### ISSUE TITLE
[Feature Request] Add a next_observations field to RolloutBufferSamples

### ISSUE THREAD

**Issue by eohomegrownapps** [DLR-RM/stable-baselines3#1328] opened 2023-02-12 18:53 UTC
### 🚀 Feature

When sampling from a `RolloutBuffer`, we return `RolloutBufferSample`s containing tensors of observations, actions etc. 

https://github.com/DLR-RM/stable-baselines3/blob/69b94dd6a8f93cf0b9d2201dcae9c146b8a9c75d/stable_baselines3/common/buffers.py#L473-L479

It would be nice if `RolloutBufferSamples` could also contain a batch of _next_ observations (alongside a mask that, for each observation, tells us whether that observation has a successor).

### Motivation

I'm implementing an RL pipeline in which I extend PPO with a custom loss. For this custom loss, I need access to (observation, next observation) pairs.

In the PPO implementation 

https://github.com/DLR-RM/stable-baselines3/blob/69b94dd6a8f93cf0b9d2201dcae9c146b8a9c75d/stable_baselines3/ppo/ppo.py#L192-L197

each batch of rollout data over which we compute the PPO loss is a `RolloutBufferSample` -- and, as these consist of a random subset of observations from the `RolloutBuffer`, we do not have enough information to compute the next observation for each observation in the batch.

### Pitch

I have already implemented this feature and submitted it as a PR [to be linked after submission].

### Alternatives

Alternatively, we could return the indices of the sampled elements with respect to the original buffer. While this may allow for more general buffer manipulation, this feels less pleasant to use.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo

**Comment by araffin** [comment] 2023-02-13 08:53
> I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo


Duplicate of https://github.com/DLR-RM/stable-baselines3/issues/1273

**Closed by araffin** 2023-02-13 08:53 UTC
Labels: enhancement
