### ISSUE TITLE
[Feature Request] request title

### ISSUE THREAD

**Issue by Forbu** [DLR-RM/stable-baselines3#1021] opened 2022-08-21 12:48 UTC
### 🚀 Feature

Making stb3 compatible with gym 0.24 version

### Motivation

Some software (pettingZoo / supersuit) are only compatible with gym 0.24 so we better make the transition now.

### Pitch

Well the plan is :
- check the problematic function and correct the issues :)

### Alternatives

Keep the same dependencies to gym 0.21 :(

**Comment by Forbu** [comment] 2022-08-21 12:48
I will try to make the change

**Comment by araffin** [comment] 2022-08-21 13:27
Duplicate of #780

**Closed by araffin** 2022-08-21 13:27 UTC
Labels: duplicate, enhancement, RTFM
