### ISSUE TITLE
[Question] Custom policy which is exactly same with the original one doesn't work.

### ISSUE THREAD

**Issue by seonwookim92** [DLR-RM/stable-baselines3#1539] opened 2023-06-03 01:53 UTC
### ❓ Question

I used a custom q_net for DQN. And found out that it's not working at all.

The original one is being converged with improved reward values, but the one with the custom network is rather getting worse.

I have no idea why it's not working since I intentionally designed the network architecture exactly the same as the original one.

![image](https://github.com/DLR-RM/stable-baselines3/assets/120056454/4bdd5f57-4394-45b6-b9d2-e98221525391)

Is there anything I'm missing?

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by qgallouedec** [comment] 2023-06-03 09:52
> - [x] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

Please do not tick the box if you do not meet the associated requirements.

It's also impossible to help you as it is, because you've provided neither the code to reproduce nor the results you're wondering about.  I can only advise you to follow the documentation about [custom network architecture](https://stable-baselines3.readthedocs.io/en/master/guide/custom_policy.html#custom-network-architecture).

**Comment by araffin** [comment] 2023-06-15 20:51
Closing as the issue template was not filled completely (and probably a duplicate of the linked issues).

**Closed by araffin** 2023-06-15 20:51 UTC
Labels: question, more information needed
