### ISSUE TITLE
Mixed Precision Training

### ISSUE THREAD

**Issue by LSC527** [DLR-RM/stable-baselines3#709] opened 2021-12-30 08:54 UTC
### 🚀 Feature

Support mixed precision training

### Motivation

Mixed precision training can significantly reduce the training time of NN. But it seems in RL, data type is always FP32. Does mixed precision training have a bad effect on the performance of RL?

**Comment by araffin** [comment] 2021-12-30 08:59
Duplicate of https://github.com/DLR-RM/stable-baselines3/issues/344

**Closed by araffin** 2021-12-30 08:59 UTC
Labels: duplicate, enhancement, more information needed
