### ISSUE TITLE
[Question] Does it make sense to make small-sized discrete actions continious?

### ISSUE THREAD

**Issue by Juphex** [DLR-RM/stable-baselines3#1482] opened 2023-05-04 17:31 UTC
### ❓ Question

Hi, I have an action space of the following type: (Discrete, Box, Box). The Discrete part corresponds to keys on the keyboard for 10 keys.
I decided to make this one also continous and map the predicted value to discrete ones. It seemed to be easiert to have an action Space that is of type Box but with 3 Dimensions. Does this work/make sense?
I know there are some issues on this but I think my question is slightly different.

### Checklist

- [ ] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment] 2023-05-05 09:17
Duplicate of https://github.com/DLR-RM/stable-baselines3/issues/527, https://github.com/DLR-RM/stable-baselines3/issues/731, https://github.com/hill-a/stable-baselines/issues/100, https://github.com/DLR-RM/stable-baselines3/issues/1094

> Does this work/make sense?

Well, it doesn't hurt to try first. You can also see other alternatives in the linked issues.

**Comment by Juphex** [comment] 2023-05-05 10:19
Thank you, what I have got is that my loss is far more negative than before :) 
Interestingly, when using all Box I can observe that my loss is moving up and down instead of descreasing continuously.

**Closed** 2023-05-05 17:53 UTC
Labels: duplicate, question, No tech support
