### ISSUE TITLE
[Feature Request] Intel Arc GPU support

### ISSUE THREAD

**Issue by 24rspires** [DLR-RM/stable-baselines3#1658] opened 2023-08-28 02:29 UTC
### 🚀 Feature

Support Intel Arc GPUs through the [Intel Extension](https://pytorch.org/tutorials/recipes/recipes/intel_extension_for_pytorch.html)

### Motivation

The few of us who have Intel Arc cards would love to use their cards for machine learning. Especially since Intel branded these cards for machine learning. They have the hardware in them.

### Pitch

Implement the Intel® [Extension for PyTorch](https://pytorch.org/tutorials/recipes/recipes/intel_extension_for_pytorch.html)

### Alternatives

Continue to have Intel Arc users use their CPU for machine learning.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] If I'm requesting a new feature, I have proposed alternatives

**Comment by araffin** [comment] 2023-08-28 06:51
Duplicate of https://github.com/DLR-RM/stable-baselines3/issues/1564

**Closed by araffin** 2023-08-28 06:51 UTC
Labels: enhancement
