### ISSUE TITLE
Getting `'DummyVecEnv' object has no attribute 'venv'` inside callback

### ISSUE THREAD

**Issue by Mahesha999** [DLR-RM/stable-baselines3#372] opened 2021-03-29 21:48 UTC
I was trying out training agent for a [hungry geese kaggle competition](https://www.kaggle.com/c/hungry-geese) based on [this](https://www.kaggle.com/ryches/stable-baselines3-starter-wip) kernel. This kernel has implemented logic using callback to self play PPO agent against its last best version while training. However, it wasnt working out of the box using the kernel directly.

While calling `model.learn(..)`, I am getting following error:

```
c:\users\crrma\.virtualenvs\hungry_geese-ept5y6nv\lib\site-packages\stable_baselines3\common\callbacks.py:327: UserWarning: Training and eval env are not of the same type<stable_baselines3.common.vec_env.vec_transpose.VecTransposeImage object at 0x0000026180030FC8> != <stable_baselines3.common.vec_env.dummy_vec_env.DummyVecEnv object at 0x0000026190205CC8>
  warnings.warn("Training and eval env are not of the same type" f"{self.training_env} != {self.eval_env}")
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-29-a1715f315993> in <module>
     28     # TODO save pytorch model
     29 if __name__ == '__main__':
---> 30     main2()

<ipython-input-29-a1715f315993> in main2()
     23 
     24     # model.learn(total_timesteps=NUM_TIMESTEPS)
---> 25     model.learn(total_timesteps=NUM_TIMESTEPS, callback=eval_callback)
     26     model.save(MODEL_DIR)
     27 

c:\users\crrma\.virtualenvs\hungry_geese-ept5y6nv\lib\site-packages\stable_baselines3\ppo\ppo.py in learn(self, total_timesteps, callback, log_interval, eval_env, eval_freq, n_eval_episodes, tb_log_name, eval_log_path, reset_num_timesteps)
    287             tb_log_name=tb_log_name,
    288             eval_log_path=eval_log_path,
--> 289             reset_num_timesteps=reset_num_timesteps,
    290         )

c:\users\crrma\.virtualenvs\hungry_geese-ept5y6nv\lib\site-packages\stable_baselines3\common\on_policy_algorithm.py in learn(self, total_timesteps, callback, log_interval, eval_env, eval_freq, n_eval_episodes, tb_log_name, eval_log_path, reset_num_timesteps)
    225         while self.num_timesteps < total_timesteps:
    226 
--> 227             continue_training = self.collect_rollouts(self.env, callback, self.rollout_buffer, n_rollout_steps=self.n_steps)
    228 
    229             if continue_training is False:

c:\users\crrma\.virtualenvs\hungry_geese-ept5y6nv\lib\site-packages\stable_baselines3\common\on_policy_algorithm.py in collect_rollouts(self, env, callback, rollout_buffer, n_rollout_steps)
    172             # Give access to local variables
    173             callback.update_locals(locals())
--> 174             if callback.on_step() is False:
    175                 return False
    176 

c:\users\crrma\.virtualenvs\hungry_geese-ept5y6nv\lib\site-packages\stable_baselines3\common\callbacks.py in on_step(self)
     86         self.num_timesteps = self.model.num_timesteps
     87 
---> 88         return self._on_step()
     89 
     90     def on_training_end(self) -> None:

<ipython-input-8-64b02e6a82e4> in _on_step(self)
     34         self.generation = 0
     35     def _on_step(self) -> bool:
---> 36         result = super(SelfPlayCallback, self)._on_step()
     37         if result and self.best_mean_reward > BEST_THRESHOLD:
     38             self.generation += 1

c:\users\crrma\.virtualenvs\hungry_geese-ept5y6nv\lib\site-packages\stable_baselines3\common\callbacks.py in _on_step(self)
    356         if self.eval_freq > 0 and self.n_calls % self.eval_freq == 0:
    357             # Sync training and eval env if there is VecNormalize
--> 358             sync_envs_normalization(self.training_env, self.eval_env)
    359 
    360             # Reset success rate buffer

c:\users\crrma\.virtualenvs\hungry_geese-ept5y6nv\lib\site-packages\stable_baselines3\common\vec_env\__init__.py in sync_envs_normalization(env, eval_env)
     67             eval_env_tmp.ret_rms = deepcopy(env_tmp.ret_rms)
     68         env_tmp = env_tmp.venv
---> 69         eval_env_tmp = eval_env_tmp.venv

AttributeError: 'DummyVecEnv' object has no attribute 'venv'
```

Below is custom gym specific code. Full notebook with error can found [here](https://colab.research.google.com/drive/1qC5Z2KF627reJKbwbGADMo6AeLe5Zj6a?usp=sharing).

```
class GeeseGym(gym.Env):
    def __init__(self, debug = False):     
        self.geese_env = make("hungry_geese", debug = debug)  #TODO true
        
        self.config = self.geese_env.configuration
        
        self.action_space = spaces.Discrete(4)        
        self.observation_space = spaces.Box(low=0, high=255, 
                                            shape=(self.config.rows, 
                                                   self.config.columns, 
                                                   3), 
                                            dtype=np.uint8)        
        self.reward_range = (-1, 1000)
        
    def reset(self):
        self.obs = self.geese_env.reset(num_agents = 2)
        x_obs = transform_observation(self.obs, self.config)
        return x_obs
    
    def step(self, action):
        my_actions = transform_actions(action)
        opponent_action = transform_actions(0)  #TODO 
        self.obs = self.geese_env.step([my_actions, opponent_action])  #TODO      
        x_obs = transform_observation(self.obs, self.config)
        x_reward = self.obs[0].reward
        done = (self.obs[0]["status"] != "ACTIVE")
        info = self.obs[0]["info"]
        return x_obs, x_reward, done, info

class GeeseSelfPlayEnv(GeeseGym):
  # wrapper over the normal single player env, but loads the best self play model
    def __init__(self):
        super(GeeseSelfPlayEnv, self).__init__()
        self.policy = self
        self.best_model = None
        self.best_model_filename = None
    def predict(self, obs): # the policy
        if self.best_model is None:
            return self.action_space.sample() # return a random action
        else:
            action, _ = self.best_model.predict(obs)
        return action
    def reset(self):
        # load model if it's there
        modellist = [f for f in os.listdir(LOGDIR) if f.startswith("history")]
        modellist.sort()
        if len(modellist) > 0:
            filename = os.path.join(LOGDIR, modellist[-1]) # the latest best model
            if filename != self.best_model_filename:
                print("loading model: ", filename)
                self.best_model_filename = filename
                if self.best_model is not None:
                    del self.best_model
                self.best_model = PPO.load(filename, env=self)
        return super(GeeseSelfPlayEnv, self).reset()

class SelfPlayCallback(EvalCallback):
  # hacked it to only save new version of best model if beats prev self by BEST_THRESHOLD score
  # after saving model, resets the best score to be BEST_THRESHOLD
    def __init__(self, *args, **kwargs):
        super(SelfPlayCallback, self).__init__(*args, **kwargs)
        self.best_mean_reward = BEST_THRESHOLD
        self.generation = 0
    def _on_step(self) -> bool:
        result = super(SelfPlayCallback, self)._on_step()
        if result and self.best_mean_reward > BEST_THRESHOLD:
            self.generation += 1
            print("SELFPLAY: mean_reward achieved:", self.best_mean_reward)
            print("SELFPLAY: new best model, bumping up generation to", self.generation)
            source_file = os.path.join(LOGDIR, "best_model.zip")
            backup_file = os.path.join(LOGDIR, "history_"+str(self.generation).zfill(8)+".zip")
            copyfile(source_file, backup_file)
            self.best_mean_reward = BEST_THRESHOLD
        return result

def make_monitored_selfplaygym(rank =0): #TODO pass config
    def _init():
        env = GeeseSelfPlayEnv() #TODO pass config
        LOGDIR = "ppo1_selfplay"
        log_file = os.path.join(MONITOR_LOGS_DIR, str(rank))
        env = Monitor(env, log_file, allow_early_resets=True) #TODO  allow_early_resets
        return env
    return _init

def main2():
    logger.configure(folder=LOGDIR)
    
#     env = SubprocVecEnv([make_monitored_selfplaygym(i) for i in range(N_CPU)]) 
    env = make_monitored_selfplaygym()
    
    eval_callback = SelfPlayCallback(env(),
        best_model_save_path=MODEL_DIR,
        log_path=LOGDIR,
        eval_freq=EVAL_FREQ,
        n_eval_episodes=EVAL_EPISODES,
        deterministic=False)
    
    model = PPO(policy = 'MlpPolicy'
                , env = env()
                , verbose = 1
                , n_steps = 2048*16
                , batch_size = 128
                , n_epochs = 50
                , tensorboard_log = TB_LOGS_DIR
                #, tb_log_name = "ppo_vs_ppo_bfs" #TODO check if works
                , learning_rate = .01)
    
    # model.learn(total_timesteps=NUM_TIMESTEPS)
    model.learn(total_timesteps=NUM_TIMESTEPS, callback=eval_callback)
    model.save(MODEL_DIR)
    
    # TODO save pytorch model
if __name__ == '__main__':
    main2()
```

Am quite sure I miss some depth. Any quick hint?

### Checklist

- [x] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)
- [x] I have checked my env using the env checker (**required**)
- [x] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by araffin** [comment] 2021-03-29 21:57
Hello,
Please fill in the "custom gym env" template, with a **minimal** working example to reproduce the error.
My guess is that there is some warnings from the `EvalCallback` that you ignored:
https://github.com/DLR-RM/stable-baselines3/blob/8a08078ea2fd6065dd7e75ff89920c8683d58580/stable_baselines3/common/callbacks.py#L327

This errors occurs because the env passed to the `EvalCallback` is not wrapped the same way as the one used for trainings, so it fails when trying to synchronize the statistics of `VecNormalize` wrapper.

Unfortunately, if you don't provide a **minimal** working example that shows that the issue may come from SB3, as we don't do tech support (cf readme and issue templates), I will close this issue.

**Comment by araffin** [comment] 2021-03-29 22:02
> Hello,
> Please fill in the "custom gym env" template, with a **minimal** working example to reproduce the error.
> My guess is that there is some warnings from the `EvalCallback` that you ignored:
> 
> https://github.com/DLR-RM/stable-baselines3/blob/8a08078ea2fd6065dd7e75ff89920c8683d58580/stable_baselines3/common/callbacks.py#L327
> 
> This errors occurs because the env passed to the `EvalCallback` is not wrapped the same way as the one used for trainings, so it fails when trying to synchronize the statistics of `VecNormalize` wrapper.
> 
> Unfortunately, if you don't provide a **minimal** working example that shows that the issue may come from SB3, as we don't do tech support (cf readme and issue templates), I will close this issue.

In your notebook, it says:
```
/usr/local/lib/python3.7/dist-packages/stable_baselines3/common/callbacks.py:327: UserWarning: Training and eval env are not of the same type<stable_baselines3.common.vec_env.vec_transpose.VecTransposeImage object at 0x7fa03b845a50> != <stable_baselines3.common.vec_env.dummy_vec_env.DummyVecEnv object at 0x7fa03b8b2450>
```

so, you have two options:
1. Use channel-first image instead of channel-last (this will remove the need of `VecTranspose`
2. Wrap your eval env using a `VecTranspose` wrapper (you need to create a `VecEnv` first)

**Closed** 2021-03-31 08:31 UTC
Labels: No tech support, custom gym env, documentation, question
