### ISSUE TITLE
[Bug]: RuntimeError: Could not infer dtype of numpy.float32

### ISSUE THREAD

**Issue by zenBandara** [DLR-RM/stable-baselines3#1964] opened 2024-07-06 08:49 UTC
### 🐛 Bug

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[197], line 1
----> 1 model.learn(total_timesteps=20000)

File ~\OneDrive\Desktop\RL\env\Lib\site-packages\stable_baselines3\ppo\ppo.py:315, in PPO.learn(self, total_timesteps, callback, log_interval, tb_log_name, reset_num_timesteps, progress_bar)
    306 def learn(
    307     self: SelfPPO,
    308     total_timesteps: int,
   (...)
    313     progress_bar: bool = False,
    314 ) -> SelfPPO:
--> 315     return super().learn(
    316         total_timesteps=total_timesteps,
    317         callback=callback,
    318         log_interval=log_interval,
    319         tb_log_name=tb_log_name,
    320         reset_num_timesteps=reset_num_timesteps,
    321         progress_bar=progress_bar,
    322     )

File ~\OneDrive\Desktop\RL\env\Lib\site-packages\stable_baselines3\common\on_policy_algorithm.py:300, in OnPolicyAlgorithm.learn(self, total_timesteps, callback, log_interval, tb_log_name, reset_num_timesteps, progress_bar)
    297 assert self.env is not None
    299 while self.num_timesteps < total_timesteps:
--> 300     continue_training = self.collect_rollouts(self.env, callback, self.rollout_buffer, n_rollout_steps=self.n_steps)
    302     if not continue_training:
    303         break

File ~\OneDrive\Desktop\RL\env\Lib\site-packages\stable_baselines3\common\on_policy_algorithm.py:178, in OnPolicyAlgorithm.collect_rollouts(self, env, callback, rollout_buffer, n_rollout_steps)
    174     self.policy.reset_noise(env.num_envs)
    176 with th.no_grad():
    177     # Convert to pytorch tensor or to TensorDict
--> 178     obs_tensor = obs_as_tensor(self._last_obs, self.device)
    179     actions, values, log_probs = self.policy(obs_tensor)
    180 actions = actions.cpu().numpy()

File ~\OneDrive\Desktop\RL\env\Lib\site-packages\stable_baselines3\common\utils.py:485, in obs_as_tensor(obs, device)
    477 """
    478 Moves the observation to the given device.
    479 
   (...)
    482 :return: PyTorch tensor of the observation on a desired device.
    483 """
    484 if isinstance(obs, np.ndarray):
--> 485     return th.as_tensor(obs, device=device)
    486 elif isinstance(obs, dict):
    487     return {key: th.as_tensor(_obs, device=device) for (key, _obs) in obs.items()}

RuntimeError: Could not infer dtype of numpy.float32

### To Reproduce

```python
from stable_baselines3 import ...

```

### Checklist

- [X] My issue does not relate to a custom gym environment. (Use the custom gym env template instead)
- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have provided a [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014) example to reproduce the bug
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment] 2024-07-06 11:52
duplicate of https://github.com/DLR-RM/stable-baselines3/issues/1960

**Closed by araffin** 2024-07-06 11:52 UTC
Labels: bug, duplicate, more information needed, windows, check the checklist
