### ISSUE TITLE
[Bug] model trained couldn't load

### ISSUE THREAD

**Issue by dotaking2021** [DLR-RM/stable-baselines3#403] opened 2021-04-20 18:08 UTC
Model trained on PPO on a Linux GPU machine. 

Then, I took the model and load on a MacBook.

Then, when loading...

`PPO.load('policy')`

```
/Users/dd/miniconda3/envs/tf_new/lib/python3.8/site-packages/stable_baselines3/common/save_util.py:166: UserWarning: Could not deserialize object lr_schedule. Consider using `custom_objects` argument to replace this object.
  warnings.warn(
/Users/dd/miniconda3/envs/tf_new/lib/python3.8/site-packages/stable_baselines3/common/save_util.py:166: UserWarning: Could not deserialize object clip_range_vf. Consider using `custom_objects` argument to replace this object.
  warnings.warn(
Traceback (most recent call last):
  File "run.py", line 25, in <module>
    model = PPO.load("/Volumes/easystore/rerun/pong_v1/policy")
  File "/Users/dd/miniconda3/envs/tf_new/lib/python3.8/site-packages/stable_baselines3/common/base_class.py", line 645, in load
    model._setup_model()
  File "/Users/dd/miniconda3/envs/tf_new/lib/python3.8/site-packages/stable_baselines3/ppo/ppo.py", line 152, in _setup_model
    self.clip_range = get_schedule_fn(self.clip_range)
  File "/Users/dd/miniconda3/envs/tf_new/lib/python3.8/site-packages/stable_baselines3/common/utils.py", line 88, in get_schedule_fn
    assert callable(value_schedule)
AssertionError

```

**Comment by Miffyli** [comment] 2021-04-20 19:12
Please fill in the issue template and include minimal code to replicate the issue, along with the system details where you experienced the bug. Saving/loading has not been extensively tested between operating systems, so there is a good chance something bugs out.

**Comment by araffin** [comment] 2021-04-20 19:27
probably a duplicate of https://github.com/DLR-RM/stable-baselines3/issues/172

**Comment by dotaking2021** [comment] 2021-04-23 02:12
basically just what @araffin  says. it is. python version difference

**Closed** 2021-04-23 05:43 UTC
Labels: bug, duplicate, more information needed
