### ISSUE TITLE
[Question] WandB logging with SubprocVecEnv

### ISSUE THREAD

**Issue by tfederico** [DLR-RM/stable-baselines3#828] opened 2022-03-22 15:16 UTC
### Question

Is it possible to perform logging using the WandB callback while using the SubprocVecEnv? I tried but I am encountering errors, so I'd like to know if you already tried this.

### Additional context

If I create a run for each different environment in a subprocess (basically call `wand.init` inside the env), I get the following error
`AssertionError: daemonic processes are not allowed to have children`

However, if I create one single run and perform the logging in the subprocesses, I get a different error (basically the PID of the process initializing the run and the PID of the processes performing the logs are different)

### Checklist

- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by tfederico** [comment] 2022-03-22 16:21
At this branch you should be able to reproduce the PID error
https://github.com/tfederico/ASLMimic/tree/pid_error

I was not able to reproduce the daemon error again, but I am getting a different error now `AssertionError: can only test a child process` which should be reproducible at this branch
https://github.com/tfederico/ASLMimic/tree/daemon_error

**Comment by tfederico** [comment] 2022-03-22 16:54
@araffin I noticed that in the RL zoo you never call `wand.log(...)` so maybe it's related to that?

**Comment by araffin** [comment] 2022-03-22 17:30
>  I noticed that in the RL zoo you never call wand.log(...) so maybe it's related to that?

Pinging @vwxyzjn as he was the one that did the integration.
I would anyway recommend you to use SB3 logger if you want to log additional values, they will be stored thanks to tensorboard integration.

**Comment by tfederico** [comment] 2022-03-23 14:55
As far as I can see with my code not calling the `wandb.log(...)` function also significantly reduces the amount of data logged on WandB when compared to tensorflow. Example:

![image](https://user-images.githubusercontent.com/15323014/159728195-2b7989aa-ffeb-4383-8fd9-f7da584ffa5e.png)

**
![image](https://user-images.githubusercontent.com/15323014/159728276-5aa2d6d0-c3c1-47e2-9665-18634aef2848.png)
**

**Comment by vwxyzjn** [comment] 2022-03-23 14:58
@tfederico try switching the x-axis from "Step" to "global_step"

![explain](https://user-images.githubusercontent.com/5555347/159728892-09fb4944-f5bc-4001-975b-8c332fe9acfb.gif)

**Comment by tfederico** [comment] 2022-03-23 15:02
Thanks, that worked! Any idea why I am getting the PID error that I mentioned earlier?

**Comment by vwxyzjn** [comment] 2022-03-23 15:04
@tfederico reading this further, why would you initialize a run within each env?

**Comment by araffin** [comment] 2022-04-11 16:36
> I should call init in each subprocess, right?

I don't think so, callback is in the main thread, not in the subprocesses. Closing as the issue is related to W&B, not SB3, and as the W&B works fine in the RL Zoo with multiple envs (and with subprocesses).
See for instance https://wandb.ai/openrlbenchmark/sb3/runs/2tf89ihi?workspace=user-araffin

**Closed by araffin** 2022-04-11 16:36 UTC
Labels: question, more information needed
