### ISSUE TITLE
[Question] Can I train agents in a nested loop in SB3?

### ISSUE THREAD

**Issue by j-thib** [DLR-RM/stable-baselines3#1491] opened 2023-05-08 23:05 UTC
### ❓ Question

I am interested in training two agents, where the actions of one affects the environment of the other, and vice-versa. I understand that SB3 is not designed for multi-agent systems, but I'm not sure if this necessarily has to be treated as a multi-agent problem. The pseudo-code for my learning problem is the following:
``` 
Initialize environment

Repeat for X episodes:
  Agent 1 takes action a1
  Repeat for N steps:
      Agent 2 takes action a2
      Environment is updated according to a1, a2
      Agent 2 collects reward r2
  Agent 1 collects reward r1

  Update environment
```
I am training on a custom env which returns no bugs in the env_checker. Any advice on how I could proceed in SB3 would be much appreciated, or if this certainly impossible to do in SB3 it would also be useful to know that.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [x] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment] 2023-05-09 08:47
Duplicate of https://github.com/DLR-RM/stable-baselines3/issues/1094 and https://github.com/DLR-RM/stable-baselines3/issues/957#issuecomment-1180492849

**Closed** 2023-05-14 17:02 UTC
Labels: duplicate, question
