### ISSUE TITLE
AttributeError: 'DummyVecEnv' object has no attribute 'venv'

### ISSUE THREAD

**Issue by patterntrade** [DLR-RM/stable-baselines3#388] opened 2021-04-11 11:53 UTC
### 🐛 Bug

CartPole-type envs working, but not Atari envs. I believe this to be a bug, or if not, the code in this area is a bit brittle.

Complains: AttributeError: 'DummyVecEnv' object has no attribute 'venv'

```
A new study created in RDB with name: no-name-8e7e1b56-83a6-4a28-b949-e97b2774d063
/home/USR/.virtualenvs/stab3/lib/python3.8/site-packages/stable_baselines3/common/callbacks.py:327: UserWarning: Training and eval env are not of the same type<stable_baselines3.common.vec_env.vec_transpose.VecTransposeImage object at 0x7fd3e4d1feb0> != <stable_baselines3.common.vec_env.dummy_vec_env.DummyVecEnv object at 0x7fd3e4c01730>
  warnings.warn("Training and eval env are not of the same type" f"{self.training_env} != {self.eval_env}")
[W 2021-04-11 13:31:13,582] Trial 0 failed because of the following error: AttributeError("'DummyVecEnv' object has no attribute 'venv'")
Traceback (most recent call last):
  File "/home/USR/.virtualenvs/stab3/lib/python3.8/site-packages/optuna/_optimize.py", line 217, in _run_trial
    value_or_values = func(trial)
  File "/home/USR/stab3/opt_multi_gpu.py", line 138, in __call__
    model.learn(N_TIMESTEPS, callback=eval_callback)
  File "/home/USR/.virtualenvs/stab3/lib/python3.8/site-packages/stable_baselines3/a2c/a2c.py", line 190, in learn
    return super(A2C, self).learn(
  File "/home/USR/.virtualenvs/stab3/lib/python3.8/site-packages/stable_baselines3/common/on_policy_algorithm.py", line 227, in learn
    continue_training = self.collect_rollouts(self.env, callback, self.rollout_buffer, n_rollout_steps=self.n_steps)
  File "/home/USR/.virtualenvs/stab3/lib/python3.8/site-packages/stable_baselines3/common/on_policy_algorithm.py", line 174, in collect_rollouts
    if callback.on_step() is False:
  File "/home/USR/.virtualenvs/stab3/lib/python3.8/site-packages/stable_baselines3/common/callbacks.py", line 88, in on_step
    return self._on_step()
  File "/home/USR/stab3/opt_multi_gpu.py", line 98, in _on_step
    super()._on_step()
  File "/home/USR/.virtualenvs/stab3/lib/python3.8/site-packages/stable_baselines3/common/callbacks.py", line 358, in _on_step
    sync_envs_normalization(self.training_env, self.eval_env)
  File "/home/USR/.virtualenvs/stab3/lib/python3.8/site-packages/stable_baselines3/common/vec_env/__init__.py", line 69, in sync_envs_normalization
    eval_env_tmp = eval_env_tmp.venv
AttributeError: 'DummyVecEnv' object has no attribute 'venv'
```
### To Reproduce

What I'm trying to achieve:
* [Hyperparameter tuning with Optuna ](https://github.com/optuna/optuna/issues/1365) I want to pass custom hyperparam ranges.
* [Running on both GPUs](https://github.com/optuna/optuna/blob/master/examples/rl/sb3_simple.py) Speed things up. To my knowledge SB3 does not support multiple GPUs natively.
* Code a combination of the two above
* End objective is to run custom envs.

The code might not be beautiful, but it works with CartPole. It's a first prototype. Does not work with Atari envs.

I therefore don't think it's an issue with my code as such, although it of course could be.

I'm no seasoned programmer. Have tried to parse the sb3 libraries, but can't seem to find a solution.

Assistance would be warmly welcomed.

```
from dask.distributed import Client, wait
from dask_cuda import LocalCUDACluster
from typing import Any
from typing import Dict

import gym
from stable_baselines3 import A2C
from stable_baselines3.common.callbacks import EvalCallback
import torch
import torch.nn as nn

import optuna
from optuna.pruners import MedianPruner
from optuna.samplers import TPESampler
import time

from multiprocessing import Manager
from joblib import parallel_backend


N_TRIALS = 100
N_JOBS = 2
N_STARTUP_TRIALS = 5
N_EVALUATIONS = 2
N_TIMESTEPS = int(2e3)
EVAL_FREQ = int(N_TIMESTEPS / N_EVALUATIONS)
N_EVAL_EPISODES = 3

ENV_ID = "BattleZone-v4" #  WORKS NOT
#ENV_ID="CartPole-v1"       WORKS

DEFAULT_HYPERPARAMS = {
    "policy": "MlpPolicy",
    "env": ENV_ID,
}
#   https://github.com/optuna/optuna/blob/master/examples/rl/sb3_simple.py

def sample_a2c_params(trial: optuna.Trial) -> Dict[str, Any]:
    """Sampler for A2C hyperparameters."""
    gamma = 1.0 - trial.suggest_float("gamma", 0.0001, 0.1, log=True)
    max_grad_norm = trial.suggest_float("max_grad_norm", 0.3, 5.0, log=True)
    gae_lambda = 1.0 - trial.suggest_float("gae_lambda", 0.001, 0.2, log=True)
    n_steps = 2 ** trial.suggest_int("exponent_n_steps", 3, 10)
    learning_rate = trial.suggest_float("lr", 1e-5, 1, log=True)
    ent_coef = trial.suggest_float("ent_coef", 0.00000001, 0.1, log=True)
    ortho_init = trial.suggest_categorical("ortho_init", [False, True])
    net_arch = trial.suggest_categorical("net_arch", ["tiny", "small"])
    activation_fn = trial.suggest_categorical("activation_fn", ["tanh", "relu"])

    # Display true values
    trial.set_user_attr("gamma_", gamma)
    trial.set_user_attr("gae_lambda_", gae_lambda)
    trial.set_user_attr("n_steps", n_steps)

    net_arch = [
        {"pi": [64], "vf": [64]} if net_arch == "tiny" else {"pi": [64, 64], "vf": [64, 64]}
    ]

    activation_fn = {"tanh": nn.Tanh, "relu": nn.ReLU}[activation_fn]

    return {
        "n_steps": n_steps,
        "gamma": gamma,
        "gae_lambda": gae_lambda,
        "learning_rate": learning_rate,
        "ent_coef": ent_coef,
        "max_grad_norm": max_grad_norm,
        "policy_kwargs": {
            "net_arch": net_arch,
            "activation_fn": activation_fn,
            "ortho_init": ortho_init,
        },
    }


class TrialEvalCallback(EvalCallback):
    """Callback used for evaluating and reporting a trial."""

    def __init__(
        self,
        eval_env: gym.Env,
        trial: optuna.Trial,
        n_eval_episodes: int = 5,
        eval_freq: int = 10000,
        deterministic: bool = True,
        verbose: int = 0,
    ):

        super().__init__(
            eval_env=eval_env,
            n_eval_episodes=n_eval_episodes,
            eval_freq=eval_freq,
            deterministic=deterministic,
            verbose=verbose,
        )
        self.trial = trial
        self.eval_idx = 0
        self.is_pruned = False

    def _on_step(self) -> bool:
        if self.eval_freq > 0 and self.n_calls % self.eval_freq == 0:
            super()._on_step()
            self.eval_idx += 1
            self.trial.report(self.last_mean_reward, self.eval_idx)
            # Prune trial if need
            if self.trial.should_prune():
                self.is_pruned = True
                return False
        return True

class Objective:
    def __init__(self, gpu_queue):
        self.gpu_queue=gpu_queue

    def __call__(self, trial):

                # Fetch GPU ID for this trial.
        gpu_id = self.gpu_queue.get()

        # Please write actual objective function here.
        #time.sleep(random.randint(1, 8))


        # GPU ID is stored as an objective value.


        kwargs = DEFAULT_HYPERPARAMS.copy()
        # Sample hyperparameters
        kwargs.update(sample_a2c_params(trial))
        # Create the RL model
        model = A2C(**kwargs)
        # Create env used for evaluation
        eval_env = gym.make(ENV_ID)
        # Create the callback that will periodically evaluate
        # and report the performance
        eval_callback = TrialEvalCallback(
            eval_env, trial, n_eval_episodes=N_EVAL_EPISODES, eval_freq=EVAL_FREQ, deterministic=True
        )

        nan_encountered = False
        try:
            model.learn(N_TIMESTEPS, callback=eval_callback)
        except AssertionError as e:
            # Sometimes, random hyperparams can generate NaN
            print(e)
            nan_encountered = True
        finally:
            # Free memory
            model.env.close()
            eval_env.close()

        # Tell the optimizer that the trial failed
        if nan_encountered:
            return float("nan")

        if eval_callback.is_pruned:
            raise optuna.exceptions.TrialPruned()

        
        # Return GPU ID to the queue.
        self.gpu_queue.put(gpu_id)

        return eval_callback.last_mean_reward

    

        # return gpu_id


if __name__ == '__main__':
    #freeze_support()

    # Set pytorch num threads to 1 for faster training
    n_gpu=2

    torch.set_num_threads(1)

    sampler = TPESampler(n_startup_trials=N_STARTUP_TRIALS)
    # Do not prune before 1/3 of the max budget is used
    pruner = MedianPruner(n_startup_trials=N_STARTUP_TRIALS, n_warmup_steps=N_EVALUATIONS // 3)

    cluster = LocalCUDACluster()
    client = Client(cluster)

    ... # Objective class

    study = optuna.create_study(storage="sqlite:///example.db", direction="maximize",sampler=sampler, pruner=pruner)
    with Manager() as manager:

        # Initialize the queue by adding available GPU IDs.
        gpu_queue = manager.Queue()
        for i in range(n_gpu):
            gpu_queue.put(i)
        with parallel_backend("dask", n_jobs=n_gpu):
            study.optimize(Objective(gpu_queue), n_trials=10, n_jobs=n_gpu)
```

### Expected behavior

Atari and custom env's to work just as well as EG CartPole

### System Info

* Ubuntu desktop
* All installed with pip
* 2x RTX 2070
* 48 GB RAM
* Python 3.8.5 64-bit
* Pytorch 1.8.1+cu102
* Gym version 0.18.0
* Stable_baselines3 1.0
* x86 architecture

### Checklist

- [v] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)
- [v] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [v] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by araffin** [comment] 2021-04-11 12:13
Duplicate of https://github.com/DLR-RM/stable-baselines3/issues/372

**Closed** 2021-04-15 16:48 UTC
Labels: duplicate
