### ISSUE TITLE
Multi Agents Reinforcement Learning

### ISSUE THREAD

**Issue by ZijianAn1999** [DLR-RM/stable-baselines3#1965] opened 2024-07-08 22:15 UTC
### ❓ Question

It seems that this system does not support MARL ?

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [ ] If code there is, it is [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014)
- [ ] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment] 2024-07-09 06:25
Duplicate of https://github.com/DLR-RM/stable-baselines3/issues/69 and https://github.com/DLR-RM/stable-baselines3/issues/1626

**Closed by araffin** 2024-07-09 06:25 UTC
Labels: duplicate, question, RTFM
