### ISSUE TITLE
gym==0.21 error

### ISSUE THREAD

**Issue by mq-maqi** [DLR-RM/stable-baselines3#1455] opened 2023-04-14 12:50 UTC
### 🐛 Bug

When I want to install the baseline using pip, it gives me an error

### To Reproduce

```python
pip install stable_baselines3

```

### Relevant log output / Error message

```shell
Best match: gym 0.21.0
Processing gym-0.21.0.tar.gz
Writing /tmp/easy_install-jwksakfi/gym-0.21.0/setup.cfg
Running gym-0.21.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-jwksakfi/gym-0.21.0/egg-dist-tmp-86d8m70b
error: Setup script exited with error in gym setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers.
```

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have provided a minimal working example to reproduce the bug
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment] 2023-04-14 12:53
> have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo

are you sure?


Duplicate of #1406 and https://github.com/openai/gym/issues/3176#issuecomment-1408598628 and #1324

**Closed by araffin** 2023-04-14 12:53 UTC
Labels: bug, duplicate

**Comment by mq-maqi** [comment] 2023-04-14 12:58
Thank you for your reply
