### ISSUE TITLE
AssertionError: The algorithm only supports (<class 'gym.spaces.discrete.Discrete'>,) 

### ISSUE THREAD

**Issue by Superduper97** [DLR-RM/stable-baselines3#1371] opened 2023-03-09 12:47 UTC
### ❓ Question

I am trying to run an rl environment from a GitHub project and I keep getting the following error:

Traceback (most recent call last):
  File "C:\Users\glenn\Desktop\sumo-rl-test\experiments\dqn_2way-single-intersection.py", line 29, in <module>
    model = DQN(
  File "E:\Users\glenn\anaconda3\envs\sumo-rl\lib\site-packages\stable_baselines3\dqn\dqn.py", line 98, in __init__
    super().__init__(
  File "E:\Users\glenn\anaconda3\envs\sumo-rl\lib\site-packages\stable_baselines3\common\off_policy_algorithm.py", line 106, in __init__
    super().__init__(
  File "E:\Users\glenn\anaconda3\envs\sumo-rl\lib\site-packages\stable_baselines3\common\base_class.py", line 168, in __init__
    assert isinstance(self.action_space, supported_action_spaces), (
AssertionError: The algorithm only supports (<class 'gym.spaces.discrete.Discrete'>,) as action spaces but Discrete(4) was provided

Could anyone provide information on why this would be happening?

Thanks

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment] 2023-03-09 12:51
> I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo

Duplicate of https://github.com/DLR-RM/stable-baselines3/issues/1274 and https://github.com/Farama-Foundation/Gymnasium/issues/348

Please follow installation instructions of https://github.com/DLR-RM/stable-baselines3/pull/1327 to have a SB3 version compatible with Gymnasium.

**Closed by araffin** 2023-03-09 12:51 UTC
Labels: duplicate, question
