### ISSUE TITLE
[Question] In evaluate.py - `evaluation_policy()` function why isn't the env.reset called after every episode

### ISSUE THREAD

**Issue by athatheo** [DLR-RM/stable-baselines3#1114] opened 2022-10-13 14:06 UTC
### Question
So the questions is what the title says. I'd expect that the environment would be reset after every episode, but apparently that isn't the case. How come?

**Comment by qgallouedec** [comment] 2022-10-13 14:12
Well, it is the case.
Maybe what makes you confused is that the VecEnv are automatically reset (in the step function) when the done signal is sent.

https://github.com/DLR-RM/stable-baselines3/blob/ef332fa50d635e28a1fdee227fe91b5fdb05877d/stable_baselines3/common/vec_env/dummy_vec_env.py#L49

**Comment by araffin** [comment] 2022-10-13 14:20
Duplicate of https://github.com/DLR-RM/stable-baselines3/issues/719

**Closed by araffin** 2022-10-13 14:20 UTC
Labels: duplicate, question
