### ISSUE TITLE
I would like to know what is the network structure of the SAC algorithm

### ISSUE THREAD

**Issue by hjg857** [DLR-RM/stable-baselines3#1976] opened 2024-07-22 15:33 UTC
### ❓ Question

I use MultiInputPolicy

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014)
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment] 2024-07-22 15:45
Duplicate of https://github.com/DLR-RM/stable-baselines3/issues/329 and https://github.com/DLR-RM/stable-baselines3/issues/1005

**Closed** 2024-07-29 08:58 UTC
Labels: duplicate, question
