### ISSUE TITLE
[Question] Is DQN actually Double DQN? 

### ISSUE THREAD

**Issue by oliverc1623** [DLR-RM/stable-baselines3#1737] opened 2023-11-06 17:01 UTC
### ❓ Question

Hi, first off great work on making Stable-Baselines3 an excellent resource for deep reinforcement learning practitioners.

I noticed that your DQN implementation features a target q network which resembles Google's Deep Mind paper, Deep Reinforcement Learning with Double Q-learning. Meanwhile, Neural Fitted Q Iteration, by Riedmiller, calculates the target using the "current estimate" of the Q function. I am looking for clarification if DQN is truly a Double DQN. I hope to use this information to accurately hopefully implement prioritized experience replay based off of your DQN implementation. 

Thanks,
Oliver

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [x] If code there is, it is [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014)
- [x] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment] 2023-11-06 17:33
Duplicate of https://github.com/DLR-RM/stable-baselines3/issues/487

It is not, current DQN is the vanilla DQN (cf. doc), but we are working (and welcome help) on https://github.com/DLR-RM/stable-baselines3/issues/622 (there is a PR for PER).
However, we do provide QR-DQN in SB3 contrib repo.

**Closed** 2023-11-06 20:20 UTC
Labels: duplicate, question, RTFM

**Comment by oliverc1623** [comment] 2023-11-06 20:21
Thanks for the clarification, will read up on #487 and the papers more throughly.
