### ISSUE TITLE
[Question] `log_std` in SAC vs. PPO

### ISSUE THREAD

**Issue by PatrickHelm** [DLR-RM/stable-baselines3#1656] opened 2023-08-25 10:20 UTC
### ❓ Question

Hello, 

I have a question regarding the treatment of the `log_std` in SAC compared to PPO. 
SAC uses a  `SquashedDiagGaussianDistribution` by default, while PPO uses a `DiagGaussianDistribution`

For the `SquashedDiagGaussianDistribution`, the actor directly outputs the `log_std` along with the `mu`, as can be seen here:

https://github.com/DLR-RM/stable-baselines3/blob/f4ec0f6afa1a23b0e0b746174cd0074471cc0b89/stable_baselines3/sac/policies.py#L101C1-L103C93

For the `DiagGaussianDistribution`, the actor only outputs the `mean_actions` while the `log_std` is defined as a separate learnable parameter, as can be seen here:

https://github.com/DLR-RM/stable-baselines3/blob/f4ec0f6afa1a23b0e0b746174cd0074471cc0b89/stable_baselines3/common/distributions.py#L148C1-L150C92

What is the rationale for using these two distinct options by default?

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014)
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment] 2023-08-25 12:12
Duplicate of https://github.com/hill-a/stable-baselines/issues/652 
related to https://github.com/DLR-RM/stable-baselines3/issues/133

**Closed** 2023-08-25 12:25 UTC
Labels: duplicate, question
