### ISSUE TITLE
Recurrent layer support for Online policy algorithms

### ISSUE THREAD

**Issue by Bharath2** [DLR-RM/stable-baselines3#550] opened 2021-08-22 05:55 UTC
### 🚀 Feature

Please add Recurrent layer Support for PPO and A2C

### Motivation
I am working on agile 3d biped locomotion. I feel that PPO with a recurrent layer like LSTM will greatly help.

### Pitch

Stable-baselines tensorflow version have options like MlpLSTMPolicy for algorithms like PPO2 and A2C. 
I can see in the source code of stable-baselines3 that the predict method of BasePolicy class has some provision for recurrent policies, But the OnPolicyAlgorithm class does not take that in to account.

I would also like to contribute to this.

### Checklist

- [y] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo

**Comment by Miffyli** [comment] 2021-08-22 10:02
Duplicate of #18, closing as such. 

Yup they would be cool to have, but nobody has had the time to come around to implement them yet (also the benefit of LSTMs outside complex tasks is questionable, (see e.g. this)[https://blog.aqnichol.com/2019/07/24/competing-in-the-obstacle-tower-challenge/] and [bottom of this](https://arxiv.org/abs/1912.01588)). Try framestacking meanwhile.

**Closed by Miffyli** 2021-08-22 10:02 UTC
Labels: enhancement
