### ISSUE TITLE
[Question] How to implement RNN?

### ISSUE THREAD

**Issue by densechen** [DLR-RM/stable-baselines3#279] opened 2020-12-29 15:26 UTC
Hi, I want to implement a policy network for RNN, but I only found the following message:
```
        # TODO (GH/1): add support for RNN policies
        # if state is None:
        #     state = self.initial_state
        # if mask is None:
        #     mask = [False for _ in range(self.n_envs)]
```

I check the state, but cannot find how to control the state value.

I think it will be better and easy to implement that make the policy network ifself to maintian all hidden states, and add a function of reset() to policy network. the RL algorithom only need to call the reset() at the begining of each episode.

Or can you tell me that how it implement currently to support RNN learning?

Best

**Comment by Miffyli** [comment] 2021-01-04 12:41
Closing as (sort of) duplicate of #160.

Support for RNNs will require modifications in many parts of the code (e.g. policies, algorithms, buffers) and is left for next major version. Right now there is no easy way to do it, and we still need to discuss what is the approach we will take for SB3 that is clean and functionally satisfactory.

**Closed by Miffyli** 2021-01-04 12:41 UTC
Labels: Maintainers on vacation, question
