### ISSUE TITLE
[Bug]: EvalCallback continues from previous evaluation

### ISSUE THREAD

**Issue by IAmTheNail** [DLR-RM/stable-baselines3#1389] opened 2023-03-17 22:11 UTC
### 🐛 Bug

When rendering a evaluation, it is clear the evaluation continues from where the previous evaluation left. Instead of restarting from the initial game state. Which has dire consequences on the results.   

I've been tracing the code and came, maybe, across the culprit: EpisodicLifeEnv. It inhibits the reset of the embedded environment when there are lives left. That is correct reasoning, except for one case: The very first reset of each evaluation. This one must take place, even if there are lives left.

Run the provided code sample. Observe from the second evaluation on, the games simply resume instead of restarting. Balls frozen in mid air suddenly resume their trajectory. :-) 

### To Reproduce

```python
import os

from stable_baselines3 import A2C
from stable_baselines3.common.callbacks import EvalCallback, BaseCallback
from stable_baselines3.common.env_util import make_atari_env
from stable_baselines3.common.vec_env import VecFrameStack
from stable_baselines3.common.vec_env.vec_transpose import VecTransposeImage

cpus = 4
environment_name = "BreakoutNoFrameskip-v4"
env = make_atari_env(environment_name, n_envs=cpus, seed=0)
env = VecFrameStack(env, n_stack=4)
env = VecTransposeImage(env)

eval_env = make_atari_env(environment_name, n_envs=cpus, seed=0)
eval_env = VecFrameStack(eval_env, n_stack=4)
eval_env = VecTransposeImage(eval_env)

log_path = os.path.join("training", "breakout", "logs")
model_path = os.path.join("training", "breakout", "A2C")
model = None
try:
    callback = EvalCallback(eval_env,
                            eval_freq=1_000 // cpus,
                            best_model_save_path=model_path,
                            verbose=1,
                            deterministic=False,
                            render=True)

    model = A2C("CnnPolicy", env, verbose=0, tensorboard_log=log_path)
    model.learn(total_timesteps=4_000_000, callback=callback, log_interval=100_000 // cpus, progress_bar=True)

finally:
    env.close()
```

### System Info

Lubuntu Virtualbox VM. No GPU whatsoever. Installed with "pip install git+https://github.com/DLR-RM/stable-baselines3" because I've had the bug of stepping into an environment requiring a reset.

$ python -c 'import stable_baselines3 as sb3; sb3.get_system_info()'
- OS: Linux-5.19.0-35-generic-x86_64-with-glibc2.35 # 36-Ubuntu SMP PREEMPT_DYNAMIC Fri Feb 3 18:36:56 UTC 2023
- Python: 3.8.16
- Stable-Baselines3: 1.8.0a9
- PyTorch: 1.13.1+cpu
- GPU Enabled: False
- Numpy: 1.24.2
- Gym: 0.21.0

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have provided a minimal working example to reproduce the bug
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment] 2023-03-17 23:54
Mostly a duplicate of https://github.com/DLR-RM/stable-baselines3/issues/666, help is welcomed to improve the documentation.

**Closed by araffin** 2023-03-17 23:54 UTC
Labels: bug, duplicate
