### ISSUE TITLE
Installation in Google Colab is not successful with both 1.8.0 and 1.7.0

### ISSUE THREAD

**Issue by poudel-bibek** [DLR-RM/stable-baselines3#1444] opened 2023-04-11 17:37 UTC
### 🐛 Bug
Installation of `stable-baselines3[extra]` via `pip` does not work in Google Colab.
This is the specified method of installation in the main GitHub repo and also the [tutorials given by the development team](https://github.com/Stable-Baselines-Team/rl-colab-notebooks/tree/sb3).

### To Reproduce

```
!pip install -q stable-baselines3[extra]
```

```
!pip install -q stable-baselines3[extra]==1.7.0
```

```
!pip install -q stable-baselines3[extra]==1.8.0
```

### Relevant log output / Error message

```shell
error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

### System Info

Google Colab free version.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have provided a minimal working example to reproduce the bug
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment] 2023-04-11 18:55
> I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo


Duplicate of #1440 and #1406

**Closed by araffin** 2023-04-11 18:55 UTC
Labels: bug, duplicate
