### ISSUE TITLE
Custom environment with multiple episodes of 200 time steps each

### ISSUE THREAD

**Issue by R470R** [DLR-RM/stable-baselines3#1208] opened 2022-12-08 19:59 UTC
### ❓ Question

Hello, I want to make an environment wich is feeded with multiple episodes of 200 time steps each.

How can I do it?

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment] 2022-12-08 20:31
Duplicate of https://github.com/AminHP/gym-anytrading/issues/81

**Closed by araffin** 2022-12-08 20:31 UTC
Labels: question
