### ISSUE TITLE
[Question] Action masking for a DQN Agent

### ISSUE THREAD

**Issue by Tim1605** [DLR-RM/stable-baselines3#1876] opened 2024-03-20 17:33 UTC
### ❓ Question

I use a DQN agent to optimise an order release. The orders have an earliest start date, which is only reached in the course of the simulation.
Currently, orders selected by the agent, but which may not yet be released, are penalised by a penalty in the reward function. However, it would be nice if it were possible to change the action space so that the agent can only select jobs whose earliest start date has already been reached using a mask.

Hence my question as to whether it is possible to mask the action space for a DQN agent in training and/or application in this way?

I am very grateful for any help!

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014)
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment] 2024-03-20 19:17
duplicate of https://github.com/DLR-RM/stable-baselines3/issues/1352#issuecomment-1450512547

**Closed** 2024-03-25 08:11 UTC
Labels: duplicate, question
