### ISSUE TITLE
Custom Loss/Update 

### ISSUE THREAD

**Issue by James-R-Han** [DLR-RM/stable-baselines3#1405] opened 2023-03-23 14:12 UTC
### ❓ Question

Hello!

Is it possible to add a custom loss function? 

Currently, I'm trying to implement Deep-V Learning which does the following:

- Take the current state S and do a 1-step lookahead applying action 'A' to predict the next state S'
- Compute a heuristic reward R_pred over the lookahead timestep
- Compute V(S')
- Repeat previous 3 steps for all actions 
- Policy follows argmax R_pred+V(S')

Currently, I'm implementing my model on top of the DQN framework, but the update/loss here is not exactly what I want it to be. So, in the current setup, I return in my model Q1, ..., QN where each of these Q values are just R_pred+V(S'). For the update step, I don't actually want to do Q Learning where we update Qa against R+maxQ(S'_true,a'), I really just want to update R_pred+V(S') against R+V(S'_true). Here S'_true is the true next state from the simulator.

Is there an easy method to accomplish this?

Thank you in advance!

James

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment] 2023-03-23 14:29
Probably a duplicate of https://github.com/DLR-RM/stable-baselines3/issues/59 and https://github.com/DLR-RM/stable-baselines3/issues/55

For that level of customization, I would recommend to fork SB3.

**Closed** 2023-03-25 13:46 UTC
Labels: question
