### ISSUE TITLE
[Question] MARL using Stable Baselines3

### ISSUE THREAD

**Issue by Hamza-101** [DLR-RM/stable-baselines3#2007] opened 2024-09-15 14:32 UTC
### ❓ Question

1. I wanted to get pointers, if any, for achieving MARL with StableBaselines3. Have run dry on the net and reddit(hard to imagine thouugh).

Any custom MARL SB3 environments exist out there, could I be pointed to them? Not been able to find any so far.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014)
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment] 2024-09-16 09:40
Duplicate of https://github.com/DLR-RM/stable-baselines3/issues/69 and https://github.com/DLR-RM/stable-baselines3/issues/1626 and https://github.com/DLR-RM/stable-baselines3/issues/1965

**Closed by araffin** 2024-09-16 09:40 UTC
Labels: duplicate, question
