### ISSUE TITLE
How to handle the error of 4d input in custom-cnn extractor

### ISSUE THREAD

**Issue by kunalrawat2000** [DLR-RM/stable-baselines3#516] opened 2021-07-20 19:13 UTC
So i'm making a custom cnn extractor but it is giving the error i.e

**Expected 4-dimensional input for 4-dimensional weight [32, 972, 8, 8], but got 2-dimensional input of size [1, 972] instead**

what should I change in this to remove this error
```
class CustomCNN(BaseFeaturesExtractor):
    """
    :param observation_space: (gym.Space)
    :param features_dim: (int) Number of features extracted.
        This corresponds to the number of unit for the last layer.
    """

    def __init__(self, observation_space: gym.spaces.Box, features_dim: int = 256):
        super(CustomCNN, self).__init__(observation_space, features_dim)
        # We assume CxHxW images (channels first)
        # Re-ordering will be done by pre-preprocessing or wrapper
        n_input_channels = observation_space.shape[0]
        self.cnn = nn.Sequential(
            nn.Conv2d(n_input_channels, 32, kernel_size=8, stride=4, padding=0),
            nn.ReLU(),
            nn.Conv2d(32, 64, kernel_size=4, stride=2, padding=0),
            nn.ReLU(),
            nn.Flatten(),
        )

        # Compute shape by doing one forward pass
        with th.no_grad():
            n_flatten = self.cnn(
                th.as_tensor(observation_space.sample()[None]).float()
            ).shape[1]

        self.linear = nn.Sequential(nn.Linear(n_flatten, features_dim), nn.ReLU())

    def forward(self, observations: th.Tensor) -> th.Tensor:
        return self.linear(self.cnn(observations))

policy_kwargs = dict(
    features_extractor_class=CustomCNN,
    features_extractor_kwargs=dict(features_dim=128),
)
```

**Comment by araffin** [comment] 2021-07-20 19:39
Hello,
please fill the custom gmy env issue template completely.

**Comment by kunalrawat2000** [comment] 2021-07-21 06:43
Hello, 
Sorry i'm not getting what you are trying to say
I'm using gym mini-grid environment with flatobswrapper

Here is the colab link for your further consideration 
https://colab.research.google.com/drive/1JjOlKhRIfKgWnyxwvnQRRA_CYJpSzNue?usp=sharing

Thank you

**Comment by Miffyli** [comment] 2021-07-21 09:26
araffin meant that you should fill in this template and complete all points listed there: https://github.com/DLR-RM/stable-baselines3/blob/master/.github/ISSUE_TEMPLATE/custom_env.md

**Comment by araffin** [comment] 2021-07-21 09:37
>araffin meant that you should fill in this template and complete all points listed there: https://github.com/DLR-RM/stable-baselines3/blob/master/.github/ISSUE_TEMPLATE/custom_env.md

> I'm using gym mini-grid environment with flatobswrapper

yes, because otherwise we don't have minimal code to reproduce the error.
As you are using a `FlatObsWrapper`, you have a 1D obs as input but you somehow tries to use a CNN  (Conv2d, which expects an image as input) on it which results on the error that you have...

**Comment by kunalrawat2000** [comment] 2021-07-21 11:55
Yes, the problem was FlatObsWrapper I'm new to this that is why this beginner's error.
Sorry to bother you all. I have another query related to Optuna so do I ask it here or create another thread for it.
Thank You so much for the Help

**Comment by Miffyli** [comment] 2021-07-21 12:00
Optuna stuff belongs to [to the zoo repo](https://github.com/DLR-RM/rl-baselines3-zoo/).

Closing as resolved.

**Closed by Miffyli** 2021-07-21 12:00 UTC
Labels: custom gym env, more information needed, question
