### ISSUE TITLE
PyTorch RuntimeError: expected scalar type Float but found Double

### ISSUE THREAD

**Issue by nikhilbarhate99** [DLR-RM/stable-baselines3#675] opened 2021-11-24 15:47 UTC
### Description

I am using the [causal world](https://github.com/rr-learning/CausalWorld) env to train a policy. In their [paper](https://arxiv.org/pdf/2010.04296.pdf) they have evaluated PPO, SAC and TD3 using tf stablebaselines, suggesting that the env works with sb api.

As far as I understand the [env uses a Box action space](https://github.com/rr-learning/CausalWorld/blob/7e2958a1db3af4f801d6d6df4fd1e507304ca537/causal_world/envs/robot/action.py#L6) which is supported by SAC and PPO in sb3

A PPO policy with sb3 starts training without any errors.

But when I tried to train a SAC policy (with sb3 pytorch), I ran into the following error:
`RuntimeError: expected scalar type Float but found Double` 

### Code example

```python
import os
import argparse
import gym
import numpy as np
from causal_world.task_generators import generate_task
from causal_world.envs import CausalWorld
from stable_baselines3 import PPO, SAC
from stable_baselines3.common.env_checker import check_env

def train(args):
	
	#env = gym.make("BipedalWalker-v3")
	
	task = generate_task(task_generator_id='picking')
	env = CausalWorld(task=task)
	
	###### sb3 check env
	check_env(env) 
	
	if args.rl_algo == 'ppo':
		model = PPO("MlpPolicy", env, verbose=1)    
	if args.rl_algo == 'sac':	
		model = SAC("MlpPolicy", env, verbose=1)

	model.learn(total_timesteps=10000, log_interval=4)


if __name__ == "__main__":
	parser = argparse.ArgumentParser()
	parser.add_argument('--rl_algo',
		type=str,
		default='sac',
		help='rl algorihtm sac | ppo',
		required=False)							
	args = parser.parse_args()				
	train(args)

```

#### stack trace:
```bash
pybullet build time: Aug  3 2020 20:48:16
Using cpu device
Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.
Traceback (most recent call last):
  File "scripts/test_sb.py", line 47, in <module>
    train(args)
  File "scripts/test_sb.py", line 32, in train
    model.learn(total_timesteps=10000, log_interval=4)
  File "/home/cw_data_venv/lib/python3.7/site-packages/stable_baselines3/sac/sac.py", line 300, in learn
    reset_num_timesteps=reset_num_timesteps,
  File "/home/cw_data_venv/lib/python3.7/site-packages/stable_baselines3/common/off_policy_algorithm.py", line 371, in learn
    self.train(batch_size=self.batch_size, gradient_steps=gradient_steps)
  File "/home/cw_data_venv/lib/python3.7/site-packages/stable_baselines3/sac/sac.py", line 241, in train
    current_q_values = self.critic(replay_data.observations, replay_data.actions)
  File "/cvmfs/ai.mila.quebec/apps/x86_64/debian/pytorch/python3.7-cuda11.1-cudnn8.0-v1.8.1/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/cw_data_venv/lib/python3.7/site-packages/stable_baselines3/common/policies.py", line 884, in forward
    return tuple(q_net(qvalue_input) for q_net in self.q_networks)
  File "/home/cw_data_venv/lib/python3.7/site-packages/stable_baselines3/common/policies.py", line 884, in <genexpr>
    return tuple(q_net(qvalue_input) for q_net in self.q_networks)
  File "/cvmfs/ai.mila.quebec/apps/x86_64/debian/pytorch/python3.7-cuda11.1-cudnn8.0-v1.8.1/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/cvmfs/ai.mila.quebec/apps/x86_64/debian/pytorch/python3.7-cuda11.1-cudnn8.0-v1.8.1/lib/python3.7/site-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "/cvmfs/ai.mila.quebec/apps/x86_64/debian/pytorch/python3.7-cuda11.1-cudnn8.0-v1.8.1/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/cvmfs/ai.mila.quebec/apps/x86_64/debian/pytorch/python3.7-cuda11.1-cudnn8.0-v1.8.1/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 94, in forward
    return F.linear(input, self.weight, self.bias)
  File "/cvmfs/ai.mila.quebec/apps/x86_64/debian/pytorch/python3.7-cuda11.1-cudnn8.0-v1.8.1/lib/python3.7/site-packages/torch/nn/functional.py", line 1753, in linear
    return torch._C._nn.linear(input, weight, bias)
RuntimeError: expected scalar type Float but found Double


```

### System Info

Describe the characteristic of your environment:
- all libraries installed with pip in a virtual environment (cw_data_venv)
- OS: Linux-4.15.0-65-generic-x86_64-with-debian-buster-sid 
- Python: 3.7.6
- Stable-Baselines3: 1.3.0
- PyTorch: 1.8.1+cu111
- GPU Enabled: False
- Numpy: 1.21.4
- Gym: 0.19.0

### Additional context

The error persists on a gpu machine

It seems error is originating from the SAC policy when the `current_q_values` are calculated with a forward pass through the critic.
It could potentially be solved by specifying `dtype` in the [to_torch function in replay buffer](https://github.com/DLR-RM/stable-baselines3/blob/b37052cbf059b6f81314f5b98205e4a3403e4112/stable_baselines3/common/buffers.py#L123)

### Checklist

- [x] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)
- [x] I have checked my env using the env checker (**required**)
- [x] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by Miffyli** [comment] 2021-11-24 17:42
Hey! Indeed sounds like a bug, and we would be happy to accept a PR that fixes this. The `RolloutBuffer` used by PPO already fixes the dtype to float32 (hence it works), but `ReplayBuffer` uses the [dtype of the observation](https://github.com/DLR-RM/stable-baselines3/blob/master/stable_baselines3/common/buffers.py#L507). 

This should be fixed by checking that if observation space dtype if a floating point number, it should be stored as float32. Other dtypes should be kept as is (e.g. image observations with dtype uint8 should be kept as uint8).

**Comment by nikhilbarhate99** [comment] 2021-11-25 06:46
Since the `critic` takes in observations and actions, we will need to handle both in the `ReplayBuffer` and `DictReplayBuffer` classes.

I am thinking to replace [the following in the ReplayBuffer](https://github.com/DLR-RM/stable-baselines3/blob/master/stable_baselines3/common/buffers.py#L192-L200) class:
```python
self.observations = np.zeros((self.buffer_size, self.n_envs) + self.obs_shape, dtype=observation_space.dtype)

if optimize_memory_usage:
    # `observations` contains also the next observation
    self.next_observations = None
else:
    self.next_observations = np.zeros((self.buffer_size, self.n_envs) + self.obs_shape, dtype=observation_space.dtype)

self.actions = np.zeros((self.buffer_size, self.n_envs, self.action_dim), dtype=action_space.dtype)
```
with:

```python
# fix the dtype of floating point observations and actions to float32 
# which is the required precision for `forward` function call on current versions of PyTorch

obs_dtype = observation_space.dtype
if obs_dtype is np.float64 or obs_dtype is np.float16:
   obs_dtype = np.float32

action_dtype = action_space.dtype
if action_dtype is np.float64 or action_dtype is np.float16:
   action_dtype = np.float32

self.observations = np.zeros((self.buffer_size, self.n_envs) + self.obs_shape, dtype=obs_dtype)

if optimize_memory_usage:
    # `observations` contains also the next observation
    self.next_observations = None
  else:
    self.next_observations = np.zeros((self.buffer_size, self.n_envs) + self.obs_shape, dtype=obs_dtype)

self.actions = np.zeros((self.buffer_size, self.n_envs, self.action_dim), dtype=action_dtype)
```

And do the same for `DictReplayBuffer` class

**Comment by Miffyli** [comment] 2021-11-25 09:28
After further discussion with @araffin, it might be better to delegate this issue to the users by including a specific check in `env_checker` where it checks that all float types are `float32`. Reasoning for this is that transforming float64 -> float32 would have to be done all around the code which gets pretty messy.

**Comment by nikhilbarhate99** [comment] 2021-11-25 10:03
Okay
In that case, include the fp32 precision specification in the documentation for `custom_gym_env`

**Comment by araffin** [comment] 2021-12-06 14:23
btw, I think the issue is not the observation space (preprocessing cast it to float32) but the action space (I pushed an update in #686 ).

**Closed** 2021-12-09 12:14 UTC
Labels: bug, question, custom gym env
