### ISSUE TITLE
[Question] Graph optimization tasks 

### ISSUE THREAD

**Issue by aabbas90** [DLR-RM/stable-baselines3#1312] opened 2023-02-03 16:38 UTC
### ❓ Question

Hi, I need to solve graph optimization problems using RL. The action space is continuous and size of action space is equal to number of nodes in the graph. I have the following strategy in mind to achieve this via stable-baselines3:

1. For observation space use [graph](https://www.gymlibrary.dev/api/spaces/#graph) space from gym. 
2. For action space I will define a custom torch module which will use GNN inside (using [PyG](https://pytorch-geometric.readthedocs.io/en/latest/)). 
3. I want one agent to learn on multiple graphs (so batch size `B` > 1) and each graph can have variable number of nodes |V|. This causes following issues: 
a. How to implement the 'extra linear layer' as mentioned in [custom policy](https://stable-baselines3.readthedocs.io/en/master/guide/custom_policy.html) myself? This is because I need to use [scatter_sum](https://pytorch-scatter.readthedocs.io/en/latest/functions/scatter.html) to compute value function for each graph separately. Similarly for sampling action the `Linear` layer needs to act separately on rows of a tensor of size `|B|.|V| x d ` to produce `|B|.|V| x 1 ` output. Where `d ` is the size of feature embedding from action network. 
b. On reading a new graph from disk I need to recreate/change the environment but train the same agent. Some example in this direction would be good. 

Thanks a lot for your help. A related [issue](https://github.com/DLR-RM/stable-baselines3/issues/1280).
Ahmed

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment] 2023-02-03 18:41
> A related https://github.com/DLR-RM/stable-baselines3/issues/1280.

yes, looks like a duplicate of it and I would keep the discussion there, to have everything at one place.
I've never used GNN, only read about it, so I unfortunately cannot help much (maybe others can, @BlueBug12?).

**Comment by araffin** [comment] 2023-02-25 14:36
Closing in favor of https://github.com/DLR-RM/stable-baselines3/issues/1280.

**Closed by araffin** 2023-02-25 14:36 UTC
Labels: enhancement, question
