### ISSUE TITLE
.predict vs evaluate policy? 

### ISSUE THREAD

**Issue by hugistaken** [DLR-RM/stable-baselines3#851] opened 2022-04-07 04:39 UTC
Hey, I'm getting really different results using .predict and evaluate policy for the same environment. I checked some other posts, but I could only find that I should set deterministic to true which I have.  Am I misunderstanding what evaluate does, or is this specific to my situation, in which case I can share the code I have.  Thanks.

**Comment by araffin** [comment] 2022-04-07 05:38
Hello,
please tell us what is your current interpretation of both, and please read the doc about those two first.

**Comment by hugistaken** [comment] 2022-04-07 06:15
Well I looked at the source code for the evaluate method and it seems to loop through the observations and keep a running total of the reward. It basically matches my while true loop where I check every observation and use the model to predict the highest probability outcome and make the appropriate action.

**Comment by araffin** [comment] 2022-04-07 06:27
i assume you are using a custom environment?
if so, please fill in the custom env issue template, otherwise, please provide a minimal example to reproduce the issue.

**Comment by araffin** [comment] 2022-04-07 06:32
if you want detailed explanation, i recode the evaluate policy at 2:09:06 in https://youtu.be/Ikngt0_DXJg ;) (and check that it matches sb3 built in helper)

**Comment by hugistaken** [comment] 2022-04-07 06:48
I believe it has to do with a random seed for a stochastic environment. I set a fixed seed and the results are a lot closer but should I expect them to be completely equal? for my environment when I run eval on multiple episodes i get the same results each time so I was expecting that would happen for predict loop as well. I'll check out the video as well thank you :)

**Comment by hugistaken** [comment] 2022-04-08 04:07
Ok so I was incorrect about the random seed, my environment is unaffected by randomness and will move in the same sequence each time, the random seed did not help. Instead, I've realized that the difference is in the way I get observations. My model is recurrent, but in the code for evaluate policy, if model.policy.recurrent is true, the observation is randomly chosen. shouldn't it return the next observation?

**Comment by Miffyli** [comment] 2022-04-08 09:28
> It basically matches my while true loop where I check every observation and use the model to predict the highest probability outcome and make the appropriate action.

Depending on the algorithm you use, by default it uses stochastic sampling (i.e. does not take the action with the highest probability), so this might affect results. See `deterministic` flag in `predict´.

**Comment by hugistaken** [comment] 2022-04-08 13:43
Yep i did make sure to set deterministic to true, i think i realized the difference is in the way we get observations and ill try to rewrite the eval function to see how observations are updated for recurrent models.

**Comment by hugistaken** [comment] 2022-04-09 03:45
Can you please clarify what the state parameter means for predict

**Comment by hugistaken** [comment] 2022-04-09 04:37
Hey, so I realized the difference was the state parameter. In my predict i dont pass a state, can you help me understand what the state affects, and why it's different that the observation set I am passing?

**Comment by Miffyli** [comment] 2022-04-09 10:29
The `state` parameter is reserved for recurrent models and is not used in main SB3 algorithms (but is used in some of the contrib algorithms, primarily recurrent PPO). So yes, if you are using that recurrent model, then you should pass the state forward.

I am closing this issue as "no tech support". These issues are for bug reports and enhancement proposals. For support in running your codes and debugging like this, we recommend asking elsewhere (e.g. [RL Discord](https://discord.com/invite/xhfNqQv)).

**Closed by Miffyli** 2022-04-09 10:29 UTC
Labels: question, more information needed

**Comment by araffin** [comment] 2022-04-09 11:36
>  i dont pass a state, can you help me understand what the state affects, and why it's different that the observation set I am passing?
> The state parameter is reserved for recurrent models and is not used in main SB3 algorithms 

To complete Anssi's reply, state here refers to states of the LSTM (cell state and hidden state) and should not be confused with the observation (that's one of the reason we call it that way), which is the state of an MDP.
It is crucial to pass the hidden states to the LSTM, otherwise you are not using its recurrent/memory part.
