### ISSUE TITLE
[Bug] 'numpy.random._generator.Generator' object has no attribute 'randint' while using Noop in AtariWrapper for DQN agent

### ISSUE THREAD

**Issue by g27182818** [DLR-RM/stable-baselines3#930] opened 2022-06-11 19:19 UTC
### 🐛 Bug

`model.learn()` fails with DQN agent when freeway environment is wrapped by `AtariWrapper()` with `noop_max=500`

### To Reproduce

Here is the minimal code to reproduce the problem:

```python
from stable_baselines3.common.atari_wrappers import AtariWrapper
from stable_baselines3 import DQN
import gym

env = AtariWrapper(gym.make('FreewayNoFrameskip-v4'), noop_max=500)

model = DQN("CnnPolicy",  env, batch_size=16,  verbose=1, optimize_memory_usage=True)
model.learn(total_timesteps=1, log_interval=10)
```

Which gives the following error:

```bash
A.L.E: Arcade Learning Environment (version 0.7.5+db37282)
[Powered by Stella]
Using cuda device
Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.
Wrapping the env in a VecTransposeImage.
Traceback (most recent call last):
  File "/media/disk1/user_home1/gmmejia/Reinforcement_HW/T6/freway.py", line 8, in <module>
    model.learn(total_timesteps=1, log_interval=10)
  File "/home/gmmejia/anaconda3/envs/hw_6/lib/python3.10/site-packages/stable_baselines3/dqn/dqn.py", line 258, in learn
    return super(DQN, self).learn(
  File "/home/gmmejia/anaconda3/envs/hw_6/lib/python3.10/site-packages/stable_baselines3/common/off_policy_algorithm.py", line 333, in learn
    total_timesteps, callback = self._setup_learn(
  File "/home/gmmejia/anaconda3/envs/hw_6/lib/python3.10/site-packages/stable_baselines3/common/off_policy_algorithm.py", line 309, in _setup_learn
    return super()._setup_learn(
  File "/home/gmmejia/anaconda3/envs/hw_6/lib/python3.10/site-packages/stable_baselines3/common/base_class.py", line 429, in _setup_learn
    self._last_obs = self.env.reset()  # pytype: disable=annotation-type-mismatch
  File "/home/gmmejia/anaconda3/envs/hw_6/lib/python3.10/site-packages/stable_baselines3/common/vec_env/vec_transpose.py", line 110, in reset
    return self.transpose_observations(self.venv.reset())
  File "/home/gmmejia/anaconda3/envs/hw_6/lib/python3.10/site-packages/stable_baselines3/common/vec_env/dummy_vec_env.py", line 61, in reset
    obs = self.envs[env_idx].reset()
  File "/home/gmmejia/anaconda3/envs/hw_6/lib/python3.10/site-packages/stable_baselines3/common/monitor.py", line 79, in reset
    return self.env.reset(**kwargs)
  File "/home/gmmejia/anaconda3/envs/hw_6/lib/python3.10/site-packages/gym/core.py", line 292, in reset
    return self.env.reset(**kwargs)
  File "/home/gmmejia/anaconda3/envs/hw_6/lib/python3.10/site-packages/gym/core.py", line 333, in reset
    return self.env.reset(**kwargs)
  File "/home/gmmejia/anaconda3/envs/hw_6/lib/python3.10/site-packages/gym/core.py", line 319, in reset
    observation = self.env.reset(**kwargs)
  File "/home/gmmejia/anaconda3/envs/hw_6/lib/python3.10/site-packages/stable_baselines3/common/atari_wrappers.py", line 106, in reset
    obs = self.env.reset(**kwargs)
  File "/home/gmmejia/anaconda3/envs/hw_6/lib/python3.10/site-packages/stable_baselines3/common/atari_wrappers.py", line 154, in reset
    return self.env.reset(**kwargs)
  File "/home/gmmejia/anaconda3/envs/hw_6/lib/python3.10/site-packages/stable_baselines3/common/atari_wrappers.py", line 36, in reset
    noops = self.unwrapped.np_random.randint(1, self.noop_max + 1)
AttributeError: 'numpy.random._generator.Generator' object has no attribute 'randint'
```

### Expected behavior

To correctly train the model.

### Installation

I'm installing `Stable-Baselines-3`  as recomended by the documentation. In conda:

```
conda create --name problem_env
conda activate problem_env
conda install python
pip install stable-baselines3[extra]
```

### Describe the characteristic of your environment:
Running `sb3.get_system_info()` gives:
```bash
OS: Linux-5.4.0-113-generic-x86_64-with-glibc2.31 #127-Ubuntu SMP Wed May 18 14:30:56 UTC 2022
Python: 3.10.4
Stable-Baselines3: 1.5.0
PyTorch: 1.11.0+cu102
GPU Enabled: True
Numpy: 1.22.4
Gym: 0.21.0
```

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)
- [x] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [x] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by Miffyli** [comment] 2022-06-11 19:34
Hey! Thanks for reporting this. I do not have a machine to try this right now, but I assume this bug also happens even if you do not pass `noop_max` argument to the wrapper? Looks like the `randint` method was renamed or replaced by `integers` for generators.

**Comment by g27182818** [comment] 2022-06-11 19:36
Yes, I've just tried it and it also happens with:

```python
env = AtariWrapper(gym.make('FreewayNoFrameskip-v4'))
```

**Comment by Miffyli** [comment] 2022-06-11 19:38
@araffin Any guesses why this does not happen in tests? Is the numpy version fixed or maybe gym version changes introduces some changes? In any case, I am not 100% how to properly address this: the long way would be to make a new, seeded generator in the wrapper and use that.

**Comment by araffin** [comment] 2022-06-11 21:50
Duplicate of https://github.com/DLR-RM/stable-baselines3/issues/875

**Closed by araffin** 2022-06-11 21:50 UTC
Labels: bug, duplicate
