### ISSUE TITLE
Box action space values

### ISSUE THREAD

**Issue by anilkurkcu** [DLR-RM/stable-baselines3#1450] opened 2023-04-14 06:35 UTC
### ❓ Question

Hi, I am trying out an action space with Low = -0.01 and High = +0.01

I want my agent to learn to output actions ~0.0

But during training I observe that it usually samples actions of magnitude 0.01, not sampling out much of actions of magnitude 0.0

Is there a way I could achieve this?

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment] 2023-04-14 06:42
> I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)

https://stable-baselines3.readthedocs.io/en/master/guide/rl_tips.html#tips-and-tricks-when-creating-a-custom-environment

Duplicate of https://github.com/hill-a/stable-baselines/issues/473 and 
https://github.com/DLR-RM/stable-baselines3/issues/1293

**Closed by araffin** 2023-04-14 06:42 UTC
Labels: duplicate, question, custom gym env, RTFM
