### ISSUE TITLE
[Question] AttributeError: 'numpy.random._generator.Generator' object has no attribute 'randint'

### ISSUE THREAD

**Issue by Shivam310** [DLR-RM/stable-baselines3#977] opened 2022-07-22 17:47 UTC
So I was working on my atari breakout project and whenever I do evaluate policy I get this error:
```
AttributeError                            Traceback (most recent call last)
Input In [21], in <cell line: 1>()
----> 1 evaluate_policy(model, env, n_eval_episodes=10)

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\stable_baselines3\common\evaluation.py:82, in evaluate_policy(model, env, n_eval_episodes, deterministic, render, callback, reward_threshold, return_episode_rewards, warn)
     80 current_rewards = np.zeros(n_envs)
     81 current_lengths = np.zeros(n_envs, dtype="int")
---> 82 observations = env.reset()
     83 states = None
     84 episode_starts = np.ones((env.num_envs,), dtype=bool)

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\stable_baselines3\common\vec_env\vec_frame_stack.py:58, in VecFrameStack.reset(self)
     54 def reset(self) -> Union[np.ndarray, Dict[str, np.ndarray]]:
     55     """
     56     Reset all environments
     57     """
---> 58     observation = self.venv.reset()  # pytype:disable=annotation-type-mismatch
     60     observation = self.stackedobs.reset(observation)
     61     return observation

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\stable_baselines3\common\vec_env\dummy_vec_env.py:61, in DummyVecEnv.reset(self)
     59 def reset(self) -> VecEnvObs:
     60     for env_idx in range(self.num_envs):
---> 61         obs = self.envs[env_idx].reset()
     62         self._save_obs(env_idx, obs)
     63     return self._obs_from_buf()

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\gym\core.py:292, in Wrapper.reset(self, **kwargs)
    291 def reset(self, **kwargs):
--> 292     return self.env.reset(**kwargs)

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\gym\core.py:333, in RewardWrapper.reset(self, **kwargs)
    332 def reset(self, **kwargs):
--> 333     return self.env.reset(**kwargs)

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\gym\core.py:319, in ObservationWrapper.reset(self, **kwargs)
    318 def reset(self, **kwargs):
--> 319     observation = self.env.reset(**kwargs)
    320     return self.observation(observation)

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\stable_baselines3\common\atari_wrappers.py:59, in FireResetEnv.reset(self, **kwargs)
     58 def reset(self, **kwargs) -> np.ndarray:
---> 59     self.env.reset(**kwargs)
     60     obs, _, done, _ = self.env.step(1)
     61     if done:

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\stable_baselines3\common\atari_wrappers.py:106, in EpisodicLifeEnv.reset(self, **kwargs)
     97 """
     98 Calls the Gym environment reset, only when lives are exhausted.
     99 This way all states are still reachable even though lives are episodic,
   (...)
    103 :return: the first observation of the environment
    104 """
    105 if self.was_real_done:
--> 106     obs = self.env.reset(**kwargs)
    107 else:
    108     # no-op step to advance from terminal/lost life state
    109     obs, _, _, _ = self.env.step(0)

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\stable_baselines3\common\atari_wrappers.py:154, in MaxAndSkipEnv.reset(self, **kwargs)
    153 def reset(self, **kwargs) -> GymObs:
--> 154     return self.env.reset(**kwargs)

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\stable_baselines3\common\atari_wrappers.py:36, in NoopResetEnv.reset(self, **kwargs)
     34     noops = self.override_num_noops
     35 else:
---> 36     noops = self.unwrapped.np_random.randint(1, self.noop_max + 1)
     37 assert noops > 0
     38 obs = np.zeros(0)

AttributeError: 'numpy.random._generator.Generator' object has no attribute 'randint'
```

---------------------------------------------------------------------------------------------------------------------------------------------------
Here is my code:
```
import gym
from stable_baselines3 import A2C
from stable_baselines3.common.vec_env import VecFrameStack
from stable_baselines3.common.evaluation import evaluate_policy
from stable_baselines3.common.env_util import make_atari_env
from stable_baselines3.common.env_util import make_vec_env

import os
from gym.utils import play
from stable_baselines3.ddpg.policies import CnnPolicy

from ale_py import ALEInterface
from ale_py.roms import Breakout

ale = ALEInterface()


ale.loadROM(Breakout)
environment_name = env = gym.make('ALE/Breakout-v5', render_mode='human')
env = make_atari_env('Breakout-v0', n_envs=4, seed=0)
env = VecFrameStack(env, n_stack=4)
log_path = os.path.join('Training', 'Logs')
model = A2C('CnnPolicy', environment_name, verbose=1, tensorboard_log=log_path)
a2c_path = os.path.join('Training','Logs', 'A2C_300k_model')
model.save(a2c_path)
del model
model = A2C.load(a2c_path, env)
evaluate_policy(model, env, n_eval_episodes=10)
```
---------------------------------------------------------------------------------------------------------------------------------------------------
Please help.
Thanks.

**Comment by qgallouedec** [comment] 2022-07-22 17:51
Next time, please fill in the issue template. This way you could realize that this question has already been asked and duplicated: #875

**Comment by araffin** [comment] 2022-07-22 18:27
Closing as duplicate of https://github.com/DLR-RM/stable-baselines3/issues/875 and this should not happened if you installed SB3 with pip (using `[extra]` package), as the correct ale-py version is pinned.

**Closed by araffin** 2022-07-22 18:27 UTC
Labels: duplicate, question

**Comment by Shivam310** [comment] 2022-07-23 17:21
> Closing as duplicate of #875 and this should not happened if you installed SB3 with pip (using `[extra]` package), as the correct ale-py version is pinned.

Hi there,
I actually tried both of the pip installs but now I get this error:
```
ValueError                                Traceback (most recent call last)
Input In [7], in <cell line: 1>()
----> 1 model = A2C.load(a2c_path, env)

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\stable_baselines3\common\base_class.py:726, in BaseAlgorithm.load(cls, path, env, device, custom_objects, print_system_info, force_reset, **kwargs)
    724 env = cls._wrap_env(env, data["verbose"])
    725 # Check if given env is valid
--> 726 check_for_correct_spaces(env, data["observation_space"], data["action_space"])
    727 # Discard `_last_obs`, this will force the env to reset before training
    728 # See issue https://github.com/DLR-RM/stable-baselines3/issues/597
    729 if force_reset and data is not None:

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\stable_baselines3\common\utils.py:226, in check_for_correct_spaces(env, observation_space, action_space)
    214 """
    215 Checks that the environment has same spaces as provided ones. Used by BaseAlgorithm to check if
    216 spaces match after loading the model with given env.
   (...)
    223 :param action_space: Action space to check against
    224 """
    225 if observation_space != env.observation_space:
--> 226     raise ValueError(f"Observation spaces do not match: {observation_space} != {env.observation_space}")
    227 if action_space != env.action_space:
    228     raise ValueError(f"Action spaces do not match: {action_space} != {env.action_space}")

ValueError: Observation spaces do not match: Box([[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]], [[[255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  ...
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]]

 [[255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  ...
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]]

 [[255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  ...
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]]], (3, 210, 160), uint8) != Box([[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]], [[[255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  ...
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]]

 [[255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  ...
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]]

 [[255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  ...
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]]

 [[255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  ...
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]]], (4, 84, 84), uint8)
```
Please help.
Thanks

**Comment by Shivam310** [comment] 2022-07-23 17:22
> Next time, please fill in the issue template. This way you would have realized that this question has already been asked and duplicated: #875

Sorry, I wasn't aware of this. I will make sure to do it next time.
Thanks.

**Comment by qgallouedec** [comment] 2022-07-23 17:41
Please open a new issue, as it is not related to your original topic.
