### ISSUE TITLE
(SB3,DDPG): TypeError: reset() got an unexpected keyword argument 'seed'

### ISSUE THREAD

**Issue by acq3047** [DLR-RM/stable-baselines3#1612] opened 2023-07-17 18:39 UTC
### 🐛 Bug

Greetings, I am reaching out to inquire if there is anyone who can provide assistance in resolving an error that I have encountered while using DDPG with SB3. Specifically, upon running the code, I am prompted with an expected argument at the time of reset, which is necessary for the algorithm's functionality. I would greatly appreciate any guidance or assistance that can be offered. Thank you for your time and consideration.

### Code example

```python
import gymnasium as gym
import numpy as np
import time
from typing import Optional
from reinforcement_learning.airgym.envs.car_env import AirSimCarEnv
from stable_baselines3 import DQN, DDPG
from stable_baselines3.common.env_checker import check_env
from stable_baselines3.common.monitor import Monitor
from stable_baselines3.common.vec_env import DummyVecEnv, VecTransposeImage
from stable_baselines3.common.evaluation import evaluate_policy
from stable_baselines3.common.noise import NormalActionNoise,OrnsteinUhlenbeckActionNoise
from stable_baselines3.common.callbacks import EvalCallback

# create the environment
env=gym.make("airgym:airsim-car-sample-v0", ip_address="127.0.0.1", image_shape=(84, 84, 1))
print(dir(env))
#n_actions = env.action_space.shape[-1]
# Initialize RL algorithm type and parameters
# NormalActionNoise(mean=np.zeros(n_actions), sigma=0.1 * np.ones(n_actions))
model = DDPG(
    "MlpPolicy",
    env,
    learning_rate=0.00025,
    verbose=1,
    batch_size=32,
    train_freq=(1, 'episode'),
    gamma=0.99,  # Discount factor
    learning_starts=200000,
    buffer_size=5000,
    tau=0.005,  # soft update coefficient
    gradient_steps=-1,
    optimize_memory_usage=False,
    seed=None,
    action_noise=None,
    replay_buffer_class=None,
    replay_buffer_kwargs=None,
    device="auto",
    tensorboard_log="./tb_logs/",
    _init_setup_model=True,
)

# Create an evaluation callback with the same env, called every 10000 iterations
callbacks = []
eval_callback = EvalCallback(
    env,
    callback_on_new_best=None,
    n_eval_episodes=5,
    best_model_save_path=".",
    log_path=".",
    eval_freq=10000,
)
callbacks.append(eval_callback)
kwargs = {}
kwargs["callback"] = callbacks
# Train for a certain number of timesteps
model.learn(
    total_timesteps=20000, log_interval=4, tb_log_name="ddpg_airsim_car_run_" + str(time.time()), callback=callbacks, reset_num_timesteps=True, progress_bar=False)
# Save policy weights
model.save("ddpg_airsim_car_policy")
vec_env = model.get_env()
del model # remove to demonstrate saving and loading

model = DDPG.load("ddpg_airsim_car_policy")
obs, info = vec_env.reset()
while True:
    action = model.predict(obs, deterministic=True)
    obs, reward, terminated, truncated, info = vec_env.step(action)
    # obs, reward, terminated, truncated, info = env.step(action)
    env.render()
    done= terminated or truncated
    if terminated or truncated:
       obs, info = env.reset(seed=0, options={})


```

### Relevant log output / Error message

```shell
TypeError: reset() got an unexpected keyword argument 'seed'
```

### System Info

I am using:

- Python 3.9
- Gymnasium 0.29.0
- Open AI Gym 0.26.2
- PyTorch 2.0.1

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have provided a [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014) example to reproduce the bug
- [X] I have checked my env using the env checker
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment] 2023-07-18 11:15
Duplicate of https://github.com/DLR-RM/stable-baselines3/issues/1609, please read carefully the checklist.

**Closed by araffin** 2023-07-18 11:15 UTC
Labels: custom gym env

**Comment by RibhavOjha** [comment] 2023-08-22 20:33
Hi
I dont understand how is this issue a duplicate of #1609 . This issue talks about "TypeError: reset() got an unexpected keyword argument 'seed' " and the issue you have quoted talks about "AssertionError: The algorithm only supports (<class 'gymnasium.spaces.box.Box'>,) as action spaces but Discrete(6) was provided
"
Thanks

**Comment by araffin** [comment] 2023-08-23 06:39
See https://github.com/DLR-RM/stable-baselines3/issues/1609#issuecomment-1638201454 and https://github.com/DLR-RM/stable-baselines3/issues/1609#issuecomment-1643814703
