### ISSUE TITLE
Is data normalization required by stable baselines?

### ISSUE THREAD

**Issue by evo11x** [DLR-RM/stable-baselines3#563] opened 2021-09-10 16:13 UTC
For custom environments do I need to normalize the observation array? Or it is done by stable-baselines internaly ?

This is the learning code

```
    env = MyEnv(config)
    policy_kwargs = dict(activation_fn=th.nn.ReLu, net_arch=[dict(pi=[32, 32], vf=[32, 32])])
                     
    model = PPO(
        "MlpPolicy", env,
        learning_rate=1e-4,
        policy_kwargs=policy_kwargs,
        verbose=1,
        tensorboard_log="./tensorboard/")

    model.learn(total_timesteps=int(3e+6))
    model.save('model')
```

**Comment by Miffyli** [comment] 2021-09-10 17:39
Answer is in docs, see [here](https://stable-baselines3.readthedocs.io/en/master/guide/examples.html#pybullet-normalizing-input-features).

**Comment by evo11x** [comment] 2021-09-10 21:12
After I have added VecNormalize to the environment I get this error, without VecNormalize the code runs fine, but the training is not good at all...

`Using cuda device
Logging to ./tensorboard/PPO_4
Traceback (most recent call last):
  File "deep_rl.py", line 33, in <module>
    model.learn(total_timesteps=int(1e+6))
  File ".env\lib\site-packages\stable_baselines3\ppo\ppo.py", line 301, in learn
    return super(PPO, self).learn(
  File ".env\lib\site-packages\stable_baselines3\common\on_policy_algorithm.py", line 237, in learn   
    continue_training = self.collect_rollouts(self.env, callback, self.rollout_buffer, n_rollout_steps=self.n_steps)
  File ".env\lib\site-packages\stable_baselines3\common\on_policy_algorithm.py", line 169, in collect_rollouts
    actions, values, log_probs = self.policy.forward(obs_tensor)
  File ".env\lib\site-packages\stable_baselines3\common\policies.py", line 586, in forward
    latent_pi, latent_vf, latent_sde = self._get_latent(obs)
    features = self.extract_features(obs)
  File ".env\lib\site-packages\stable_baselines3\common\policies.py", line 128, in extract_features   
    return self.features_extractor(preprocessed_obs)
  File ".env\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File ".env\lib\site-packages\stable_baselines3\common\torch_layers.py", line 48, in forward
    return self.flatten(observations)
  File ".env\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File ".env\lib\site-packages\torch\nn\modules\flatten.py", line 40, in forward
    return input.flatten(self.start_dim, self.end_dim)
IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)`

I use Python 3.9, Windows 10 64-bit, the latest pytorch and stable-baselines3

**Comment by Miffyli** [comment] 2021-09-10 21:14
I recommend that you check your environment with env checker (see docs), and start by modifying the examples provided there to ensure code is correct.

Closing as no tech support.

**Closed by Miffyli** 2021-09-10 21:14 UTC
Labels: question, custom gym env, No tech support, RTFM

**Comment by araffin** [comment] 2021-09-16 10:48
And duplicate of https://github.com/DLR-RM/stable-baselines3/issues/455
