### ISSUE TITLE
the same learning rate will be used for all networks (Q-Values, Actor and Value function)

### ISSUE THREAD

**Issue by lordemyj** [DLR-RM/stable-baselines3#1740] opened 2023-11-08 08:25 UTC
### ❓ Question

How do I set different learning rates?

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014)
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment] 2023-11-08 09:49
Hello,
for now, you would need a fork of SB3, see https://github.com/DLR-RM/stable-baselines3/issues/338

**Comment by araffin** [comment] 2023-12-04 16:56
> and especially https://github.com/DLR-RM/stable-baselines3/issues/338#issuecomment-791392974

closing as duplicate of it

**Closed by araffin** 2023-12-04 16:56 UTC
Labels: question
