### ISSUE TITLE
[Question] LSTM and GRU

### ISSUE THREAD

**Issue by evo11x** [DLR-RM/stable-baselines3#554] opened 2021-08-30 14:45 UTC
How can I change the layers to LSTM or GRU using stable baselines 3 with pytorch ? I can't find this in the documentation.

**Comment by Miffyli** [comment] 2021-08-30 18:30
Closing as duplicate of #160 

The answer is: there is not support for RNNs yet (and it is not as easy as simply adding them to the feature extractor)

**Closed by Miffyli** 2021-08-30 18:30 UTC
Labels: duplicate, question
