### ISSUE TITLE
getting MlpLstmPolicy working with PPO DQN or A2C??

### ISSUE THREAD

**Issue by chrisantha** [DLR-RM/stable-baselines3#319] opened 2021-02-17 22:05 UTC
I'm not sure how to get the LSTM policy working with the above algorithms. It says 

    model = PPO('MlpLstmPolicy', env, verbose=1).learn(5000)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/stable_baselines3/ppo/ppo.py", line 110, in __init__
    _init_setup_model=False,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/stable_baselines3/common/on_policy_algorithm.py", line 87, in __init__
    tensorboard_log=tensorboard_log,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/stable_baselines3/common/base_class.py", line 106, in __init__
    self.policy_class = get_policy_from_name(policy_base, policy)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/stable_baselines3/common/policies.py", line 815, in get_policy_from_name
    f"Error: unknown policy type {name},"
KeyError: "Error: unknown policy type MlpLstmPolicy,the only registed policy type are: ['MlpPolicy', 'CnnPolicy']!"

**Comment by Miffyli** [comment] 2021-02-17 22:16
There is no support for LSTM/RNN policies in stable-baselines3 yet. You need to use [stable-baselines](https://github.com/hill-a/stable-baselines/) for those.

Closing as duplicate of #18.

**Closed by Miffyli** 2021-02-17 22:16 UTC
Labels: RTFM
