### ISSUE TITLE
[Question] Is there a way to parallelise PPO so that it can run on GPU?  

### ISSUE THREAD

**Issue by Dylan-Kerler** [DLR-RM/stable-baselines3#374] opened 2021-03-30 11:15 UTC
### Question

The main bottleneck of PPO is the env simulation; A gradient update cannot be done until enough "experience" is collected. Is it possible to run the env simulation in parallel and then asynchronously do gradient updates?

**Comment by araffin** [comment] 2021-03-30 11:28
Probably a duplicate of https://github.com/DLR-RM/stable-baselines3/issues/314
You may also take a look at MPI, and would accept a PR in contrib repo, see https://github.com/Stable-Baselines-Team/stable-baselines3-contrib/issues/11

**Comment by Dylan-Kerler** [comment] 2021-03-31 22:43
I had never even heard of MPI before you mentioned it (i looked into it and it's super cool).

**Closed** 2021-04-15 12:53 UTC
Labels: duplicate, question
