### ISSUE TITLE
[Bug]: Evaluation and Training Inconsistent Performance 

### ISSUE THREAD

**Issue by Jackflyingzzz** [DLR-RM/stable-baselines3#1178] opened 2022-11-17 17:10 UTC
### 🐛 Bug

Hi! I'm using SAC/TQC in my custom environment. When I evaluated the saved agents by CheckpointCallback, it seems like the rewards obtained in evaluation for the later agents are far less than that in training. The optimum point(similar performance as training) is located at the nearly convergence region, and become unsatisfactory from there. While the rewards in training are constantly at maximum.
<img width="365" alt="Screenshot 2022-11-17 at 16 40 26" src="https://user-images.githubusercontent.com/105610300/202505881-1bb3bbbf-c57b-43bb-97b0-f67e78d289a3.png">

Here are some parameters during the training.
<img width="1784" alt="Screenshot 2022-11-17 at 17 02 49" src="https://user-images.githubusercontent.com/105610300/202510591-06426d7d-afe5-4cd7-ba4c-b9d18a5e7dd4.png">

This is the comparison of the action at each stage of saved agents, where the agents saved from later does not converge to an optimal action.
<img width="1359" alt="Screenshot 2022-11-17 at 17 06 46" src="https://user-images.githubusercontent.com/105610300/202511254-fd8e38dd-a8d9-4e71-898a-96e6bcc2bada.png">
I'm not sure if this is a bug or I messed up some parameters in training, I truly appreciate any help or advice, Thanks!

### To Reproduce

```python
from stable_baselines3 import ...

```

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have provided a minimal working example to reproduce the bug
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment] 2022-11-18 09:32
Probably a duplicate of https://github.com/DLR-RM/stable-baselines3/issues/1063 (and the std reward is also important)
Also related to https://github.com/DLR-RM/stable-baselines3/issues/879 https://github.com/DLR-RM/stable-baselines3/issues/851#issuecomment-1091130586

**Comment by Jackflyingzzz** [comment] 2022-11-19 23:16
I'm not sure if this is relevant to my problem, but the first graph is my first training, the second graph is the restarted training from the latest agent, the rewards does not continue from the previous highest one. Is that because of some default extra exploration at the first episode?  Thanks!  @araffin 
<img width="965" alt="Screenshot 2022-11-19 at 23 08 07" src="https://user-images.githubusercontent.com/105610300/202875126-b63b4e90-f574-49c3-b5b7-af09d00b92a9.png">
<img width="912" alt="Screenshot 2022-11-19 at 23 07 49" src="https://user-images.githubusercontent.com/105610300/202875183-fe4dcac5-1ac1-42ab-94b0-c49bacd3361c.png">

**Comment by araffin** [comment] 2022-11-19 23:37
Please fill the issue template completely, but I'm afraid your problem falls into "tech support/consulting" which we don't do (cf. README and issue template) .

**Closed** 2022-12-17 11:28 UTC
Labels: bug, custom gym env, more information needed

**Comment by ReHoss** [comment] 2023-01-30 11:57
> I'm not sure if this is relevant to my problem, but the first graph is my first training, the second graph is the restarted training from the latest agent, the rewards does not continue from the previous highest one. Is that because of some default extra exploration at the first episode? Thanks! @araffin <img alt="Screenshot 2022-11-19 at 23 08 07" width="965" src="https://user-images.githubusercontent.com/105610300/202875126-b63b4e90-f574-49c3-b5b7-af09d00b92a9.png"> <img alt="Screenshot 2022-11-19 at 23 07 49" width="912" src="https://user-images.githubusercontent.com/105610300/202875183-fe4dcac5-1ac1-42ab-94b0-c49bacd3361c.png">

@Jackflyingzzz what's the end of the story ?
