### ISSUE TITLE
AssertionError: The algorithm only supports (<class 'gym.spaces.box.Box'>, <class 'gym.spaces.discrete.Discrete'>, <class 'gym.spaces.multi_discrete.MultiDiscrete'>, <class 'gym.spaces.multi_binary.MultiBinary'>) as action spaces but Discrete(2) was provided

### ISSUE THREAD

**Issue by hedaniel7** [DLR-RM/stable-baselines3#1475] opened 2023-04-28 15:41 UTC
Steps to reproduce with Anaconda:

```
conda create --name myenv python=3.7
conda activate myenv
pip install stable-baselines3[extra]

```
Create python-file with tutorial code:
```
import gymnasium as gym

from stable_baselines3 import A2C
from gym import spaces

env = gym.make("CartPole-v1")

model = A2C("MlpPolicy", env, verbose=1)
model.learn(total_timesteps=10_000)

vec_env = model.get_env()
obs = vec_env.reset()
for i in range(1000):
    action, _state = model.predict(obs, deterministic=True)
    obs, reward, done, info = vec_env.step(action)
    vec_env.render()
    # VecEnv resets automatically
    # if done:
    #   obs = vec_env.reset()
```
    
` pip install gymnasium`
   
   run the code and it should reproduce this error:
   
Using cpu device
Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.
Traceback (most recent call last):
  File "SB3tutorial.py", line 8, in <module>
    model = A2C("MlpPolicy", env, verbose=1)
  File "/home/dan/anaconda3/envs/myenv/lib/python3.7/site-packages/stable_baselines3/a2c/a2c.py", line 110, in __init__
    spaces.MultiBinary,
  File "/home/dan/anaconda3/envs/myenv/lib/python3.7/site-packages/stable_baselines3/common/on_policy_algorithm.py", line 91, in __init__
    supported_action_spaces=supported_action_spaces,
  File "/home/dan/anaconda3/envs/myenv/lib/python3.7/site-packages/stable_baselines3/common/base_class.py", line 173, in __init__
    f"The algorithm only supports {supported_action_spaces} as action spaces "
AssertionError: The algorithm only supports (<class 'gym.spaces.box.Box'>, <class 'gym.spaces.discrete.Discrete'>, <class 'gym.spaces.multi_discrete.MultiDiscrete'>, <class 'gym.spaces.multi_binary.MultiBinary'>) as action spaces but Discrete(2) was provided
>

**Comment by araffin** [comment] 2023-04-28 15:45
Duplicate of https://github.com/DLR-RM/stable-baselines3/issues/1371 and https://github.com/DLR-RM/stable-baselines3/issues/1274 and https://github.com/Farama-Foundation/Gymnasium/issues/348

**Please use the issue template next time**

`pip install stable-baselines3[extra] --pre --upgrade` (install SB3 v2.0+) or install master version (see documentation).

**Closed by araffin** 2023-04-28 15:45 UTC
Labels: duplicate
