### ISSUE TITLE
[Question] why are `SAC` and `TD3` default hyperparameters not so similar?

### ISSUE THREAD

**Issue by Kallinteris-Andreas** [DLR-RM/stable-baselines3#1769] opened 2023-12-01 14:57 UTC
### ❓ Question

Some [SAC](https://stable-baselines3.readthedocs.io/en/master/modules/sac.html#parameters)'s and [TD3](https://stable-baselines3.readthedocs.io/en/master/modules/td3.html#parameters)'s default parameter so different 

|Variable Name|SAC|TD3|
|----------------------------|--------------|--------------|
|`learning_rate` | 0.0003 | 0.001|
|`batch_size`| 256 | 100 |
|`train_freq` | 1 | (1, 'episode') |
|`gradient_steps` |  1 | -1 |

To me in particular, `batch_size` stands out as it significantly affects the runtime (scaling roughly linearly) and learning performance. 

Is there a design reason of why they are different?

Thanks!

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014)
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment] 2023-12-01 16:14
Hello,

> Is there a design reason of why they are different?

The answer is quite simple, it comes from the original papers.
But DDPG/TD3 defaults should be changed to SAC defaults as `(1, 'episode')` causes confusion (you can find several issues in the repo) and the original TD3 implementation now uses the same defaults: https://github.com/sfujim/TD3/commit/a8d53f7ad28e22b9cb28189b1ba9fac096587e88

I would appreciate a PR that changes that =) (and also update the RL Zoo)

**Comment by Kallinteris-Andreas** [comment] 2023-12-01 16:20
Should all of them be changed, or just `train_freq`?

what should be updated in RL zoo

**Comment by araffin** [comment] 2023-12-01 16:45
> Should all of them be changed, or just train_freq?

I'm not sure, at least `train_freq` and `gradient_steps`

See https://github.com/DLR-RM/stable-baselines3/issues/1562 (which is a duplicate of current issue)

What do you think @qgallouedec ?

> what should be updated in RL zoo

The same thing: https://github.com/DLR-RM/rl-baselines3-zoo/blob/master/hyperparams/td3.yml

**Closed** 2024-01-12 15:05 UTC
Labels: duplicate, help wanted, question
