### ISSUE TITLE
[Bug]: Very Poor A2C CPU Utilization

### ISSUE THREAD

**Issue by Bonifatius94** [DLR-RM/stable-baselines3#1245] opened 2022-12-27 17:55 UTC
### 🐛 Bug

When using the A2C algorithm with 50 vectorized environments on a Ryzen Threadripper machine with 12 cores / 24 threads, I'm getting this really poor, almost single-core CPU utilization.

![stablebaselines3_a2c_algo_poor_cpu_utilization](https://user-images.githubusercontent.com/29117597/209699619-e00de4dd-8971-4142-97ac-53ee0a85e968.jpg)

I've tested the A2C training algorithm with several Gym environments such as FrozenLake and Pong. Both didn't make better use of the CPU either (except for FrozenLake being very small and yielding a lot more steps/s which doesn't even rise a single core up to 100%).

### To Reproduce

See the README commands on my GitHub repository for the [robot_sf simulator](https://github.com/Bonifatius94/robot-sf). I'm using a dockerized training with NVIDIA GPU support. It shouldn't make a difference when using other Gym environments.

```sh
# clone the git repo
git clone --recurse-submodules https://github.com/Bonifatius94/robot-sf
cd robot-sf

# install docker and docker-compose
sudo apt-get update && sudo apt-get install -y docker.io docker-compose
sudo usermod -aG docker $USER && reboot

# install cURL for sending HTTP requests
sudo apt-get update && sudo apt-get install -y curl

# register the NVIDIA Docker PPA as apt source
distribution=$(. /etc/os-release;echo $ID$VERSION_ID) \
    && curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add - \
    && curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list \
        | sudo tee /etc/apt/sources.list.d/nvidia-docker.list

# install NVIDIA Docker from the official NVIDIA PPA
sudo apt-get update && sudo apt-get install -y nvidia-docker2

# build the docker image and launch the training
docker-compose build && docker-compose run \
    robotsf-cuda python ./scripts/training.py
```

I've also tested with common Gym environments like FrozenLake or Pong. FrozenLake doesn't even rise one CPU core up to 100% and Pong has about the same behavior as my own training environment (one core at 100%, other cores on idle). So, you can use Pong for your investigations if you don't wanna use my custom Gym environment; it should have about the same properties.

```py
import gym
from stable_baselines3 import A2C
from stable_baselines3.common.env_util import make_vec_env

def training():
    env = make_vec_env(lambda: gym.make("FrozenLake-v1"), n_envs=50)
    model = A2C("MlpPolicy", env)
    model.learn(total_timesteps=int(2e6), progress_bar=True)
    model.save("./model/dqn_model")

if __name__ == '__main__':
    training()
```

```py
import gym
from stable_baselines3 import A2C
from stable_baselines3.common.env_util import make_vec_env

def training():
    env = make_vec_env(lambda: gym.make("ALE/Pong-v5"), n_envs=50)
    model = A2C("CnnPolicy", env)
    model.learn(total_timesteps=int(2e6), progress_bar=True)
    model.save("./model/dqn_model")

if __name__ == '__main__':
    training()
```

### Relevant log output / Error message

```shell
There's no hard bug or error message. It's just that the algorithm doesn't scale with CPU cores as expected, see my screenshot.
```

### System Info

See my Dockerfile and requirements.txt. Running your little script inside the Docker environment of my workstation produced following output:

```text
OS: Linux-5.4.0-135-generic-x86_64-with-glibc2.27 #152~18.04.2-Ubuntu SMP Tue Nov 29 08:23:49 UTC 2022
Python: 3.9.12
Stable-Baselines3: 1.6.2
PyTorch: 1.13.0
GPU Enabled: True
Numpy: 1.23.4
Gym: 0.21.0

({'OS': 'Linux-5.4.0-135-generic-x86_64-with-glibc2.27 #152~18.04.2-Ubuntu SMP Tue Nov 29 08:23:49 UTC 2022', 'Python': '3.9.12', 'Stable-Baselines3': '1.6.2', 'PyTorch': '1.13.0', 'GPU Enabled': 'True', 'Numpy': '1.23.4', 'Gym': '0.21.0'}, 'OS: Linux-5.4.0-135-generic-x86_64-with-glibc2.27 #152~18.04.2-Ubuntu SMP Tue Nov 29 08:23:49 UTC 2022\nPython: 3.9.12\nStable-Baselines3: 1.6.2\nPyTorch: 1.13.0\nGPU Enabled: True\nNumpy: 1.23.4\nGym: 0.21.0\n')
```

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have provided a minimal working example to reproduce the bug
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment] 2022-12-28 09:42
Probably a duplicate of https://github.com/DLR-RM/stable-baselines3/issues/350 and https://github.com/DLR-RM/stable-baselines3/issues/682

Also related: https://github.com/DLR-RM/stable-baselines3/issues/314 https://github.com/DLR-RM/stable-baselines3/issues/849 https://github.com/DLR-RM/stable-baselines3/issues/217

As I wrote, "A2C is meant to be run mostly on cpu" (especially true when not using a CNN), in you case two things that will improve CPU usage:
deactivate GPU (`CUDA_VISIBLE_DEVICES=`) and use `SubprocVecEnv` instead of the default dummy vecenv.

**Comment by Bonifatius94** [comment] 2022-12-28 12:03
> Probably a duplicate of #350 and #682
> 
> Also related: #314 #849 #217
> 
> As I wrote, "A2C is meant to be run mostly on cpu" (especially true when not using a CNN), in you case two things that will improve CPU usage: deactivate GPU (`CUDA_VISIBLE_DEVICES=`) and use `SubprocVecEnv` instead of the default dummy vecenv.

Thanks a lot for your reply. I'll try it out 😄

Maybe you can put a typical vectorized environment in your readthedocs.io for A2C 😉

The use case of A2C for many users is scaling slow gym environments with multiple cores. That's basically the reason why the pick A2C in the first place. So why not make it easier to do the right thing and harder to do the wrong thing? 😉

I can help you with an example if you want 😄

**Comment by qgallouedec** [comment] 2022-12-28 13:15
> Maybe you can put a typical vectorized environment in your readthedocs.io for A2C 😉
> I can help you with an example if you want 😄

Since this question comes up a lot, I think it's worth mentioning in the documentation. Can you submit a PR with the clarification you are advocating?

**Comment by araffin** [comment] 2022-12-28 13:18
> Maybe you can put a typical vectorized environment in your readthedocs.io for A2C 

could you elaborate?

anyway, if you want to scale, i would recommend you to use PPO (usually easier to tune and more sammle efficient) or ARS (fast async implementation in SB3 contrib).

**Comment by Bonifatius94** [comment] 2022-12-28 13:23
Ok now the A2C scaling works. All cores have 60% utilization :smile: :smile: :smile:  I had to set *make\_vec\_env(..., vec\_env\_cls=SubprocVecEnv)* for those who read this and want a solution.

And also some fine-tuning insight: Disabling the GPU is not required for parallel performance gains. In fact, it actually slowed my training down by 3x because my envs are GPU empowered with Numba / NumPy. And the more envs, the better the performance, no matter how many physical cores your machine has. So put as many envs as you can afford with RAM.

In my case of robot\_sf, the throughput scaled from 800 to 4800 steps/s (with n\_envs=50 at 18 GB RAM) which is a 6x improvement compared to the DummyVecEnv implementation. With n\_envs=75 took the memory usage went up to 24 GB of RAM and had a throughput of 5200 steps/s, so the gains diminish, but still compared to 800 steps/s it's another 50% improvement.

```py
from stable_baselines3.a2c.a2c import A2C
from stable_baselines3.common.env_util import make_vec_env
from stable_baselines3.common.vec_env.subproc_vec_env import SubprocVecEnv
from robot_sf.robot_env import RobotEnv

def training():
    env = make_vec_env(lambda: RobotEnv(difficulty=2), n_envs=50, vec_env_cls=SubprocVecEnv)
    model = A2C("MlpPolicy", env, tensorboard_log="./logs/a2c_logs/")
    model.learn(total_timesteps=50_000_000, progress_bar=True)
    model.save("./model/a2c_model")

if __name__ == '__main__':
    training()
```

**Comment by Bonifatius94** [comment] 2022-12-28 13:29
> anyway, if you want to scale, i would recommend you to use PPO (usually easier to tune and more sample efficient) or ARS (fast async implementation in SB3 contrib).

Cool, I'll definitely have a look at those algorithms as well. I'm going to benchmark them for my research project and maybe implement my own algorithm :smile:

**Comment by Bonifatius94** [comment] 2022-12-28 14:26
> could you elaborate?

Sure, no problem. Here is the PR #1250 with my docs changes. Let me know if it's fine with you :wink:

**Closed** 2023-02-02 11:34 UTC
Labels: duplicate, question

**Comment by george-adams1** [comment] 2023-02-18 20:47
@araffin do you know if PPO is meant to mainly be trained on CPU or GPU?

**Comment by araffin** [comment] 2023-02-18 20:53
> do you know if PPO is meant to mainly be trained on CPU or GPU?

As A2C can be seen as a special case of PPO (https://arxiv.org/abs/2205.09123), the same recommendations apply to PPO (the preliminary results in https://github.com/DLR-RM/stable-baselines3/pull/1250#issuecomment-1413652861 should apply to PPO too).

**Comment by LinhNguyenTran** [comment] 2023-08-16 10:48
Hey @araffin i got this for A2C, PPO. How about DQN and SAC?

**Comment by Bonifatius94** [comment] 2023-08-16 13:06
> How about DQN and SAC?

Try it out. It's very specific for your particular training environment and hardware.

**Comment by LinhNguyenTran** [comment] 2023-08-16 15:38
Hello @Bonifatius94 , thank you for the prompt response. I've primarily used the simple CartPole environment so far, as I'm just getting started in this field. I've employed CartPole-v1 and experimented with the DQN, PPO, and A2C algorithms. I conducted these experiments both on my local Lenovo laptop and on a workstation (WS) equipped with a CPU (A32 Cores/64 Threads @ 3.5 GHz).

Interestingly, when I utilized the "SubprocVecEnv," my iterations per second (it/s) actually slowed down. Moreover, increasing the "n_envs" parameter resulted in a delayed convergence.

For instance:

    Locally, I encountered an error with "SubprocVecEnv," so I proceeded without it:

        A2C without SubprocVec on Notebook (n_envs=1)
            Speed: 1000 it/s
            Convergence: 79000 timesteps

        A2C with n_envs=4 on Notebook
            Speed: 4330 it/s
            Convergence: 531618 timesteps

    On the workstation without "SubprocVecEnv," I found it perplexing that the training was slower:
        A2C without SubprocVec on Workstation
            Speed: 768 it/s
            Convergence: 89964 timesteps

    On the workstation with "SubprocVecEnv":

        A2C with SubprocVec, n_envs=1 on Workstation
            Speed: 677 it/s
            Convergence: 141055 timesteps

        A2C with SubprocVec and n_envs=4 on Workstation
            Speed: 2611 it/s
            Convergence: 720818 timesteps

The code snippet used for these experiments
```
import gym
from stable_baselines3 import DQN, PPO, A2C
# ... (other code imports and settings)

env = make_vec_env('CartPole-v1', n_envs=1, monitor_dir=log_dir, vec_env_cls=SubprocVecEnv)

# ... (other code settings)

model = DQN(env=env, verbose=0, **hyperparams)

# Training
model.learn(250000, progress_bar=True, callback=[save_callback])
```

The Error for Local usage of SubprocVecEnv:

![image](https://github.com/DLR-RM/stable-baselines3/assets/69585347/1d73e37c-b062-4c5c-abca-23ad67f34f56)

**Comment by Bonifatius94** [comment] 2023-08-16 15:58
> Interestingly, when I utilized the "SubprocVecEnv," my iterations per second (it/s) actually slowed down

I know, it's because CartPole is such a simple environment (see the [gym repo](https://github.com/openai/gym/blob/master/gym/envs/classic_control/cartpole.py)). Using parallel threads is actually a huge overkill in comparison to computing the steps sequentially. In fact, CartPole performs best with DummyVecEnv and hilariously many n\_envs (10k or even more).

But honestly, CartPole is really a toy environment. Don't optimize for such a case. It doesn't matter whether it finishes in 5 or 10 minutes. Rather pick complex simulators / games like Atari or MuJoCo and try to solve those. That's where algorithms like PPO, SAC, etc. actually shine with their sample efficiency.

**Comment by LinhNguyenTran** [comment] 2023-08-17 11:56
Thank You @Bonifatius94, i will try to get to the complex things now. 

One small note: Can you maybe elaborate on what you meant by "performs best" by  setting CartPole-v1 with DummyVecEnv and n_envs=10k. 
(in terms of Time of Convergence, or Timesteps taken till success, or it/s?)

I tried that but it looks not that well. Training wasn't successful.
I tried different timesteps ranging from 50.000 to 5.000.000.

**Comment by Bonifatius94** [comment] 2023-08-17 12:03
I think it's very machine specific. You'll need to find this out by yourself :wink:
