### ISSUE TITLE
TypeError: ufunc 'isnan' not supported for the input types, Custom gym environment.

### ISSUE THREAD

**Issue by Sukhamjot-Singh** [DLR-RM/stable-baselines3#1323] opened 2023-02-09 13:08 UTC
### 🐛 Bug

Both my action and observation spaces are Dicts and check_env is giving an error.
I have also used FlattenObservation as I am using spaces.Dict for observation space and I am unsure about that part.

### Code example

```python
import gym
import math
import numpy as np
from gym import spaces

from stable_baselines.common.env_checker import check_env
from gym.wrappers import FlattenObservation

class NOMA(gym.Env):
  def __init__(self, M, k):
      self.M = M
      self.k = k
      self.observation_space = spaces.Dict({
          "theta": spaces.Box(0, 2*math.pi, shape = (M,M)),
          "gk_real": spaces.Box(-np.inf, np.inf, shape = (k, M)), 
          "gk_imag": spaces.Box(-np.inf, np.inf, shape = (k, M)), 
      })
      self.action_space = spaces.Dict({
          "theta": spaces.Box(0, 2*math.pi, shape = (M,M)),
          "pk": spaces.Box(-np.inf, np.inf, shape = (k,)),  
      })
  def step(self, action):
      reward = 0
      return self.observation_space.sample(), reward, True, {}
  def reset(self):
      return self.observation_space.sample()

env = NOMA(256, 4)
wrapped_env = FlattenObservation(env)
check_env(wrapped_env)
```

### Relevant log output / Error message

```shell
/usr/local/lib/python3.8/dist-packages/stable_baselines/common/vec_env/vec_check_nan.py in _check_val(self, async_step, **kwargs)
     56         found = []
     57         for name, val in kwargs.items():
---> 58             has_nan = np.any(np.isnan(val))
     59             has_inf = self.check_inf and np.any(np.isinf(val))
     60             if has_inf:

TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

### System Info

!pip install gym==0.21.0
!pip install stable_baselines

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have provided a minimal working example to reproduce the bug
- [X] I have checked my env using the env checker
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment] 2023-02-09 13:32
> I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo

Probably a duplicate of https://github.com/DLR-RM/stable-baselines3/issues/1319

**Comment by Sukhamjot-Singh** [comment] 2023-02-09 13:37
> > I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
> 
> Probably a duplicate of #1319
> 
> EDIT: my guess is that you are also using numpy >= 1.24, right?

The numpy version is 1.21.6 in my colab notebook.

**Comment by Sukhamjot-Singh** [comment] 2023-02-09 13:41
So is there a workaround for not using FlattenObservation wrapper? Sorry, i am new to this.

**Comment by Sukhamjot-Singh** [comment] 2023-02-24 09:53
@araffin Can you suggest me a workaround for this flattenObservation wrapper?
Thanks in advance

**Comment by araffin** [comment] 2023-02-24 10:19
> Can you suggest me a workaround for this flattenObservation wrapper?

the error comes from the env checker and only at the very end, so if you don't have any other warning/error, you can safely comment the env checker line.
If you still want to execute the env checker, you can catch the exception.
I should push a fix soon otherwise.

**Comment by araffin** [comment] 2023-02-25 13:56
you are using stable-baselines, not stable-baselines3...
with python 3.7, SB3 latest version and numpy 1.21, the env checker passes and output:
```
UserWarning: The action space is not based off a numpy array. Typically this means it's either a Dict or Tuple space. This type of action space is currently not supported by Stable Baselines 3. You should try to flatten the action using a wrapper.
```

**Closed** 2023-02-25 14:03 UTC
Labels: duplicate, question, custom gym env
