### ISSUE TITLE
How to transfer a policy optimized through behavioral cloning to a PPO Algorithm

### ISSUE THREAD

**Issue by LeonHenne** [DLR-RM/stable-baselines3#1453] opened 2023-04-14 12:17 UTC
### ❓ Question

Hello there,

Since it is hard for RL algorithms to find optimal policies in an a huge 3 dimensional optimization problem, my idea is to provide them a little help by first learning a policy through Imitation learning based on a rule-based policy and then transfer the policy or weights to fine tune them by a PPO Algorithm. The Problem that occurs is that it seems that there isn't really an interface between an ActorCriticPolicy and a PPO instance for this weight or knowledge transfer. 
I would be really grateful for any hints on how to perform this transfer.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment] 2023-04-14 12:45
Duplicate of https://github.com/DLR-RM/stable-baselines3/issues/1414 and #1411 
Related: we have a notebook about behavior cloning in the doc.

**Closed** 2023-04-14 13:56 UTC
Labels: duplicate, question, RTFM
