### ISSUE TITLE
Stable Baselines3 check_env shows wrong return type from reset() method

### ISSUE THREAD

**Issue by JustinS6626** [DLR-RM/stable-baselines3#1555] opened 2023-06-15 03:13 UTC
### 🐛 Bug

I am trying to run an experiment with Stable Baselines 3 using a PPO optimization method with a custom environment based on the Minigrid environment maintained by the Farama Foundation. When I run the `check_env` statement, it finds errors with the `reset` method of my environment for which the stack trace says that the obs returned by the reset function needs to be a numpy array. I am unable to locate the sources of the error, since my custom minigrid uses the same reset method that it inherits from the base class. I have looked over the instructions on the Minigrid docs for creating custom environments, but I am still not clear on where my mistake is. I don't have a lot of experience using custom environments, so I would really appreciate some help.

### Code example

This is the code for the environment itself:

```
import numpy as np
from minigrid.core.grid import Grid
from minigrid.core.mission import MissionSpace
from minigrid.core.world_object import Goal, Lava, Wall
from minigrid.minigrid_env import MiniGridEnv
from enum import IntEnum
from gymnasium import spaces

class LavagridActions(IntEnum):
    left = 0
    right = 1
    forward = 2

def array_in_list(a, l):
    contained = False
    for item in l:
        if (a == item).all():
            contained = True
    return contained

class coord_tree:
    def __init__(self, data, is_goal):
        self.data = data
        self.is_goal = is_goal
        self.north = None
        self.south = None
        self.east = None
        self.west = None
        
    def build(self, obstacles, visited, goal, dim, n_stops):
        visited.append(self.data)
        new_stops = 0
        if self.data[0] == 1 and self.data[1] == 1:
            #print("Case 0")
            n_stops += 1
            south_coord = np.array([self.data[0] + 1, self.data[1]])
            south_goal = (south_coord == goal).all()
            if array_in_list(south_coord, obstacles) == False and array_in_list(south_coord, visited) == False and n_stops < dim ** 2 and self.is_goal == False:
                #print("South tile clear")
                self.south = coord_tree(south_coord, south_goal)
                new_stops += 1
            east_coord = np.array([self.data[0], self.data[1] + 1])
            east_goal = (east_coord == goal).all()
            if array_in_list(east_coord, obstacles) == False and array_in_list(east_coord, visited) == False and n_stops < dim ** 2 and self.is_goal == False:

                #print("East tile clear")
                self.east = coord_tree(east_coord, east_goal)
                new_stops += 1
            #print("Stops reached: " + str(n_stops + new_stops))
            if self.south is not None:
                #print("Building south")
                self.south.build(obstacles, visited, goal, dim, n_stops + new_stops)
            #else:
                #print("Can't build south")
            if self.east is not None:
                #print("Building east")
                self.east.build(obstacles, visited, goal, dim, n_stops + new_stops)
            #else:
                #print("Can't build east")
        else:
            if self.data[0] == 1:
                if self.data[1] == dim:
                    #print("Case 1")
                    south_coord = np.array([self.data[0] + 1, self.data[1]])
                    south_goal = (south_coord == goal).all()
                    if array_in_list(south_coord, obstacles) == False and array_in_list(south_coord, visited) == False and n_stops < dim ** 2 and self.is_goal == False:
                        self.south = coord_tree(south_coord, south_goal)
                        new_stops += 1
                    west_coord = np.array([self.data[0], self.data[1] - 1])
                    west_goal = (west_coord == goal).all()
                    if array_in_list(west_coord, obstacles) == False and array_in_list(west_coord, visited) == False and n_stops < dim ** 2 and self.is_goal == False:
                        self.west = coord_tree(west_coord, west_goal)
                        new_stops += 1
                    #print("Stops reached: " + str(n_stops + new_stops))
                    if self.south is not None:
                        self.south.build(obstacles, visited, goal, dim, n_stops + new_stops)
                    if self.west is not None:
                        self.west.build(obstacles, visited, goal, dim, n_stops + new_stops)
                else:
                    #print("Case 2")
                    south_coord = np.array([self.data[0] + 1, self.data[1]])
                    south_goal = (south_coord == goal).all()
                    if array_in_list(south_coord, obstacles) == False and array_in_list(south_coord, visited) == False and n_stops < dim ** 2 and self.is_goal == False:
                        self.south = coord_tree(south_coord, south_goal)
                        new_stops += 1
                    east_coord = np.array([self.data[0], self.data[1] + 1])
                    east_goal = (east_coord == goal).all()
                    if array_in_list(east_coord, obstacles) == False and array_in_list(east_coord, visited) == False and n_stops < dim ** 2 and self.is_goal == False:
                        self.east = coord_tree(east_coord, east_goal)
                        new_stops += 1
                    west_coord = np.array([self.data[0], self.data[1] - 1])
                    west_goal = (west_coord == goal).all()
                    if array_in_list(west_coord, obstacles) == False and array_in_list(west_coord, visited) == False and n_stops < dim ** 2 and self.is_goal == False:
                        self.west = coord_tree(west_coord, west_goal)
                        new_stops += 1
                    #print("Stops reached: " + str(n_stops + new_stops))
                    if self.south is not None:
                        self.south.build(obstacles, visited, goal, dim, n_stops + new_stops)
                    if self.east is not None:
                        self.east.build(obstacles, visited, goal, dim, n_stops + new_stops)
                    if self.west is not None:
                        self.west.build(obstacles, visited, goal, dim, n_stops + new_stops)
            elif self.data[0] == dim:
                if self.data[1] == 1:
                    #print("Case 3")
                    north_coord = np.array([self.data[0] - 1, self.data[1]])
                    north_goal = (north_coord == goal).all()
                    if array_in_list(north_coord, obstacles) == False and array_in_list(north_coord, visited) == False and n_stops < dim ** 2 and self.is_goal == False:
                        self.north = coord_tree(north_coord, north_goal)
                        new_stops += 1
                    east_coord = np.array([self.data[0], self.data[1] + 1])
                    east_goal = (east_coord == goal).all()
                    if array_in_list(east_coord, obstacles) == False and array_in_list(east_coord, visited) == False and n_stops < dim ** 2 and self.is_goal == False:
                        self.east = coord_tree(east_coord, east_goal)
                        new_stops += 1
                    #print("Stops reached: " + str(n_stops + new_stops))
                    if self.north is not None:
                        self.north.build(obstacles, visited, goal, dim, n_stops + new_stops)
                    if self.east is not None:
                        self.east.build(obstacles, visited, goal, dim, n_stops + new_stops)
                elif self.data[1] == dim:
                    #print("Case 4")
                    north_coord = np.array([self.data[0] - 1, self.data[1]])
                    north_goal = (north_coord == goal).all()
                    if array_in_list(north_coord, obstacles) == False and array_in_list(north_coord, visited) == False and n_stops < dim ** 2 and self.is_goal == False:
                        self.north = coord_tree(north_coord, north_goal)
                        new_stops += 1
                    west_coord = np.array([self.data[0], self.data[1] - 1])
                    west_goal = (west_coord == goal).all()
                    if array_in_list(west_coord, obstacles) == False and array_in_list(west_coord, visited) == False and n_stops < dim ** 2 and self.is_goal == False:
                        self.west = coord_tree(west_coord, west_goal)
                        new_stops += 1
                    #print("Stops reached: " + str(n_stops + new_stops))
                    if self.north is not None:
                        self.north.build(obstacles, visited, goal, dim, n_stops + new_stops)
                    if self.west is not None:
                        self.west.build(obstacles, visited, goal, dim, n_stops + new_stops)
                else:
                    #print("Case 5")
                    north_coord = np.array([self.data[0] - 1, self.data[1]])
                    north_goal = (north_coord == goal).all()
                    if array_in_list(north_coord, obstacles) == False and array_in_list(north_coord, visited) == False and n_stops < dim ** 2 and self.is_goal == False:
                        self.north = coord_tree(north_coord, north_goal)
                        new_stops += 1
                    east_coord = np.array([self.data[0], self.data[1] + 1])
                    east_goal = (east_coord == goal).all()
                    if array_in_list(east_coord, obstacles) == False and array_in_list(east_coord, visited) == False and n_stops < dim ** 2 and self.is_goal == False:
                        self.east = coord_tree(east_coord, east_goal)
                        new_stops += 1
                    west_coord = np.array([self.data[0], self.data[1] - 1])
                    west_goal = (west_coord == goal).all()
                    if array_in_list(west_coord, obstacles) == False and array_in_list(west_coord, visited) == False and n_stops < dim ** 2 and self.is_goal == False:
                        self.west = coord_tree(west_coord, west_goal)
                        new_stops += 1
                    #print("Stops reached: " + str(n_stops + new_stops))
                    if self.north is not None:
                        self.north.build(obstacles, visited, goal, dim, n_stops + new_stops)
                    if self.east is not None:
                        self.east.build(obstacles, visited, goal, dim, n_stops + new_stops)
                    if self.west is not None:
                        self.west.build(obstacles, visited, goal, dim, n_stops + new_stops)
            else:
                if self.data[1] == 1:
                    #print("Case 6")
                    north_coord = np.array([self.data[0] - 1, self.data[1]])
                    north_goal = (north_coord == goal).all()
                    if array_in_list(north_coord, obstacles) == False and array_in_list(north_coord, visited) == False and n_stops < dim ** 2 and self.is_goal == False:
                        self.north = coord_tree(north_coord, north_goal)
                        new_stops += 1
                    south_coord = np.array([self.data[0] + 1, self.data[1]])
                    south_goal = (south_coord == goal).all()
                    if array_in_list(south_coord, obstacles) == False and array_in_list(south_coord, visited) == False and n_stops < dim ** 2 and self.is_goal == False:
                        self.south = coord_tree(south_coord, south_goal)
                        new_stops += 1
                    east_coord = np.array([self.data[0], self.data[1] + 1])
                    east_goal = (east_coord == goal).all()
                    if array_in_list(east_coord, obstacles) == False and array_in_list(east_coord, visited) == False and n_stops < dim ** 2 and self.is_goal == False:
                        self.east = coord_tree(east_coord, east_goal)
                        new_stops += 1
                    #print("Stops reached: " + str(n_stops + new_stops))
                    if self.north is not None:
                        self.north.build(obstacles, visited, goal, dim, n_stops + new_stops)
                    if self.south is not None:
                        self.south.build(obstacles, visited, goal, dim, n_stops + new_stops)
                    if self.east is not None:
                        self.east.build(obstacles, visited, goal, dim, n_stops + new_stops)
                elif self.data[1] == dim:
                    #print("Case 7")
                    north_coord = np.array([self.data[0] - 1, self.data[1]])
                    north_goal = (north_coord == goal).all()
                    if array_in_list(north_coord, obstacles) == False and array_in_list(north_coord, visited) == False and n_stops < dim ** 2 and self.is_goal == False:
                        self.north = coord_tree(north_coord, north_goal)
                        new_stops += 1
                    south_coord = np.array([self.data[0] + 1, self.data[1]])
                    south_goal = (south_coord == goal).all()
                    if array_in_list(south_coord, obstacles) == False and array_in_list(south_coord, visited) == False and n_stops < dim ** 2 and self.is_goal == False:
                        self.south = coord_tree(south_coord, south_goal)
                        new_stops += 1
                    west_coord = np.array([self.data[0], self.data[1] - 1])
                    west_goal = (west_coord == goal).all()
                    if array_in_list(west_coord, obstacles) == False and array_in_list(west_coord, visited) == False and n_stops < dim ** 2 and self.is_goal == False:
                        self.west = coord_tree(west_coord, west_goal)
                        new_stops += 1
                    #print("Stops reached: " + str(n_stops + new_stops))
                    if self.north is not None:
                        self.north.build(obstacles, visited, goal, dim, n_stops + new_stops)
                    if self.south is not None:
                        self.south.build(obstacles, visited, goal, dim, n_stops + new_stops)
                    if self.west is not None:
                        self.west.build(obstacles, visited, goal, dim, n_stops + new_stops)
                else:
                    #print("Case 8")
                    north_coord = np.array([self.data[0] - 1, self.data[1]])
                    north_goal = (north_coord == goal).all()
                    if array_in_list(north_coord, obstacles) == False and array_in_list(north_coord, visited) == False and n_stops < dim ** 2 and self.is_goal == False:
                        self.north = coord_tree(north_coord, north_goal)
                        new_stops += 1
                    south_coord = np.array([self.data[0] + 1, self.data[1]])
                    south_goal = (south_coord == goal).all()
                    if array_in_list(south_coord, obstacles) == False and array_in_list(south_coord, visited) == False and n_stops < dim ** 2 and self.is_goal == False:
                        self.south = coord_tree(south_coord, south_goal)
                        new_stops += 1
                    east_coord = np.array([self.data[0], self.data[1] + 1])
                    east_goal = (east_coord == goal).all()
                    if array_in_list(east_coord, obstacles) == False and array_in_list(east_coord, visited) == False and n_stops < dim ** 2 and self.is_goal == False:
                        self.east = coord_tree(east_coord, east_goal)
                        new_stops += 1
                    west_coord = np.array([self.data[0], self.data[1] - 1])
                    west_goal = (west_coord == goal).all()
                    if array_in_list(west_coord, obstacles) == False and array_in_list(west_coord, visited) == False and n_stops < dim ** 2 and self.is_goal == False:
                        self.west = coord_tree(west_coord, west_goal)
                        new_stops += 1
                    #print("Stops reached: " + str(n_stops + new_stops))
                    if self.north is not None:
                        self.north.build(obstacles, visited, goal, dim, n_stops + new_stops)
                    if self.south is not None:
                        self.south.build(obstacles, visited, goal, dim, n_stops + new_stops)
                    if self.east is not None:
                        self.east.build(obstacles, visited, goal, dim, n_stops + new_stops)
                    if self.west is not None:
                        self.west.build(obstacles, visited, goal, dim, n_stops + new_stops)
        #print("Build done")
                        

    def find_path(self):
        if self.north is None and self.south is None and self.east is None and self.west is None:
            return self.is_goal
        else:
            if self.north is not None:
                if self.south is not None:
                    if self.east is not None:
                        if self.west is not None:
                            #print("Branch 1")
                            return self.north.find_path() or self.south.find_path() or self.east.find_path() or self.west.find_path()
                        else:
                            #print("Branch 2")
                            return self.north.find_path() or self.south.find_path() or self.east.find_path()
                    else:
                        if self.west is not None:
                            #print("Branch 3")
                            return self.north.find_path() or self.south.find_path() or self.west.find_path()
                        else:
                            #print("Branch 4")
                            return self.north.find_path or self.south.find_path()
                else:
                    if self.east is not None:
                        if self.west is not None:
                            #print("Branch 5")
                            return self.north.find_path() or self.east.find_path() or self.west.find_path()
                        else:
                            #print("Branch 6")
                            return self.north.find_path() or self.east.find_path()
                    else:
                        if self.west is not None:
                            #print("Branch 7")
                            return self.north.find_path() or self.west.find_path()
                        else:
                            #print("Branch 8")
                            return self.north.find_path()
            else:
                if self.south is not None:
                    if self.east is not None:
                        if self.west is not None:
                            #print("Branch 9")
                            return self.south.find_path() or self.east.find_path() or self.west.find_path()
                        else:
                            #print("Branch 10")
                            return self.south.find_path() or self.east.find_path()
                    else:
                        if self.west is not None:
                            #print("Branch 11")
                            return self.south.find_path() or self.west.find_path()
                        else:
                            #print("Branch 12")
                            return self.south.find_path()
                else:
                    if self.east is not None:
                        if self.west is not None:
                            #print("Branch 13")
                            return self.east.find_path() or self.west.find_path()
                        else:
                            #print("Branch 14")
                            return self.east.find_path()
                    else:
                        #print("Branch 15")
                        return self.west.find_path()

class RandomLavaEnv(MiniGridEnv):
    def __init__(self, size, n_obstacles,
                 obstacle_type=Lava,
                 max_steps=None, **kwargs):
        self.obstacle_type = obstacle_type
        self.obstacles = []
        self.lava_list = []
        self.size = size
        self.bumps = 0
        self.goal_pos = np.array((self.size - 2, self.size - 2))
        self.stored_grid = None
        self.actions = LavagridActions
        self.action_space = spaces.Discrete(len(self.actions))
        
        if obstacle_type == Lava:
            mission_space = MissionSpace(mission_func=self._gen_mission_lava)
        else:
            mission_space = MissionSpace(mission_func=self._gen_mission)

        if max_steps is None:
            max_steps = 4 * size**2
        self.n_obstacles = n_obstacles
##        if n_obstacles != self.size:
##            self.n_obstacles = int(self.size)
##        else:
##            self.n_obstacles = n_obstacles

        super().__init__(mission_space=mission_space,
                         grid_size=size,
                         see_through_walls=True,
                         max_steps=max_steps,
                         **kwargs)
        self.reward_range=(-1, 1)

    @staticmethod
    def _gen_mission_lava():
        return "avoid lava and get to the green goal square"

    @staticmethod
    def _gen_mission():
        return "find the opening and get to the green goal square"

    def _gen_grid(self, width, height):
        assert width >= 5 and height >= 5
        self.grid = Grid(width, height)
        #print("Grid made")
        self.grid.wall_rect(0, 0, width, height)
        #print("Wall complete")
        self.grid.set(width - 2, height - 2, Goal())
        #print("Goal placed")
        self.agent_pos = np.array([1, 1])
        self.agent_dir = 0
        
        if len(self.obstacles) == 0:
            for i_obst in range(self.n_obstacles):
                self.obstacles.append(Lava())
            #self.place_obj(self.obstacles[i_obst], max_tries=100)
            retry = True
            while retry:
                #print("Trying again")
                self.lava_list = []
                for i_obst in range(self.n_obstacles):
                    #print("Obstacle number: " + str(i_obst))
                    attempt = True
                    while attempt:
                        #print("Placing lava")
                        lava_x = self._rand_int(1, width - 2)
                        #print("Lava x" + str(lava_x))
                        if lava_x == 1:
                            lava_y = self._rand_int(2, height - 2)
                        elif lava_x == width - 2:
                            lava_y = self._rand_int(1, height - 3)
                        else:
                            lava_y = self._rand_int(1, height - 1)
                        lava_spot = np.array([lava_y, lava_x])
                        if array_in_list(lava_spot, self.lava_list) == False:
                            self.lava_list.append(lava_spot)
                            attempt = False
                valid_map = self.path_check(np.array(self.agent_pos), self.lava_list, [])
                #print("path examined")
                if valid_map and len(self.lava_list) == self.n_obstacles:
                    retry = False

        for i in range(len(self.lava_list)):
            spot = self.lava_list[i]
            self.put_obj(self.obstacles[i], *spot)
                #print("Lava pit placed")
                
                
                #self.put_obj(self.obstacles[i_obst], *lava_spot)
        self.mission = ("avoid the lava and get to the green goal square" if self.obstacle_type == Lava else "find the opening and get to the green goal square")
        self.stored_grid = self.grid
        

##    def reset(self, seed=0, options=None):
##        init_obs, info = super().reset(seed=seed)
##        self.grid = self.stored_grid
##        obs = super().gen_obs()
##        return obs, info
        
            

                               

    def path_check(self, coordinates, obstacles, visited):
        #print(coordinates)
        #print(visited)
        initial_point = coord_tree(coordinates, False)
        initial_point.build(obstacles, visited, self.goal_pos, self.size - 2, 0)
        #print("Build complete")
        has_path = initial_point.find_path()
        return has_path

                                           
    def step(self, action):
        self.step_count += 1
        if action >= self.action_space.n:
            action = 0
        front_cell = self.grid.get(*self.front_pos)
        #print(type(front_cell))
        not_clear = front_cell and front_cell.type != "goal"
        is_lava = front_cell and front_cell.type == "lava"
        obs, reward, terminated, truncated, info = super().step(action)
        if action == self.actions.forward:
            if not_clear:
                if is_lava:
                    #reward = -0.9 + 0.9 * (self.step_count / self.max_steps)
                    reward = -1
                    terminated = True
                    self.bumps = 0
##                else:
##                    #self.bumps += 1
##                    #reward = -0.01 * 0.9 * (self.bumps / self.max_steps)
##                    reward = -1
##                    terminated = True
                return obs, reward, terminated, truncated, info
            else:
                if front_cell is None:
                    if terminated == True:
                        reward = -1
                        self.bumps = 0
                    else:
                        reward = 0
                else:
                    if front_cell.type != "goal":
                        if terminated == True:
                            reward = -1
                            self.bumps = 0
                        else:
                            reward = 0
        else:
            if terminated or truncated:
                reward = -1
                self.bumps = 0
            else:
                reward = 0
##        if self.step_count >= self.max_steps:
##            truncated = True
##            terminated = True
##            reward = -1
##        if self.step_count == self.max_steps - 1:
##            reward = -1 + 0.9 * (self.step_count / self.max_steps)
##            self.bumps = 0
        
        return obs, reward, terminated, truncated, info
```
This code was executed in a separate file to produce the error:

```
import gymnasium as gym
from gymnasium.envs.registration import *
from stable_baselines3.common.env_checker import check_env

register(
    id="Minigrid-RandomLava-6Spots-v0",
    entry_point="RandomLavaMinigrid:RandomLavaEnv",
    kwargs={"size": 8, "n_obstacles": 6})

env_name = "Minigrid-RandomLava-6Spots-v0"
env = gym.make(env_name, max_episode_steps=100, render_mode="human")
check_env(env)
obs, info = env.reset(seed=0)

```

### Relevant log output / Error message

```shell
Warning (from warnings module):
  File "/usr/lib/python3/dist-packages/requests/__init__.py", line 89
    warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
RequestsDependencyWarning: urllib3 (1.26.14) or chardet (3.0.4) doesn't match a supported version!

Warning (from warnings module):
  File "/usr/local/lib/python3.8/dist-packages/gymnasium/utils/passive_env_checker.py", line 188
    logger.warn(f"{pre} is not within the observation space.")
UserWarning: [33mWARN: The obs returned by the `reset()` method is not within the observation space.[0m

Warning (from warnings module):
  File "/usr/local/lib/python3.8/dist-packages/stable_baselines3/common/env_checker.py", line 51
    warnings.warn(
UserWarning: The minimal resolution for an image is 36x36 for the default `CnnPolicy`. You might need to use a custom features extractor cf. https://stable-baselines3.readthedocs.io/en/master/guide/custom_policy.html
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/stable_baselines3/common/env_checker.py", line 271, in _check_returned_values
    _check_obs(obs[key], observation_space.spaces[key], "reset")
  File "/usr/local/lib/python3.8/dist-packages/stable_baselines3/common/env_checker.py", line 190, in _check_obs
    assert isinstance(obs, np.ndarray), f"The observation returned by `{method_name}()` method must be a numpy array"
AssertionError: The observation returned by `reset()` method must be a numpy array

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/idlelib/run.py", line 559, in runcode
    exec(code, self.locals)
  File "/home/justin/LavagridTest.py", line 12, in <module>
    check_env(env)
  File "/usr/local/lib/python3.8/dist-packages/stable_baselines3/common/env_checker.py", line 438, in check_env
    _check_returned_values(env, observation_space, action_space)
  File "/usr/local/lib/python3.8/dist-packages/stable_baselines3/common/env_checker.py", line 273, in _check_returned_values
    raise AssertionError(f"Error while checking key={key}: " + str(e)) from e
AssertionError: Error while checking key=mission: The observation returned by `reset()` method must be a numpy array
```
```


### System Info

GPU: NVIDIA GeForce RTX 2060 Super, Driver version 470.182.03
Installation: pip3.8 (Bleeding edge installation)
Python: 3.8.10
PyTorch: 2.0.0+cu117
Gymnasium: 0.28.1
Gym: 0.21.0
Minigrid: 2.3.0

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have provided a minimal working example to reproduce the bug
- [X] I have checked my env using the env checker
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment] 2023-06-15 03:35
Probably duplicate of https://github.com/DLR-RM/stable-baselines3/issues/1548, as stated in the doc you need SB3 v2.x for gymnasium support.

**Comment by DarthMalloc** [comment] 2023-06-15 04:39
I already checked on that. My version is 2.0.0a13. Are there any other possible reasons why that might be occurring?

**Comment by araffin** [comment] 2023-06-15 05:19
"AssertionError: Error while checking key=mission: The observation returned by `reset()` method must be a numpy array"

btw, your code example is not minimal despite the ticked box...

**Closed** 2023-07-03 09:45 UTC
Labels: question, custom gym env, more information needed, check the checkboxes
