### ISSUE TITLE
[Bug]: Using gymnasium's vectorised environments

### ISSUE THREAD

**Issue by sryu1** [DLR-RM/stable-baselines3#1608] opened 2023-07-15 02:10 UTC
### 🐛 Bug

using vectorised gymnasium environments raise an error.

### To Reproduce

```python
import gymnasium as gym
from stable_baselines3 import PPO
vec_env = gym.make_vec("CartPole-v1", num_envs=4)
vec_env.reset(seed=42)
model = PPO("MlpPolicy", vec_env)
```

### Relevant log output / Error message

```shell
Traceback (most recent call last):
  File "<pyshell#4>", line 1, in <module>
    model = PPO("MlpPolicy", vec_env)
  File "C:\Users\noahs\AppData\Local\Programs\Python\Python311\Lib\site-packages\stable_baselines3\ppo\ppo.py", line 104, in __init__
    super().__init__(
  File "C:\Users\noahs\AppData\Local\Programs\Python\Python311\Lib\site-packages\stable_baselines3\common\on_policy_algorithm.py", line 81, in __init__
    super().__init__(
  File "C:\Users\noahs\AppData\Local\Programs\Python\Python311\Lib\site-packages\stable_baselines3\common\base_class.py", line 169, in __init__
    env = self._wrap_env(env, self.verbose, monitor_wrapper)
  File "C:\Users\noahs\AppData\Local\Programs\Python\Python311\Lib\site-packages\stable_baselines3\common\base_class.py", line 216, in _wrap_env
    env = _patch_env(env)
  File "C:\Users\noahs\AppData\Local\Programs\Python\Python311\Lib\site-packages\stable_baselines3\common\vec_env\patch_gym.py", line 33, in _patch_env
    raise ValueError(
ValueError: The environment is of type <class 'gymnasium.experimental.vector.async_vector_env.AsyncVectorEnv'>, not a Gymnasium environment. In this case, we expect OpenAI Gym to be installed and the environment to be an OpenAI Gym environment.
```

### System Info

All installed via pip
- OS: Windows-10-10.0.22621-SP0 10.0.22621
- Python: 3.11.4
- Stable-Baselines3: 2.0.0
- PyTorch: 2.0.1+cpu
- GPU Enabled: False
- Numpy: 1.25.1
- Cloudpickle: 2.2.1
- Gymnasium: 0.29.0
- Gym 0.26.1

### Checklist

- [X] My issue does not relate to a custom gym environment. (Use the custom gym env template instead)
- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have provided a [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014) example to reproduce the bug
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by sryu1** [comment] 2023-07-15 02:12
I know Gymnasium 0.29.0 does not support SB3==2.0.0 but same thing happens with 0.28.1

**Comment by araffin** [comment] 2023-07-15 11:49
Duplicate of https://github.com/DLR-RM/stable-baselines3/issues/1568

**Closed by araffin** 2023-07-15 11:49 UTC
Labels: duplicate, RTFM, check the checkboxes
