### ISSUE TITLE
Adding dropout to a custom network

### ISSUE THREAD

**Issue by Karlheinzniebuhr** [DLR-RM/stable-baselines3#1666] opened 2023-09-05 22:46 UTC
### ❓ Question

I'm trying to add dropout to my network, but everything I tried gets me some kind of error. 

```
import gym
import torch
import torch.nn as nn
from stable_baselines3.common.policies import ActorCriticPolicy
from stable_baselines3 import PPO

# Define a minimal Gym environment (CartPole-v1)
envs = gym.make("CartPole-v1")

class CustomMlpPolicy(ActorCriticPolicy):
    def __init__(self, *args, **kwargs):
        super(CustomMlpPolicy, self).__init__(*args, **kwargs)
        
        # Modify the policy network to add dropout layers
        self.policy_net = nn.Sequential(
            nn.Linear(self.mlp_extractor.output_dim, 128),
            nn.Tanh(),
            nn.Dropout(p=0.5),  # Add dropout to the first hidden layer
            nn.Linear(128, 128),
            nn.Tanh(),
        )

        # Value network remains the same
        self.value_net = nn.Sequential(
            nn.Linear(self.mlp_extractor.output_dim, 256),
            nn.Tanh(),
            nn.Linear(256, 256),
            nn.Tanh(),
            nn.Linear(256, 256),
            nn.Tanh(),
            nn.Linear(256, 256),
            nn.Tanh(),
        )

# Create the PPO model using your custom policy
model = PPO(CustomMlpPolicy, envs)
model.learn(total_timesteps=10000)  # Train for a specified number of timesteps

```

`AttributeError: 'MlpExtractor' object has no attribute 'output_dim'`

I checked the [documentation](https://stable-baselines3.readthedocs.io/en/master/guide/custom_policy.html) but it does not contain any reference to dropouts. 

How can I implement dropouts? 

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014)
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment] 2023-09-06 06:20
Duplicate of https://github.com/DLR-RM/stable-baselines3/issues/1069#issuecomment-1251485510, a working example can be found in https://github.com/DLR-RM/stable-baselines3/pull/1036

**Comment by Karlheinzniebuhr** [comment] 2023-09-06 20:53
I'm afraid #1036 only works for SAC() since PPO didn't get an update with that PR.

**Comment by araffin** [comment] 2023-09-07 06:36
> I'm afraid #1036 only works for SAC() since PPO didn't get an update with that PR.

well, nothing prevent you from forking and doing the update yourself ;)
i mostly wanted to link a working example with dropout.

**Closed** 2023-09-24 17:35 UTC
Labels: duplicate, question
