### ISSUE TITLE
Environment is reset twice per episode when evaluating policy on DummyVecEnv

### ISSUE THREAD

**Issue by tirafesi** [DLR-RM/stable-baselines3#60] opened 2020-06-15 14:29 UTC
The `evaluate_policy` helper function reset the environment at the start of each episode:

https://github.com/DLR-RM/stable-baselines3/blob/494ebfd20abe90acc136fdaf215c76ec566acd2c/stable_baselines3/common/evaluation.py#L33-L34

But `DummyVecEnv` automatically resets the environment when `step` returns `done = true`: 

https://github.com/DLR-RM/stable-baselines3/blob/494ebfd20abe90acc136fdaf215c76ec566acd2c/stable_baselines3/common/vec_env/dummy_vec_env.py#L45-L48

This causes the environment to reset twice per episode when evaluating the policy.

**Comment by Miffyli** [comment] 2020-06-15 14:38
Good catch, indeed it is being reset twice. Looks like a simple solution would be to move the first `reset` outside the loop in `evaluate_policy`.

@araffin Pinging you to give a comment on this, in case we missed something important.

**Comment by tirafesi** [comment] 2020-06-15 14:44
@Miffyli In my opinion, a better fix would be to remove the call to `reset` from DummyVecEnv's `step` method. It doesn't seem very intuitive that step would automatically reset the environment - the user should be responsible for checking when `done = true` themselves. Also, this results in even the simple examples from Gym also resetting the envs twice per episode. Example taken from [here](https://gym.openai.com/):

```python3
import gym
from stable_baselines3.common.vec_env import DummyVecEnv

env = DummyVecEnv([lambda: gym.make("CartPole-v1")])
observation = env.reset()
for _ in range(1000):
  env.render()
  action = env.action_space.sample() # your agent here (this takes random actions)
  observation, reward, done, info = env.step(action)

  if done[0]:
    observation = env.reset() # double reset, since it was already called by DummyVecEnv step
env.close()
```

**Comment by Miffyli** [comment] 2020-06-15 14:49
This would make things more complicated when implementing algorithms and gathering samples from multiple envs, though. You would have to loop over `dones`, see what were `True`, specifically reset those envs, update obs and also update any masks/hidden states. By letting `step` do resets when necessary, this gets abstracted away and simplifies training process/code.

But indeed this leads to more complicated/confusing setup when evaluating and working on single environments. However both sb and sb3 algorithms assume vectorized environments (even in the case of single environment) to simplify the code-base by only covering one of these APIs.

**Comment by araffin** [comment] 2020-06-16 12:30
>Pinging you to give a comment on this, in case we missed something important.

I had that issue for another project. I think a better solution would be to allow deactivating automatic reset but keep it `True` by default.
And even if we are using a `VecEnv`, we still need to call `reset()` the very first time.
Maybe adding a `need_reset()` method to the `VecEnv` would solve the issue?

**Comment by Miffyli** [comment] 2020-06-17 08:43
> I had that issue for another project. 
Was it this same evaluation mistake? In that case the error would be fixed by moving the reset outside the loop. I see the point behind adding argument for disabling automatic resets (and then we need the `need_reset()` function), but I do not see need for adding it if it is not going to be used.

**Comment by araffin** [comment] 2020-06-19 08:44
>In that case the error would be fixed by moving the reset outside the loop.

This does not solve the complete problem (the environment will still be reset twice but at least not after every episode)

> I see the point behind adding argument for disabling automatic resets (and then we need the need_reset() function), but I do not see need for adding it if it is not going to be used.

Good point. My main concern is that it is one of the less intuitive behavior that we have (we had several issues asking about where is the reset done).
So, in fact, to solve that issue, we just need the `need_reset()` method.

(On another project, where I was using teleoperation, I had to define a custom `VecEnv` that does not auto-reset in order to re-initialize manually the robot before resetting the env.)

**Comment by Miffyli** [comment] 2020-06-19 10:50
Ok, I agree we at least need the `need_reset()` function (returns True if at least one environment requires reset?). To help clarifying how VecEnv works, we could add the `reset_automatically=True` parameter to `step` function. Seeing the parameter should already tell a little bit about how they work, and I would have enjoyed same feature back when I was confused with the "vectorized environments" :D

**Comment by araffin** [comment] 2020-06-22 08:47
>To help clarifying how VecEnv works, we could add the reset_automatically=True parameter to step function.

I don't like changing the api of `step()` :/ (which should mimic the gym api) even though I understand your point.

**Comment by Miffyli** [comment] 2020-06-24 14:23
Ah, right, good point. In that case it can be passed in init. In any case, the documentation should reflect the behaviour as precisely as possible (e.g. what needs to be done if it automatically does not reset). Also what should be the behaviour of `reset()`? Shall it reset all environments, or only reset the ones that need resetting? The former matches Gym API, but makes little sense, while latter makes things easier but breaks the behaviour. Should it be a new function `reset_done_envs()` which only resets environments which reached `done=True`, and then returns observations for _all_ environments. The observations for non-resetted environments are the observations from previous `step` call.

**Comment by araffin** [comment] 2020-06-24 15:04
>Shall it reset all environments, or only reset the ones that need resetting?

It shall reset all envs, you have the `env_method()` for something more granular.
We have to keep in mind that this feature will be used in special cases only and the current behavior work in most cases, so I would avoid overcomplicated things.

**Closed** 2020-08-05 10:12 UTC
Labels: bug

**Comment by llewynS** [comment] 2023-10-31 08:11
This is still an issue in 2023. Should be capitalised in documentation as it is atypical behaviour.

**Comment by araffin** [comment] 2023-10-31 08:15
> This is still an issue in 2023.

The double reset issue was fixed in https://github.com/DLR-RM/stable-baselines3/pull/136

If you think it's not the case, please provide a minimal and working example to reproduce the issue.

**Comment by logan-dunbar** [comment] 2025-06-17 20:44
I think this issue has regressed, if you look at the changes made in [#136](https://github.com/DLR-RM/stable-baselines3/pull/136) there is a check on VecEnv to decide whether to reset initially or not:
```python
for i in range(n_eval_episodes):
    # Avoid double reset, as VecEnv are reset automatically
    if not isinstance(env, VecEnv) or i == 0:
        obs = env.reset()
````

But in the [current main branch](https://github.com/DLR-RM/stable-baselines3/blob/9e5ccc1832366d55abbf31b561ea9dcfbfdfa485/stable_baselines3/common/evaluation.py#L87) there is no longer a check. This is messing with the ability to record videos correctly as it creates 2 videos per true reset of the env.
