### ISSUE TITLE
[Question] How to log success rate per 100 episodes  using a custom callback?

### ISSUE THREAD

**Issue by phil695** [DLR-RM/stable-baselines3#1454] opened 2023-04-14 12:24 UTC
### ❓ Question

Thanks for your great work! I am a fresher in RL, and I want to konw how to log success rate per 100 episodes  using a custom callback?

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment] 2023-04-14 12:28
> have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)

what have you read/tried so far?

**Comment by phil695** [comment] 2023-04-14 12:40
I have read the documentation about Logger . It seems that this way of success_rate only works for off-policy algorithms in #945 ,so i want to use custom callback and i have read the part of "callback" in documentation but i do not konw how to achieve this custom function which log success rate per 100 episodes

**Comment by araffin** [comment] 2023-04-14 12:49
Partial duplicate of https://github.com/DLR-RM/stable-baselines3/issues/954 and 
https://github.com/DLR-RM/stable-baselines3/issues/410 and https://github.com/DLR-RM/stable-baselines3/issues/1300

Related : #1424

**Closed** 2023-04-23 21:05 UTC
Labels: duplicate, question
