### ISSUE TITLE
[Question] Does PPO handle timeout and bootstrap correctly?

### ISSUE THREAD

**Issue by zhihanyang2022** [DLR-RM/stable-baselines3#651] opened 2021-11-04 08:04 UTC
### Question

SB3's PPO does not seem to distinguish between done and timeout, and only relies on done flags when computing GAE return:

https://github.com/DLR-RM/stable-baselines3/blob/2bb4500948dccba3292135b1e295532fbc32f668/stable_baselines3/common/buffers.py#L349

For example, when GAE lambda is set to 1, the comment says that `R - V(s)` would be computed, where R is the discounted reward with bootstrap. What if bootstrap is not appropriate for certain envs (`done = 1` means done literally)?

Also, as the documentation for VecEnv points out, the real next observation is only available in `terminal_observation ` key of the `info` dictionary. However, I don't see the real next observation being used in computing the bootstrap.

### Checklist

- [x] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by araffin** [comment] 2021-11-04 08:32
Hello,
Duplicate of https://github.com/DLR-RM/stable-baselines3/issues/633

It currently does not (but you can use a `TimeFeatureWrapper` as in the RL Zoo) and we would welcome a PR that implements it ;)

**Comment by zhihanyang2022** [comment] 2021-11-04 08:42
> we would welcome a PR that implements proper handling of timeouts ;)

I'm happy to work on this, as it's related to my current project as well.

Before I proceed, I want to clear up a few things:
- (I asked this earlier) As the documentation for VecEnv points out, the real next observation is only available in terminal_observation key of the info dictionary. However, I don't see the real next observation being used in computing the bootstrap.
- How should one interpret `_last_episode_starts`, and why isn't `done` used instead? I've read #375 but I'm still not sure.

**Comment by araffin** [comment] 2021-11-04 09:06
> However, I don't see the real observation being used for bootstrapping in the current code for PPO, which is a bit weird to me.

it is not used because we don't bootstrap when `done=True` currently.

> nd why isn't the naming done used instead? 

compared to off-policy algorithms, everything is shifted by one, and we initialize `_last_episode_starts` to true:

https://github.com/DLR-RM/stable-baselines3/blob/master/stable_baselines3/common/base_class.py#L430 

PS: I will close this to have all the discussion in #633

**Closed by araffin** 2021-11-04 09:06 UTC
Labels: duplicate, question
