### ISSUE TITLE
[Bug]  on loading trained agent(td3), raised error: 'Box' object has no attribute 'shape'

### ISSUE THREAD

**Issue by yizhoucc** [DLR-RM/stable-baselines3#681] opened 2021-11-28 23:43 UTC
I think the problem is in save_util.py, when saving/loading, the decoded action_space.shape is represented as action_space._shape. thus, when loading the model and try to read the .shape attr, the code fails.
tested a fresh installation of stablebaselines3 using pip, version 1.3.0. gym version 0.19.

**Comment by yizhoucc** [comment] 2021-11-29 00:11
realized this is related to torch version, downgrade to torch 1.9.0 solve the problem for now. what is the recommended torch version for stablebaselines3 1.3.0?

**Comment by araffin** [comment] 2021-11-29 09:30
Probably a duplicate of https://github.com/DLR-RM/stable-baselines3/issues/573 where you have a mismatch between gym versions. You can use `.load("model.zip", print_system_info=True)` to debug it.

Anyway, please fill up the issue template completely.

**Closed** 2021-12-05 18:33 UTC
Labels: bug, duplicate, more information needed

**Comment by yizhoucc** [comment] 2022-02-03 03:44
some update on the issue. although its closed but it might help someone who experience similar problems. it turned out to be the torch version. I can't remember exactly what I found previously, but some name space changes from torch 1.9 to 1.10 makes loading trained agent stuck in a loop. in short, trained with one torch version and load in another torch version is not guaranteed to work.
