### ISSUE TITLE
[Dependency] support for newest supersuit 3.4.0 

### ISSUE THREAD

**Issue by spencerbug** [DLR-RM/stable-baselines3#916] opened 2022-05-21 19:52 UTC
Hello, I'm trying to get the [basic pistonball_v6 example (13 lines of code)](https://github.com/Farama-Foundation/PettingZoo/blob/master/tutorials/13_lines.py) working. If I download the latest versions of these 4 packages: gym, pettingzoo, supersuit, stable-baselines3, they are incompatible. 
It looks like 
stable-baselines3==1.5.0 (latest) depends on gym==0.21.0
supersuit 3.4.0 (latest) depends on gym >=0.22.0

Is there plans to update stable_baselines3 to support latest supersuit? Is there a known working version combination I could try just to evaluate this basic example so I can at least evaluate the framework?

(test_deps_supersuit_gym_stablebaselinev3_pettingzoo) sneilan@Macbook-Pro-Spencer-Work test_deps_supersuit_gym_stablebaselinev3_pettingzoo % pipenv install pettingzoo gym supersuit stable-baselines3                                                         
Installing pettingzoo...
Adding pettingzoo to Pipfile's [packages]...
✔ Installation Succeeded 
Installing gym...
Adding gym to Pipfile's [packages]...
✔ Installation Succeeded 
Installing supersuit...
Adding supersuit to Pipfile's [packages]...
✔ Installation Succeeded 
Installing stable-baselines3...
Adding stable-baselines3 to Pipfile's [packages]...
✔ Installation Succeeded 
Pipfile.lock (db4242) out of date, updating to (5d179e)...
Locking [dev-packages] dependencies...
Locking [packages] dependencies...
Building requirements...
Resolving dependencies...
✘ Locking Failed! 
[ResolutionFailure]:   File "/Users/sneilan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/pipenv/resolver.py", line 741, in _main
[ResolutionFailure]:       resolve_packages(pre, clear, verbose, system, write, requirements_dir, packages, dev)
[ResolutionFailure]:   File "/Users/sneilan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/pipenv/resolver.py", line 702, in resolve_packages
[ResolutionFailure]:       results, resolver = resolve(
[ResolutionFailure]:   File "/Users/sneilan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/pipenv/resolver.py", line 684, in resolve
[ResolutionFailure]:       return resolve_deps(
[ResolutionFailure]:   File "/Users/sneilan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/pipenv/utils.py", line 1395, in resolve_deps
[ResolutionFailure]:       results, hashes, markers_lookup, resolver, skipped = actually_resolve_deps(
[ResolutionFailure]:   File "/Users/sneilan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/pipenv/utils.py", line 1108, in actually_resolve_deps
[ResolutionFailure]:       resolver.resolve()
[ResolutionFailure]:   File "/Users/sneilan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/pipenv/utils.py", line 833, in resolve
[ResolutionFailure]:       raise ResolutionFailure(message=str(e))
[pipenv.exceptions.ResolutionFailure]: Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  First try clearing your dependency cache with $ pipenv lock --clear, then try the original command again.
 Alternatively, you can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
  Hint: try $ pipenv lock --pre if it is a pre-release dependency.
ERROR: Could not find a version that matches gym==0.21,>=0.21.0,>=0.22.0 (from -r /var/folders/1d/y0ctz0cj60qf3grpdb_tn2j80000gp/T/pipenvosmw1d0zrequirements/pipenv-_5r13xjl-constraints.txt (line 4))
Tried: 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.1.6, 0.1.7, 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.2.5, 0.2.6, 0.2.7, 0.2.8, 0.2.9, 0.2.10, 0.2.11, 0.2.12, 0.3.0, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.4.4, 0.4.5, 0.4.6, 0.4.8, 0.4.9, 0.4.10, 0.5.0, 0.5.1, 0.5.2, 0.5.3, 0.5.4, 0.5.5, 0.5.6, 0.5.7, 0.6.0, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.7.4, 0.8.0, 0.8.1, 0.8.2, 0.9.0, 0.9.1, 0.9.2, 0.9.3, 0.9.4, 0.9.5, 0.9.6, 0.9.7, 0.10.0, 0.10.1, 0.10.2, 0.10.3, 0.10.4, 0.10.5, 0.10.8, 0.10.9, 0.10.11, 0.11.0, 0.12.0, 0.12.1, 0.12.4, 0.12.5, 0.12.6, 0.13.0, 0.13.1, 0.14.0, 0.15.3, 0.15.4, 0.15.6, 0.15.7, 0.16.0, 0.17.0, 0.17.1, 0.17.2, 0.17.3, 0.18.0, 0.18.3, 0.19.0, 0.20.0, 0.21.0, 0.22.0, 0.23.0, 0.23.1
Skipped pre-versions: 0.8.0.dev0
There are incompatible versions in the resolved dependencies:
  gym (from -r /var/folders/1d/y0ctz0cj60qf3grpdb_tn2j80000gp/T/pipenvosmw1d0zrequirements/pipenv-_5r13xjl-constraints.txt (line 4))
  gym==0.21 (from stable-baselines3==1.5.0->-r /var/folders/1d/y0ctz0cj60qf3grpdb_tn2j80000gp/T/pipenvosmw1d0zrequirements/pipenv-_5r13xjl-constraints.txt (line 3))
  gym>=0.21.0 (from pettingzoo==1.18.1->-r /var/folders/1d/y0ctz0cj60qf3grpdb_tn2j80000gp/T/pipenvosmw1d0zrequirements/pipenv-_5r13xjl-constraints.txt (line 5))
  gym>=0.22.0 (from supersuit==3.4.0->-r /var/folders/1d/y0ctz0cj60qf3grpdb_tn2j80000gp/T/pipenvosmw1d0zrequirements/pipenv-_5r13xjl-constraints.txt (line 2))

**Comment by araffin** [comment] 2022-05-22 13:26
Duplicate of https://github.com/DLR-RM/stable-baselines3/issues/871

**Closed by araffin** 2022-05-22 13:26 UTC
Labels: duplicate, question
