### ISSUE TITLE
AssertionError: The algorithm only supports (<class 'gymnasium.spaces.box.Box'>,) as action spaces but Box(-1.0, 1.0, (4,), float32) was provided

### ISSUE THREAD

**Issue by Egbert1314** [DLR-RM/stable-baselines3#1714] opened 2023-10-14 08:23 UTC
### 🐛 Bug

AssertionError: The algorithm only supports (<class 'gymnasium.spaces.box.Box'>,) as action spaces but Box(-1.0, 1.0, (4,), float32) was provided

### To Reproduce

import multiprocessing
import sys
from pettingzoo.test import parallel_api_test
from citylearn import GridLearn
from citylearn import MyEnv
from pathlib import Path

from stable_baselines3.sac import MlpPolicy
from stable_baselines3 import SAC

import numpy as np
import supersuit as ss
from copy import deepcopy
import time
import os
import random

random.seed(12)
np.random.seed(12)
model_name = "test"
tic = time.time()
climate_zone = 1
data_path = Path("citylearn/data/Climate_Zone_"+str(climate_zone))#字符串格式str的加法
buildings_states_actions = 'citylearn/buildings_state_action_space.json'

config = {
    "model_name":model_name,
    "data_path":data_path,
    "climate_zone":climate_zone,
    "buildings_states_actions_file":buildings_states_actions,
    "hourly_timesteps":1,
    "percent_rl":0.5,
    "nclusters":1,
    "max_num_houses":None
}
grid = GridLearn(**config)
env = MyEnv(grid) #for _ in range(config['nclusters'])
env.grid = grid
env.initialize_rbc_agents()
print('creating pettingzoo env...')
env = ss.pettingzoo_env_to_vec_env_v1(env)
print('stacking vec env...')
env = ss.concat_vec_envs_v1(env, 1, num_cpus=1, base_class='stable_baselines3')
grid.normalize_reward()
model = SAC(MlpPolicy, env, ent_coef=0.1, learning_rate=0.001)

### Relevant log output / Error message

```shell
File D:\anaconda\envs\gridlearn3\lib\site-packages\spyder_kernels\py3compat.py:356 in compat_exec
    exec(code, globals, locals)
  File d:\spyder\gridlearn-master\gdemo3.py:87
    model = SAC(MlpPolicy, env, ent_coef=0.1, learning_rate=0.001)
  File D:\anaconda\envs\gridlearn3\lib\site-packages\stable_baselines3\sac\sac.py:120 in __init__
    super().__init__(
  File D:\anaconda\envs\gridlearn3\lib\site-packages\stable_baselines3\common\off_policy_algorithm.py:110 in __init__
    super().__init__(
  File D:\anaconda\envs\gridlearn3\lib\site-packages\stable_baselines3\common\base_class.py:180 in __init__
    assert isinstance(self.action_space, supported_action_spaces), (
AssertionError: The algorithm only supports (<class 'gymnasium.spaces.box.Box'>,) as action spaces but Box(-1.0, 1.0, (4,), float32) was provided
```

### System Info

gym 0.26.2
stable_line3 2.1.0
python 3.8

### Checklist

- [ ] My issue does not relate to a custom gym environment. (Use the custom gym env template instead)
- [ ] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [ ] I have provided a [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014) example to reproduce the bug
- [ ] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by qgallouedec** [comment] 2023-10-14 09:30
Duplicate of #1588 #1475 #1371 and #1274

**Comment by Egbert1314** [comment] 2023-10-14 09:56
I am so sorry for my first upload issue. Thanks for your help.

**Closed** 2023-10-14 10:02 UTC
Labels: bug
