### ISSUE TITLE
[Question] Should `evaluate_policy` reset the environment when episode is done ?

### ISSUE THREAD

**Issue by antoinebrl** [DLR-RM/stable-baselines3#719] opened 2022-01-05 12:03 UTC
### Question

I'm training a PPO agent and I observed a large gap between training and evalution in terms of performances. I know many things could be the reason for that but, as I was navigating through the code base I stumbled upon [`evaluate_policy`](https://github.com/DLR-RM/stable-baselines3/blob/d9e198e04fab39600781093ec9925aafdb9589f9/stable_baselines3/common/evaluation.py#L11). I was surprise to see no call to the reset method of the environment when the episode is completed. Should there be a `observations = env.reset()` under the `if dones[i]:` statement or am I missing something?
I'am happy to make a PR if this modification is deemed relevant.

### Checklist

- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo

**Comment by araffin** [comment] 2022-01-05 12:07
Duplicate of https://github.com/hill-a/stable-baselines/issues/1083
and as stated in the doc:
"When using vectorized environments, the environments are automatically reset at the end of each episode. "

https://stable-baselines3.readthedocs.io/en/master/guide/vec_envs.html

**Closed by araffin** 2022-01-05 12:07 UTC
Labels: question, RTFM

**Comment by antoinebrl** [comment] 2022-01-05 12:17
I knew the reset had to be done somewhere. I though `DummyVecEnv` was dummier than that ^^
Thanks for your quick answer!
