### ISSUE TITLE
[Bug]: pip install fails

### ISSUE THREAD

**Issue by Industrial** [DLR-RM/stable-baselines3#1341] opened 2023-02-20 13:15 UTC
### 🐛 Bug

Hi!

When I run `pip install --use-pep517 stable-baselines3` then I get a pip install error.

### To Reproduce

```bash
pip install --use-pep517 stable-baselines3
```

### Relevant log output / Error message

```shell
Collecting stable-baselines3
  Using cached stable_baselines3-1.7.0-py3-none-any.whl (171 kB)
Collecting gym==0.21
  Using cached gym-0.21.0.tar.gz (1.5 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      error in gym setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have provided a minimal working example to reproduce the bug
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment] 2023-02-20 13:30
> I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo

Duplicate of https://github.com/DLR-RM/stable-baselines3/issues/1324

**Closed by araffin** 2023-02-20 13:30 UTC
Labels: bug, duplicate
