### ISSUE TITLE
[Question] Is it possible to use custom LSTM and transformer models with MlpPolicy ActorCriticPolicy?

### ISSUE THREAD

**Issue by HaakonFlaaronning** [DLR-RM/stable-baselines3#1407] opened 2023-03-23 17:48 UTC
### ❓ Question

I want to use PPO and A2C with a custom LSTM and transformer network. PPO only have native support for "MlpPolicy" "CnnPolicy" and "MultiInputPolicy". Can I still use "MlpPolicy" but specify a custom LSTM or transformer network, or can it purely be used with networks that only have linear layers? Does it mess up the training if I specify a LSTM network? 

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment] 2023-03-24 09:24
Duplicate of https://github.com/DLR-RM/stable-baselines3/issues/1387, https://github.com/DLR-RM/stable-baselines3/issues/1077 https://github.com/DLR-RM/stable-baselines3/issues/177 and https://github.com/Stable-Baselines-Team/stable-baselines3-contrib/issues/165

For `RecurrentPPO`, please take a look at SB3 contrib (as written in the doc): https://sb3-contrib.readthedocs.io/en/master/modules/ppo_recurrent.html

**Comment by Pythoniasm** [comment] 2023-03-27 13:28
I can recommend to use a custom features extractor that does everything you want. However, you might want to adjust the MLP heads for critic and actor accordingly - but still using the MlpPolicy.

**Closed** 2023-03-31 11:40 UTC
Labels: duplicate, question
