### ISSUE TITLE
[Feature Request] Adding transformer (self-attention) policies/torch layers

### ISSUE THREAD

**Issue by ElPettego** [DLR-RM/stable-baselines3#1432] opened 2023-04-06 00:16 UTC
### 🚀 Feature

due to the recent proven stability and reliability of transformer i think we should implement  them in stable baselines. maybe creating an actor critic transformer policy?

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo

**Comment by araffin** [comment] 2023-04-06 04:56
> I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo

Please check harder next time...

Duplicate of https://github.com/Stable-Baselines-Team/stable-baselines3-contrib/issues/165 https://github.com/DLR-RM/stable-baselines3/issues/177 https://github.com/DLR-RM/stable-baselines3/issues/1387 https://github.com/DLR-RM/stable-baselines3/issues/1407 https://github.com/DLR-RM/stable-baselines3/issues/1077

**Closed by araffin** 2023-04-06 04:56 UTC
Labels: duplicate, enhancement
