### ISSUE TITLE
[Question]  Action and value net in Custome on-policy actorcritic net structure

### ISSUE THREAD

**Issue by cosmo86** [DLR-RM/stable-baselines3#1445] opened 2023-04-13 07:42 UTC
### ❓ Question

As I am reading the SB3 doc : https://stable-baselines3.readthedocs.io/en/master/guide/custom_policy.html  (Advanced Section), I understand how to customize ActorCriticPolicy network (how to customize value_net and policy_net in mlp_extractor)

But during implementation, I do not understand how action_net and value_net are created and I don't think it is specified in the doc  . 
<img width="467" alt="image" src="https://user-images.githubusercontent.com/51028745/231688136-2296c700-79c4-4c1c-a6dd-37aca65cadd5.png">

Could someone help me explain where does the action_net and value_net come from and how to customize them?

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment] 2023-04-13 07:58
"An extra linear layer will be added on top of the layers specified in net_arch, in order to have the right output dimensions and activation functions (e.g. Softmax for discrete actions)."

Those are required projection layers for policy/value networks.

Duplicate of https://github.com/DLR-RM/stable-baselines3/issues/1092

**Comment by cosmo86** [comment] 2023-04-13 08:48
@araffin  thank! I only searched keyword 'action net'

**Closed** 2023-04-23 21:21 UTC
Labels: duplicate, question
