### ISSUE TITLE
Model does not get updated when using DDPG and TD3

### ISSUE THREAD

**Issue by anilkurkcu** [DLR-RM/stable-baselines3#1034] opened 2022-08-26 02:53 UTC
Hello,

I have built a custom environment and using the callback function to check how my agent performs at every certain timesteps.

While there is no issue when using A2C, PPO, SAC, there is an issue with DDPG and TD3. The issue is that each time I do a callback and run the environment by first resetting and then evaluating my model, DDPG and TD3 no matter how long the total training timestep is give always the same reward value.

I am really curious why A2C, PPO and SAC do not get stuck with the same reward value, but DDPG and TD3 do. Is there any general rule of thumb about this?

**Comment by araffin** [comment] 2022-08-26 20:51
Please fill up the issue template completely, and this is probably a duplicate of #1032

**Comment by anilkurkcu** [comment] 2022-08-29 01:50
I tried with train_freq=1, but nothing seems to change. And I am sure my custom environment is able to reset after a certain amount of timesteps, but I am not sure whether TD3 would be aware of this. Would just setting the done flag to True be sufficient for the algorithm to know that the environment is being reset?

**Comment by araffin** [comment] 2022-08-29 03:31
Please fill up the issue template completely, this is the last time i'm asking.

please read https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014 before.

**Closed** 2022-08-29 04:48 UTC
Labels: question, custom gym env, more information needed
