### ISSUE TITLE
Can the stability of Stable-Baseline3 be consistently reproduced?

### ISSUE THREAD

**Issue by RupeshKeesaram** [DLR-RM/stable-baselines3#1808] opened 2024-01-15 17:43 UTC
###  Can the stability of Stable-Baseline3 be consistently reproduced ❓

Hello everyone,  I'm planning to create a MVP around stable-baseline3 but before that I'm trying to figure out whether the algorithms are deterministic or not ? Before raising this issue I've came across a [similar issue](https://github.com/DLR-RM/stable-baselines3/issues/369), which was closed without any conclusion. It would be really grateful if someone from the community or stable-baseline3 team can help me. 

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014)
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment] 2024-01-16 09:00
> whether the algorithms are deterministic or not ? 

They are (on the same os/with the same libraries version, see doc) and they are tested: https://github.com/DLR-RM/stable-baselines3/blob/master/tests/test_deterministic.py

Duplicate of https://github.com/DLR-RM/stable-baselines3/issues/557 (and others)

PS: the "stable" in SB3 has more to do with software quality than training results

**Comment by RupeshKeesaram** [comment] 2024-01-16 15:21
Sure, Thank you for your response @araffin.

**Closed** 2024-01-16 15:27 UTC
Labels: duplicate, question
