### ISSUE TITLE
Maskable ppo agent does not accept Discrete action space

### ISSUE THREAD

**Issue by aheidariiiiii1993** [DLR-RM/stable-baselines3#1588] opened 2023-07-03 08:25 UTC
### 🐛 Bug

Based on the documentations, maskable PPO agent can be used with discrete action space. But when using a custom environment with Discrete action space, I receive the error about the type of action space. The reproducable code is provided

`AssertionError: The algorithm only supports (<class 'gymnasium.spaces.discrete.Discrete'>, <class 'gymnasium.spaces.multi_discrete.MultiDiscrete'>, <class 'gymnasium.spaces.multi_binary.MultiBinary'>) as action spaces but Discrete(7) was provided`

### Code example

```
import pandas as pd  
import numpy as np 
from datetime import datetime, timedelta
import math
import matplotlib.pyplot as plt
import time  # to measure the computation time
import os 
from math import log, log10, exp, e, pow, sqrt 
import gym
from gym import spaces

from stable_baselines3.common.env_checker import check_env
from stable_baselines3 import PPO, A2C # DQN coming soon
from stable_baselines3.common.env_util import make_vec_env
from stable_baselines3 import PPO, A2C, DQN # DQN coming soon
from stable_baselines3.common.env_util import make_vec_env
from sb3_contrib import RecurrentPPO 
from stable_baselines3 import SAC 
from stable_baselines3.common.evaluation import evaluate_policy
from stable_baselines3.common.env_util import make_vec_env
from stable_baselines3.common.noise import NormalActionNoise
from sb3_contrib import QRDQN
import torch 
from sb3_contrib import RecurrentPPO
from sb3_contrib.common.maskable.policies import MaskableActorCriticPolicy
from sb3_contrib.common.wrappers import ActionMasker
from sb3_contrib.ppo_mask import MaskablePPO
from stable_baselines3.common.vec_env import DummyVecEnv 
from stable_baselines3 import TD3, SAC 
from stable_baselines3.common.noise import NormalActionNoise, OrnsteinUhlenbeckActionNoise

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import LSTM
from tensorflow.keras.models import load_model

import sys 

class EnergySystem_dis(gym.Env):

    def __init__ (self):
        super(EnergySystem_dis, self).__init__()
        
        n_actions = 7 
        n_states = 15

        self.action_space = spaces.Discrete(n_actions) 
                       
        self.observation_space = spaces.Box(low=0, high=1, shape=(n_states,), dtype=np.float32)
        
        self.MAX_STEPS = 48 #for the moment we test 24 hours 

        #self.seed() 
        
        self.Done = False 
        
        ##############################
        
    def reset (self):
        """
        Reset the state of the environment and returns an initial observation.

        Returns
        -------
        observation (object): the initial observation of the space.
        """
        ##################################################################
        # Reset other parameters
        self.count = 0 
        self.reward = 0
        self.done = False
        self.info = {}
        ###################################################################
        # Reset state
        
        #self.sim_start_time_actual=start_hour # what is actually in practice
    
        #self.sim_stop_time_actual=start_hour+1
        
        #self.sim_start_time_trnsys=start_hour 
    
        #self.sim_stop_time_trnsys=start_hour+1

        self.state=[0 for i in range(n_states)]  
        
        self.state = np.array(self.state).astype(np.float32)

        return self.state


    def step (self, action):
        
        self.action = action
       
        if self.done:
            # code should never reach this point
            print("EPISODE self.done!!!")

        elif self.count == self.MAX_STEPS:
            self.done = True
            self.episode_counter = self.episode_counter +1        
            print("End of episode= ", self.episode_counter)

        else:
            assert self.action_space.contains(action)
            self.count += 1
            self.done = False 

        ##################################################################################
        # Update states 

        self.state=[0 for i in range(n_states)]

        self.state = np.array(self.state).astype(np.float32)

        ##################################################################################
        # Update reward 

        

        self.reward = 0
        
    ##########################################################################
        
        info = {}

        return self.state, self.reward, self.done, info


    def render (self, mode="human"):
        pass 

    def close (self):
        """Override close in your subclass to perform any necessary cleanup.
        Environments will automatically close() themselves when
        garbage collected or when the program exits.
        """
        pass

environment_dis = EnergySystem_dis()  


def mask_fn(environment: gym.Env):
    
    mask = np.ones(environment.action_space.n, dtype=bool)
    
    # reduce possibility of comfort violation 
                        
    return mask.astype(bool)

# self.T_sp_w_FH=24
        
# self.T_sp_w_AHU=30
        
# self.T_sp_a_AHU=22


environment_dis = ActionMasker(environment_dis, mask_fn) 


model = MaskablePPO("MlpPolicy", 
                     environment_dis,
                     learning_rate=0.002,
                     verbose=0,
                     n_steps=48*7,
                     #batch_size =48,
                     #ent_coef = 0.1,
                     #n_epochs = 10,
                     #clip_range = 0.8
                     )
```

### Relevant log output / Error message

```shell
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
Cell In[9], line 19
      9 # self.T_sp_w_FH=24
     10         
     11 # self.T_sp_w_AHU=30
     12         
     13 # self.T_sp_a_AHU=22
     16 environment_dis = ActionMasker(environment_dis, mask_fn) 
---> 19 model = MaskablePPO("MlpPolicy", 
     20                      environment_dis,
     21                      learning_rate=0.002,
     22                      verbose=0,
     23                      n_steps=48*7,
     24                      #batch_size =48,
     25                      #ent_coef = 0.1,
     26                      #n_epochs = 10,
     27                      #clip_range = 0.8
     28                      )

File ~\anaconda3\lib\site-packages\sb3_contrib\ppo_mask\ppo_mask.py:103, in MaskablePPO.__init__(self, policy, env, learning_rate, n_steps, batch_size, n_epochs, gamma, gae_lambda, clip_range, clip_range_vf, normalize_advantage, ent_coef, vf_coef, max_grad_norm, target_kl, stats_window_size, tensorboard_log, policy_kwargs, verbose, seed, device, _init_setup_model)
     78 def __init__(
     79     self,
     80     policy: Union[str, Type[MaskableActorCriticPolicy]],
   (...)
    101     _init_setup_model: bool = True,
    102 ):
--> 103     super().__init__(
    104         policy,
    105         env,
    106         learning_rate=learning_rate,
    107         n_steps=n_steps,
    108         gamma=gamma,
    109         gae_lambda=gae_lambda,
    110         ent_coef=ent_coef,
    111         vf_coef=vf_coef,
    112         max_grad_norm=max_grad_norm,
    113         use_sde=False,
    114         sde_sample_freq=-1,
    115         stats_window_size=stats_window_size,
    116         tensorboard_log=tensorboard_log,
    117         policy_kwargs=policy_kwargs,
    118         verbose=verbose,
    119         seed=seed,
    120         device=device,
    121         _init_setup_model=False,
    122         supported_action_spaces=(
    123             spaces.Discrete,
    124             spaces.MultiDiscrete,
    125             spaces.MultiBinary,
    126         ),
    127     )
    129     self.batch_size = batch_size
    130     self.n_epochs = n_epochs

File ~\anaconda3\lib\site-packages\stable_baselines3\common\on_policy_algorithm.py:81, in OnPolicyAlgorithm.__init__(self, policy, env, learning_rate, n_steps, gamma, gae_lambda, ent_coef, vf_coef, max_grad_norm, use_sde, sde_sample_freq, stats_window_size, tensorboard_log, monitor_wrapper, policy_kwargs, verbose, seed, device, _init_setup_model, supported_action_spaces)
     58 def __init__(
     59     self,
     60     policy: Union[str, Type[ActorCriticPolicy]],
   (...)
     79     supported_action_spaces: Optional[Tuple[Type[spaces.Space], ...]] = None,
     80 ):
---> 81     super().__init__(
     82         policy=policy,
     83         env=env,
     84         learning_rate=learning_rate,
     85         policy_kwargs=policy_kwargs,
     86         verbose=verbose,
     87         device=device,
     88         use_sde=use_sde,
     89         sde_sample_freq=sde_sample_freq,
     90         support_multi_env=True,
     91         seed=seed,
     92         stats_window_size=stats_window_size,
     93         tensorboard_log=tensorboard_log,
     94         supported_action_spaces=supported_action_spaces,
     95     )
     97     self.n_steps = n_steps
     98     self.gamma = gamma

File ~\anaconda3\lib\site-packages\stable_baselines3\common\base_class.py:180, in BaseAlgorithm.__init__(self, policy, env, learning_rate, policy_kwargs, stats_window_size, tensorboard_log, verbose, device, support_multi_env, monitor_wrapper, seed, use_sde, sde_sample_freq, supported_action_spaces)
    177 self._vec_normalize_env = unwrap_vec_normalize(env)
    179 if supported_action_spaces is not None:
--> 180     assert isinstance(self.action_space, supported_action_spaces), (
    181         f"The algorithm only supports {supported_action_spaces} as action spaces "
    182         f"but {self.action_space} was provided"
    183     )
    185 if not support_multi_env and self.n_envs > 1:
    186     raise ValueError(
    187         "Error: the model does not support multiple envs; it requires " "a single vectorized environment."
    188     )

AssertionError: The algorithm only supports (<class 'gymnasium.spaces.discrete.Discrete'>, <class 'gymnasium.spaces.multi_discrete.MultiDiscrete'>, <class 'gymnasium.spaces.multi_binary.MultiBinary'>) as action spaces but Discrete(7) was provided
```

### System Info

gym version 0.26.2
stable_baselines3 version 2.0.0
Python version 3.10.9

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have provided a minimal working example to reproduce the bug
- [X] I have checked my env using the env checker
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment] 2023-07-03 09:02
Duplicate of https://github.com/DLR-RM/stable-baselines3/issues/1475 https://github.com/DLR-RM/stable-baselines3/issues/1371 and https://github.com/DLR-RM/stable-baselines3/issues/1274 and https://github.com/Farama-Foundation/Gymnasium/issues/348

**Closed by araffin** 2023-07-03 09:02 UTC
Labels: duplicate, custom gym env, check the checkboxes

**Comment by aheidariiiiii1993** [comment] 2023-07-03 09:12
@araffin I followed the template and provided a minimal working code with all the details. May I ask why did you close it again ?!

**Comment by araffin** [comment] 2023-07-03 09:15
> May I ask why did you close it again ?!

Did you read my comment? (which is also related to the checklist)

**Comment by aheidariiiiii1993** [comment] 2023-07-03 12:22
@araffin Yes, after following the chain of unanswered comments, I reached to #1274 as an answered one, which was not similar to my issue. Here I am using Discrete and I am still getting error.

**Comment by aheidariiiiii1993** [comment] 2023-07-03 12:33
@araffin The same cde has been working before I change my operating system

**Comment by araffin** [comment] 2023-07-03 13:02
>  I have checked my env using the env checker

if you would have used the env checker (as required), it would have told you that you must use gymnasium, not gym with SB3 v2.x (that's the same errors in the other issues, SB3 v1.x is compatible with gym 0.21 only).

The shimmy compatibility layer that allows to use gym env with gymnasium is brittle and only work for "raw" env (without any wrappers).
