### ISSUE TITLE
Are there best practises for ensuring reproducible results for multiple runs of model training?

### ISSUE THREAD

**Issue by manacoa** [DLR-RM/stable-baselines3#290] opened 2021-01-13 12:28 UTC
### Question

Are there any guidelines for how to make training sessions deterministic and reproducible? I'm training OpenAI Gym MuJoCo environments with PPO and my training graphs are different each time. Not sure if this is something I'm doing wrong or if it-s simply impossible. A checklist would be very useful.

### Additional context

What I've tried before each training session:

    seed = 0
    env.seed(seed)
    env.action_space.seed(seed)
    baselines3_set_random_seed(seed, using_cuda=True)
 
### Checklist

- [X ] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by Miffyli** [comment] 2021-01-13 13:08
Closing as duplicate of #292 .

**Closed by Miffyli** 2021-01-13 13:08 UTC
Labels: question
