### ISSUE TITLE
Update to numpy afftect atari wrapper

### ISSUE THREAD

**Issue by jp2294** [DLR-RM/stable-baselines3#895] opened 2022-04-30 21:40 UTC
### 🐛 Bug
Inside stable_baselines3/common/atari_wrappers.py in the class NoopResetEnv the call to randint is no longer supported in the latest versions of numpy.

```python
36: noops = self.unwrapped.np_random.randint(1, self.noop_max + 1)

```
I think the code should look like this but I haven't been able to get it working
```python
try:
  noops = self.unwrapped.np_random.integers(1, self.noop_max + 1)
except AttributeError:
  noops = self.unwrapped.np_random.randint(1, self.noop_max + 1)

```

### To Reproduce
Run the first 4 cells within atari_games.ipynb the google colab notebook and the error should appear as long as the latest version of numpy is used. If not to force the error add this code to the first cell to get the most recent version of numpy:
```python
!pip install numpy
```
https://colab.research.google.com/github/Stable-Baselines-Team/rl-colab-notebooks/blob/sb3/atari_games.ipynb#scrollTo=f3K4rMXwimBO

**Comment by araffin** [comment] 2022-04-30 21:54
Duplicate of https://github.com/DLR-RM/stable-baselines3/issues/875

**Closed by araffin** 2022-04-30 21:54 UTC
Labels: bug, duplicate

**Comment by araffin** [comment] 2022-04-30 21:59
I've pushed a temp fix in the meantime: https://github.com/Stable-Baselines-Team/rl-colab-notebooks/commit/65753761edd3b55db2d42aed3d478dfda857dae3
