### ISSUE TITLE
[Question] Type Error

### ISSUE THREAD

**Issue by Paulchen29** [DLR-RM/stable-baselines3#1263] opened 2023-01-08 13:35 UTC
### ❓ Question

Hi

I am currently creating a custom enviroment. 

`class PlacementEnv(gym.Env):

    def __init__(self, wp, sl):
        self.reward = None
        self.workpieces = wp
        self.slabs = sl

        # Define the observation space
        i = 1
        space_to_observe = {}

        for workpiece in self.workpieces:
            highx = workpiece.pointMax_X
            highy = workpiece.pointMax_Y
            low = np.array([0, 0])
            high = np.array([highx, highy])

            space_single_workpiece = {
                'points_workpiece' + str(i): gym.spaces.Box(low, high, shape=(2,), dtype=np.int16),
                'slabID_workpiece' + str(i): gym.spaces.Discrete(1)}
            space_to_observe = space_to_observe | space_single_workpiece
            i = i + 1

        dict_space = spaces.Dict(space_to_observe)
        self.observation_space = dict_space

        # Define action space
        # 1=Target Slab, 2=InsertionPoint X, 3=InsertionPoint Y, 4=Rotation Angle (future)
        self.action_space = spaces.MultiDiscrete([len(self.slabs), 3400, 2000])

    def reset(self):
        i = 1
        space_to_observe = {}

        for workpiece in self.workpieces:
            workpiece.slab_id = None
            workpiece.insertion_point = (0, 0)
            workpiece.rotation_angle = 0
            highx = workpiece.pointMax_X
            highy = workpiece.pointMax_Y
            low = np.array([0, 0])
            high = np.array([highx, highy])
            space_single_workpiece = {
                'points_workpiece' + str(i): gym.spaces.Box(low, high, shape=(2,), dtype=np.int16),
                'slabID_workpiece' + str(i): gym.spaces.Discrete(1)}
            space_to_observe = space_to_observe | space_single_workpiece
            i = i + 1

        dict_space = gym.spaces.Dict(space_to_observe)
        self.observation_space = dict_space
        return self.observation_space
`

Setting up the enviorment and model just work fine
`env = PlacementEnv(workpieces, slabs)
model = PPO('MultiInputPolicy', env, verbose=1)`

when it comes to: `model.learn(total_timesteps=10)` I get this error where I can't figure out where it comes from.
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'Box'

I know it happens in the dummy_vec_env.py _save_obs method 

![Scrennshot1](https://user-images.githubusercontent.com/35149760/211198894-7d254fa4-905e-4647-b223-2e3f82c92fce.PNG)
![Scrennshot2](https://user-images.githubusercontent.com/35149760/211198896-3f5b1488-fb73-4ebe-98c5-3f525950867d.PNG)

Any advise woud be highly appreciated. 

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by qgallouedec** [comment] 2023-01-08 13:48
Your question is actually about a custom environment. I am not able to tell you what the problem is but a very useful tool to help you debug your env:

```python
from stable_baselines3.common.env_checker import check_env

env = CustomEnv(arg1, ...)
# It will check your custom environment and output additional warnings if needed
check_env(env)
```

I close this issue because it is not in the right section. If the problem persists, I invite you to reopen a new issue by choosing the right template: Issues > Issue: 🤖 Custom Gym Environment Issue, which will help you explain your problem better so that we can better identify the error.

**Closed** 2023-01-08 13:48 UTC
Labels: question

**Comment by Paulchen29** [comment] 2023-01-08 14:34
Thank you very much. The check_env gave me a hint but I cannot resolve it but maybe others can. I will use the right template now.
