### ISSUE TITLE
No GPU usage when training DQN model

### ISSUE THREAD

**Issue by ashok-arora** [DLR-RM/stable-baselines3#1843] opened 2024-02-15 06:29 UTC
### 🐛 Bug

The model training never uses GPU vram and instead depends only on cpu which is slowing down the training. I did set the device as `cuda` in the DQN model training. 

### Code example

```python
import gymnasium as gym
import numpy as np
from gymnasium import spaces

from stable_baselines3 import A2C
from stable_baselines3.common.env_checker import check_env


class CustomEnv(gym.Env):

    def __init__(self):
        super().__init__()
        self.observation_space = spaces.Box(low=-np.inf, high=np.inf, shape=(14,))
        self.action_space = spaces.Box(low=-1, high=1, shape=(6,))

    def reset(self, seed=None, options=None):
        return self.observation_space.sample(), {}

    def step(self, action):
        obs = self.observation_space.sample()
        reward = 1.0
        terminated = False
        truncated = False
        info = {}
        return obs, reward, terminated, truncated, info

env = CustomEnv()
check_env(env)

model = A2C("MlpPolicy", env, verbose=1).learn(1000)
```

### System Info

```
- OS: Linux-6.5.0-17-generic-x86_64-with-glibc2.10 # 17~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Jan 16 14:32:32 UTC 2
- Python: 3.8.5
- Stable-Baselines3: 2.3.0a2
- PyTorch: 2.2.0+cu121
- GPU Enabled: True
- Numpy: 1.23.0
- Cloudpickle: 3.0.0
- Gymnasium: 0.29.1
- OpenAI Gym: 0.18.3
```

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have provided a [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014) example to reproduce the bug
- [X] I have checked my env using the env checker
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment] 2024-02-15 08:38
Hello,

> I did set the device as cuda in the DQN model training.

The code that you provide is using A2C, not DQN.
Does python shows up when you call `nvidia-smi`?

For small network, it is recommended to use CPU instead of GPU (usually faster) and play with `OMP_NUM_THREADS` env variable.

Anyway, I guess it is more a PyTorch issue than a SB3 one.

**Comment by ashok-arora** [comment] 2024-02-15 08:45
Oh sorry, I am using DQN, A2C and PPO with the SUMO simulator for traffic light control. Neither of them seem to be using gpu. 
Yeah, python does show up but its using only 404mb.

**Comment by araffin** [comment] 2024-02-15 08:50
>  Yeah, python does show up but its using only 404mb.

That's what I wrote, this is expected.

Duplicate of https://github.com/DLR-RM/stable-baselines3/issues/350 https://github.com/DLR-RM/stable-baselines3/issues/1245 https://github.com/hill-a/stable-baselines/issues/308 and many others...

**Closed by araffin** 2024-02-15 08:50 UTC
Labels: duplicate, custom gym env

**Comment by ashok-arora** [comment] 2024-02-15 08:53
@araffin I also tried to run the pendulum environment and that consumed about 30% gpu. Considering that both tasks are of similar simplicity, shouldn't it also use atleast that much?
