### ISSUE TITLE
Unexpected time between environment step function calls

### ISSUE THREAD

**Issue by jameszampa** [DLR-RM/stable-baselines3#1147] opened 2022-10-31 13:20 UTC
### Bug description
I have a custom gym environment for fighting the Tree Sentinel from Elden Ring and I will sometimes get upwards of 20+ seconds between step function calls.

### Additional context
I can't seem to identify reasons behind why the time between steps is occasionally very high. To me it seems random.

### Code example

https://github.com/jameszampa/EldenRingAI

EldenEnv.py is where the custom environment code is
EldenReward.py is where I compute all of my rewards
play_elden_ring.py is a Flask server where elden ring is actually played and keys are pressed

To reproduce you would need a Windows computer with elden ring, a Linux computer, and a capture card
on the windows computer running play_elden_ring.py will start a flask server that the linux computer will use to operate the game. Change line 107 in get_levels.py to your elden ring .sl2 file, start a new character and note which character slot it is in. If you have no characters created and make a character that would be character slot 1, and so on. in EldenEnv.py you will need to change line 136 and 138 to your capture card path and flask server ip (local ip of windows computer). Make you your capture card has chmod 777, for my example i do sudo chmod 777 /dev/video0. Change the first argument in line 154 to your character slot. Now launch play_elden_ring.py on the windows computer. Then you can start train.py on the linux computer. that should start elden ring, press continue, and the start fighting the tree sentinel. Make sure your character is loaded so continue loads the correct character. Make sure your respawn point is at the Limgrave grace outside of the tomb you start at. Where you get called maidenless. That should be it. Or ask me to run whatever change you are thinking :)

### Time between step calls
![image](https://user-images.githubusercontent.com/36577736/199014281-8c5c9055-0c25-4dcd-a28d-6653ff8d328e.png)
[Clip of bug happening](https://www.twitch.tv/eldenringai/clip/ExpensiveLightAlligatorSmoocherZ-ljP052lKHkF4xGm9)

### System Info

Conda environment
Pip installed packaged
Python 3.8.10
Pytorch 1.13.0
Gym 0.21.0
GPUs: 2 RTX A6000s w/ NVLink
```
import stable_baselines3 as sb
sb.get_system_info()
OS: Linux-5.15.0-52-generic-x86_64-with-glibc2.17 #58~20.04.1-Ubuntu SMP Thu Oct 13 13:09:46 UTC 2022
Python: 3.8.13
Stable-Baselines3: 1.6.2
PyTorch: 1.13.0
GPU Enabled: True
Numpy: 1.23.3
Gym: 0.21.0

({'OS': 'Linux-5.15.0-52-generic-x86_64-with-glibc2.17 #58~20.04.1-Ubuntu SMP Thu Oct 13 13:09:46 UTC 2022', 'Python': '3.8.13', 'Stable-Baselines3': '1.6.2', 'PyTorch': '1.13.0', 'GPU Enabled': 'True', 'Numpy': '1.23.3', 'Gym': '0.21.0'}, 'OS: Linux-5.15.0-52-generic-x86_64-with-glibc2.17 #58~20.04.1-Ubuntu SMP Thu Oct 13 13:09:46 UTC 2022\nPython: 3.8.13\nStable-Baselines3: 1.6.2\nPyTorch: 1.13.0\nGPU Enabled: True\nNumpy: 1.23.3\nGym: 0.21.0\n')
```

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [ ] I have provided a minimal working example to reproduce the bug
- [X] I have checked my env using the env checker
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by jameszampa** [comment] 2022-10-31 13:22
https://github.com/openai/gym/issues/3141

**Comment by araffin** [comment] 2022-10-31 13:41
>  I have provided a minimal working example to reproduce the bug

See https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014 for a definition of what is "minimal" ;)

**Comment by jameszampa** [comment] 2022-10-31 13:49
Yeah, sorry there isn't really a "minimal" solution to reproduce this bug.

**Comment by araffin** [comment] 2022-10-31 14:19
Closing as this issue was already posted in gym/RL Discord.
I'll re-open it if a minimal code to reproduce the issue is provided.

**Closed by araffin** 2022-10-31 14:19 UTC
Labels: question, custom gym env, more information needed, No tech support

**Comment by jameszampa** [comment] 2022-10-31 14:48
Thanks for taking the time @araffin :)

**Comment by araffin** [comment] 2022-10-31 16:19
> I added a "minimal" code example, let me know if that is what is expected thanks
> See https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014 for a definition of what is "minimal" ;)

quoting https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014 again:
"this code is not minimal because one line can be deleted without removing the error:"

**Comment by jameszampa** [comment] 2022-10-31 17:40
@araffin I striped out everything that isn't required to reproduce the bug. When you get the chance let me know if this is correct

**Comment by araffin** [comment] 2022-10-31 18:00
Hello,
thanks for giving it a try (it's better even though it's still not minimal and self-contained, as I would need the elden game to reproduce the error).
It seems that you have some `time.sleep(5 * 60)` in your code which may explain your issue.

**Comment by jameszampa** [comment] 2022-10-31 18:17
That code is there to allow steam to cloud sync when Elden ring crashes, I can confirm that is not my issue, as the time between steps would be 5 minutes, I am seeing 20-30 seconds occasionally. Thanks again for looking into my issue

**Comment by jameszampa** [comment] 2022-10-31 18:20
Again from my understanding this hanging happens in-between step function calls. The tensorboard logs showing time_between_steps illustrates that with consistent time between steps being close to zero and then out of the blue 20+ seconds

**Comment by jameszampa** [comment] 2022-11-01 01:07
@araffin I believe I have determined what is causing the large time between step calls.
[Example 1](https://clips.twitch.tv/FurtiveDifficultAuberginePoooound-0p7G0JqM70YIJc4F)
[Example 2](https://clips.twitch.tv/DoubtfulKindNoodleResidentSleeper-EjKi3b6UvTqsYlEx)
It seems to correlate with the logs, is there anyway to disable this? Thinking about this more I might need to implement a real-time gym https://github.com/yannbouteiller/rtgym since Elden Ring is disconnected from gym. Does this theory sound correct? Id love to know your thoughts thank you!

**Comment by jameszampa** [comment] 2022-11-01 16:22
I believe I am understanding this issue more. Is there a way to collected the rollout buffer on reset rather than after an arbitrary number of n_steps?

**Comment by qgallouedec** [comment] 2022-11-01 16:41
> * [x]  I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo

Seems duplicate #1059

**Comment by jameszampa** [comment] 2022-11-01 17:34
Thanks :) @qgallouedec
