### ISSUE TITLE
[Bug]: AttributeError: 'tuple' object has no attribute 'shape'

### ISSUE THREAD

**Issue by AFpxx** [DLR-RM/stable-baselines3#1641] opened 2023-08-07 20:34 UTC
### 🐛 Bug

while testing the result of supermario something went wrong

### To Reproduce

from nes_py.wrappers import JoypadSpace
import gym_super_mario_bros
from gym_super_mario_bros.actions import SIMPLE_MOVEMENT
from stable_baselines3 import PPO

env = gym_super_mario_bros.make('SuperMarioBros-v0',apply_api_compatibility=True,render_mode="human" )
JoypadSpace.reset = lambda self, **kwargs: self.env.reset(**kwargs)
env = JoypadSpace(env, SIMPLE_MOVEMENT)

model = PPO.load('./train/best_model_1000000', env=env)
vec_env = env
obs = vec_env.reset()
done=True
while True:
    if done:
        env.reset()
    action, _states=model.predict(obs, deterministic=True)
    obs, reward, done, info = vec_env.step(action)
    vec_env.render("human")
    env.render()
env.close()

### Relevant log output / Error message

```shell
D:\anaconda3\lib\site-packages\stable_baselines3\common\vec_env\patch_gym.py:49: UserWarning: You provided an OpenAI Gym environment. We strongly recommend transitioning to Gymnasium environments. Stable-Baselines3 is automatically wrapping your environments in a compatibility layer, which could potentially cause issues.
  warnings.warn(
Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.
Wrapping the env in a VecTransposeImage.
Traceback (most recent call last):
  File "c:\Users\silve\Desktop\super\test.py", line 17, in <module>
    action, _states=model.predict(obs, deterministic=None)
  File "D:\anaconda3\lib\site-packages\stable_baselines3\common\base_class.py", line 555, in predict
    return self.policy.predict(observation, state, episode_start, deterministic)
  File "D:\anaconda3\lib\site-packages\stable_baselines3\common\policies.py", line 346, in predict
    observation, vectorized_env = self.obs_to_tensor(observation)
  File "D:\anaconda3\lib\site-packages\stable_baselines3\common\policies.py", line 257, in obs_to_tensor
    observation = maybe_transpose(observation, self.observation_space)       
  File "D:\anaconda3\lib\site-packages\stable_baselines3\common\preprocessing.py", line 84, in maybe_transpose
    if not (observation.shape == observation_space.shape or observation.shape[1:] == observation_space.shape):
AttributeError: 'tuple' object has no attribute 'shape'
```

### System Info

pip
python 3.10.9
gym 0.26.2

### Checklist

- [X] My issue does not relate to a custom gym environment. (Use the custom gym env template instead)
- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have provided a [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014) example to reproduce the bug
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment] 2023-08-08 04:16
>  have checked that there is no similar issue in the repo

Duplicate of https://github.com/DLR-RM/stable-baselines3/issues/1594 and 
https://github.com/DLR-RM/stable-baselines3/issues/1637#issuecomment-1656802361

Please follow carefully the examples from the documentation.

**Closed by araffin** 2023-08-08 04:16 UTC
Labels: duplicate, RTFM, check the checkboxes

**Comment by AFpxx** [comment] 2023-08-08 12:11
ok, let me try it
