### ISSUE TITLE
The training process does not stop even at timestep = 1.

### ISSUE THREAD

**Issue by NghiaPhamttk27** [DLR-RM/stable-baselines3#1717] opened 2023-10-18 05:18 UTC
### 🐛 Bug

I'm not sure why, but I can't save my model. When I run the command 
```
model.learn(total_timesteps=1,reset_num_timesteps=True)
model.save(f"{model_path}")
```
my training process almost never stops, and the model isn't saved. You can take a look at my GitHub repository for the entire code (https://github.com/NghiaPhamttk27/GridWorld). This is just a simple repo, and I'm not sure where I went wrong, but when I code:
```
obs, info = env.reset()
n_steps = 1
for _ in range(n_steps):
    # Random action
    action = env.action_space.sample()
    obs, reward, done, truncated, info = env.step(action)
    if done:
        model.save(f"{model_path}")
        obs, info = env.reset()
```
then the training process actually stops after the first step.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have provided a [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014) example to reproduce the bug
- [X] I have checked my env using the env checker
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment] 2023-10-18 06:08
Duplicate of https://github.com/DLR-RM/stable-baselines3/issues/1150

**Closed by araffin** 2023-10-18 06:08 UTC
Labels: duplicate, custom gym env, check the checkboxes
