### ISSUE TITLE
SB3 Discrete action space generate wrong number from user-defined action space

### ISSUE THREAD

**Issue by cosmo86** [DLR-RM/stable-baselines3#1378] opened 2023-03-12 07:29 UTC
### 🐛 Bug

When user define a custome env with Discrete action space witg negative start, Eg: Discrete(20,start = -10), SB3,during training, should not generate actions that is outside the range (-10,10).
However, it seems like SB3 will convert the start to 0 dispect of user's defination of start.

### To Reproduce

import gym
from gym import spaces
import numpy as np
from stable_baselines3 import PPO

class DummyboxEnv2(gym.Env):
    metadata = {"render_modes": None}
    def __init__(self, render_mode=None):
        super().__init__()
        # action and observation spaces
        self.observation_space = spaces.Dict({
                                             'a':spaces.Box(-3, 3, (1, 10,6), np.float32),
                                             'b':spaces.Box(low=0,high=1,dtype=np.float32),
                                             'c':spaces.Box(low=0,high=1,dtype=np.float32)
                                                })
        self.action_space = spaces.Discrete(21,start = -10)
        
    def step(self, action):
        print('action is: ', action)
        observation = self.observation_space.sample()
        reward = 1
        terminated = False
        info = {}
        return observation, reward, terminated, False, info

    def reset(self, seed=None):
        super().reset(seed=seed)
        observation = self.observation_space.sample()
        info = {}
        return observation, info
    def render(self):
        pass

env = DummyboxEnv2()
model = PPO('MultiInputPolicy', env, verbose = 1).learn(10)

### Relevant log output / Error message

```shell
As one can see, the action is between (0,20) when the user defined it to be (-10,10)
action is:  16
action is:  1
action is:  5
action is:  5
action is:  5
action is:  8
action is:  9
action is:  20
action is:  0
action is:  6
action is:  19
action is:  13
action is:  8
action is:  20
action is:  10
action is:  14
action is:  8
action is:  3
action is:  5
action is:  17
action is:  10
action is:  20
action is:  4
action is:  1
action is:  9
action is:  4
action is:  12
action is:  10
action is:  9
action is:  4
action is:  6
action is:  10
.....
.....
```

### System Info

- OS: Windows-10-10.0.22621-SP0 10.0.22621
- Python: 3.9.7
- Stable-Baselines3: 2.0.0a0
- PyTorch: 1.11.0
- GPU Enabled: True
- Numpy: 1.20.3
- Gym: 0.26.2

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have provided a minimal working example to reproduce the bug
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment] 2023-03-12 07:33
> I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo

Duplicate of #913 #1295 
The env checker should have warned you too.

**Closed by araffin** 2023-03-12 07:33 UTC
Labels: bug, duplicate

**Comment by cosmo86** [comment] 2023-03-13 01:07
thanks for the reply!
