### ISSUE TITLE
How to optimize parameters on a custom environment?

### ISSUE THREAD

**Issue by JingZhang918** [DLR-RM/stable-baselines3#641] opened 2021-11-01 08:40 UTC
As the title said. I'm having trouble with optimize my algorithm. Could anyone recommend something? I'm using PPO and the agent doesn't respond to the environment at all.

**Comment by araffin** [comment] 2021-11-01 08:52
Closing as duplicate of https://github.com/DLR-RM/rl-baselines3-zoo/issues/168
Please read the readme, note that we do not offer tech support.

**Closed by araffin** 2021-11-01 08:52 UTC
Labels: question, custom gym env, RTFM

**Comment by araffin** [comment] 2021-11-01 09:03
as you seem to try to apply RL to stock trading, i also must warn you about it. Here is recommendation from a former professional trader:
"
Retail trading, retail trading with ML, and retail trading with RL are bad ideas for almost everyone to get involved with. 
* I was a quant trader at a major hedge fund for several years. I am now retired.
* On average, traders lose money. On average, retail traders especially lose money. An excellent approximation of trading, and especially of retail trading, is 'gambling'. 
* There is a lot more bad advice on trading out there than good advice. It is extraordinarily difficult to demonstrate that any particular advice is some of the rare good advice.
* As such, it's reasonable to treat all commentary on retail trading as an epsilon away from snake oil salesmanship. Sometimes that'll be wrong, but it's a strong rule of thumb. 
* I feel a sense of responsibility to the less world-wise members of this community - which includes plenty of highschoolers - and so I find myself unable to let a conversation about retail trading occur without interceding and warning that it's very likely snake oil. 
* I find repeatedly making these warnings and the subsequent fights to be exhausting.

"

**Comment by JingZhang918** [comment] 2021-11-01 09:17
Yes, that is what I'm trying to do. The warning quoted is rather depressing cause I've always thought there's a way to do this and right now I don't know how to respond. But thank you for giving me the new information. 
However, this is my master thesis. I have to find a way to make it work. This is the last piece of my puzzle. Isn't there any way?
