### ISSUE TITLE
reccurent policy

### ISSUE THREAD

**Issue by E666GT** [DLR-RM/stable-baselines3#210] opened 2020-11-01 03:29 UTC
is there a easy way to implement a recurrent policy now in the bate BS3?

I notice these is not such policy like lstm. But, we are in urgently need that.

Thanks!

**Comment by Miffyli** [comment] 2020-11-01 14:20
Closing as duplicate of #1 and #160. 

LSTM/Recurrent support is planned for v1.1.

**Closed by Miffyli** 2020-11-01 14:20 UTC
Labels: duplicate

**Comment by sycz00** [comment] 2021-12-01 14:54
@Miffyli 
Hey I hope its okay to post that into this thread and not one of the others.
I know that recurrent policies are not available in SB3 atm. I am working on a project for which I need some sort of recurrent structure, since its a POMDP env. My question is: do you think it could work using a TCN in the end of my custom feature extractor to learn long term dependencies ? because as far as I've understood, a TCN does not need BPTT. 
Greetings:)

**Comment by Miffyli** [comment] 2021-12-01 14:57
@sycz00 TCN (temporal convolution network, I assume?) could work for that case. There is now also an experimental LSTM support for PPO [here](https://github.com/Stable-Baselines-Team/stable-baselines3-contrib/pull/53). You need to experiment to find out what works for your case :)

**Comment by sycz00** [comment] 2021-12-01 14:59
Yes thats what I mean. Wow thats amazing, thank you. Iam gonna look into this

**Comment by sycz00** [comment] 2021-12-01 15:35
pip install git+https://github.com/Stable-Baselines-Team/stable-baselines3-contrib
does not contain the ppo_lstm branch ?

**Comment by Miffyli** [comment] 2021-12-01 15:42
@sycz00 You need to checkout `feat/ppo-lstm` branch, not `ppo_lstm`.

**Comment by sycz00** [comment] 2021-12-01 17:58
@Miffyli Thanks:)

It looks like MultiInputPolicy is not available yet ? cause I got dict observation space. For now I am trying it with just one image.

**Comment by araffin** [comment] 2021-12-01 17:59
> It looks like MultiInputPolicy is not available yet ? cause I got dict observation space. For now I am trying it with just one image.

it is not (yet) but you can add the support, it is mostly a question of copy-pasting what is in the replay buffer code...

**Comment by sycz00** [comment] 2021-12-01 18:04
Okay good:) does the LSTM only exists for the actor ? if yes, why ? :)
