### ISSUE TITLE
[Question] How to retrieve the DQN loss value ?

### ISSUE THREAD

**Issue by carlos-UPC-AI** [DLR-RM/stable-baselines3#1761] opened 2023-11-21 22:01 UTC
### ❓ Question

In the context of utilizing Stable Baselines3 (SB3) for DQN, a challenge arises in acquiring direct access to the loss value, which is not readily available through the existing functions provided by SB3. The necessity for comprehensive control over the loss value becomes apparent, particularly when considering its application in a Federated Learning aggregation strategy. Is there a method to effectively retrieve the loss value in SB3?

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014)
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment] 2023-11-21 22:11
Hello,
have you considered a callback that has access to the logger? (cf. doc and other issues).

Probably a duplicate of https://github.com/DLR-RM/stable-baselines3/issues/1558

PS: you don't need a LLM for that type of question

**Closed** 2023-12-04 16:51 UTC
Labels: duplicate, question, RTFM
