### ISSUE TITLE
Integrating minigrid

### ISSUE THREAD

**Issue by AvivSham** [DLR-RM/stable-baselines3#689] opened 2021-12-08 16:48 UTC
Hi all,
Thank you for your wonderful contribution and repository!
I'm trying to integrate [minigrid (custom gym env)](https://github.com/maximecb/gym-minigrid) with stable baselines but I encounter shape related errors.
The env was checked using `check_env` and received `None`.
When passing observations through model shape related error pops up, it seems to be a miss match with channels first/last format. I also notice the following print on the command line: `Wrapping the env in a VecTransposeImage.` this what causes the problem (from what I can tell).

Code snip used to init the env:
```
import gym
import gym_minigrid
from gym_minigrid.wrappers import RGBImgPartialObsWrapper, ImgObsWrapper
from stable_baselines3.common.monitor import Monitor

env = gym.make('MiniGrid-Empty-8x8-v0')
env = RGBImgPartialObsWrapper(env)  # Get pixel observations
env = ImgObsWrapper(env)  # Get rid of the 'mission' field
env.reset()
env = Monitor(env)
```

My code base is really big if additional code is required it will be provided.

System Info
Describe the characteristic of your environment:
 * Installed using pip
 * Same problem on both CPU/GPU
 * python version 3.7.11
 * PyTorch version 1.9.1
 * Gym version 0.17.2
 * gym_minigrid latest commit in master branch

- [YES] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [YES] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)
- [YES] I have checked my env using the env checker (**required**)
- [PARTIAL] I have provided a minimal working example to reproduce the bug (**required**)

@AvivNavon

**Comment by araffin** [comment] 2021-12-08 17:08
> When passing observations through model shape related error pops up, 

Please provide traceback and minimal example to reproduce the error

> I also notice the following print on the command line: Wrapping the env in a VecTransposeImage. this what causes the problem (from what I can tell).

Probably a duplicate of https://github.com/DLR-RM/stable-baselines3/issues/671 
could you confirm? (if so, we would appreciate a PR that solves this issue, see discussion in #671)

**Comment by AvivSham** [comment] 2021-12-11 09:59
If there is a consensus between all envs where the first channel is either [RGB, RGBD, GrayScale, or object space (like in MinAtar)] than you always want to wrap the env with ImageTranspose to ensure the "image" dimensions are last.
Am I wrong here?

**Comment by araffin** [comment] 2021-12-11 10:24
We do that because of PyTorch channel first convention, but the wrapper relies on a heuristic.

**Comment by AvivSham** [comment] 2021-12-11 10:35
I understand that, but if in all envs the first two dimensions represent the image space than it is reasonable to enforce ImageTranspose wrapper. Currently the heuristic method does not cover lots of cases (e.g. binary image, normalized image [-1, 1]).

**Comment by araffin** [comment] 2021-12-11 10:41
the heuristic is just a heuristic (see issue #671 ), and we have the doc and env checker to help the user with recommandations for custom envs.

**Comment by AvivSham** [comment] 2021-12-11 10:49
I don't understand why you need the following [checks](https://github.com/DLR-RM/stable-baselines3/blob/master/stable_baselines3/common/preprocessing.py#L43) (both type and value range) images can be represented in multiple types, in addition the range can vary due to normalization.

**Comment by AvivSham** [comment] 2021-12-11 10:51
If I understand correctly ImageTranspose wrapper only permutes observations by keeping type/value range untouched isn't it?

**Comment by araffin** [comment] 2021-12-11 15:32
> I don't understand why you need the following checks (both type and value range) images can be represented in multiple types, in addition the range can vary due to normalization.

See note in https://stable-baselines3.readthedocs.io/en/master/guide/custom_env.html
This check is mainly used for pre-processing and normalising the image if needed:
https://github.com/DLR-RM/stable-baselines3/blob/88e1be9ff5e04b7688efa44951f845b7daf5717f/stable_baselines3/common/preprocessing.py#L102-L104

To check correct range, we have the env checker.

> If I understand correctly ImageTranspose wrapper only permutes observations by keeping type/value range untouched isn't it?

https://github.com/DLR-RM/stable-baselines3/blob/88e1be9ff5e04b7688efa44951f845b7daf5717f/stable_baselines3/common/vec_env/vec_transpose.py#L55-L65

**Comment by AvivSham** [comment] 2021-12-15 16:52
Additional question: 
When I'm using an mingrid env suddenly there are no logs (the code is running I don't get any error). Is there any connection to the wrappers in any why? or what can cause this?

**Comment by araffin** [comment] 2021-12-16 11:47
>  When I'm using an mingrid env suddenly there are no logs (the code is running I don't get any error). Is there any connection to the wrappers in any why? or what can cause this?

Probably a duplicate of https://github.com/DLR-RM/stable-baselines3/issues/251 and https://github.com/DLR-RM/stable-baselines3/issues/232 . Please read the documentation...
Otherwise, please fill the issue template.

**Closed** 2021-12-23 15:12 UTC
Labels: question, custom gym env
