### ISSUE TITLE
[Bug] The entropy coefficient remains constant throughout training when the model is loaded from a saved checkpoint model

### ISSUE THREAD

**Issue by Atlis** [DLR-RM/stable-baselines3#391] opened 2021-04-13 15:30 UTC
### 🐛 Bug
The entropy coefficient (ent_coef) remains constant throughout training when the model is loaded from a saved checkpoint model.
This is not expected since ent_coef was set to "auto".

### To Reproduce
1. Train a model with the TQC algo with the ent_coef set to "auto".
2. Observe that the ent_coef value varies (in the Tensorboard interface).
3. Save the trained model to a file using the CheckpointCallback.
4. Stop the training.
5. Start a new training using a saved checkpoint making sure ent_coef is still set to "auto".
6. Observe that the ent_coef value remain constant throughout training (in the Tensorboard interface).

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)
- [x] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [x] I have provided a minimal working example to reproduce the bug (**required**) (described in the steps to reproduce above)

**Comment by araffin** [comment] 2021-04-13 15:45
Hello,

thanks for reporting the issue =)

I could reproduce the bug using the following code:

```python
from sb3_contrib import TQC

policy_kwargs = dict(net_arch=[64], n_critics=1)
model = TQC("MlpPolicy", "Pendulum-v0", policy_kwargs=policy_kwargs, verbose=1, seed=1)
model.learn(2000)
ent_coef = model.log_ent_coef
env = model.get_env()
model.save("tqc_pendulum")

del model

model = TQC.load("tqc_pendulum", env=env)
model.learn(2000)
new_ent_coef = model.log_ent_coef

print(ent_coef, new_ent_coef)

```

the issue seems to be also present for SAC (as TQC is mostly SAC + distributional RL).
I will take a look soon.

next time, please provide a minimal working example and your config (steps to reproduce is ok-ish but a minimal code example is easier for us to reproduce and debug ;) ).

**Comment by Atlis** [comment] 2021-04-13 15:50
Ok, I take note of this. Thank you very much!

**Comment by araffin** [comment] 2021-04-13 15:50
The issue seems to come from the ent coef optimizer which is not linked to the correct variable after loading.

**Comment by araffin** [comment] 2021-04-13 16:25
I pushed a fix here: https://github.com/DLR-RM/stable-baselines3/pull/392

**Closed** 2021-04-15 12:50 UTC
Labels: bug
