### ISSUE TITLE
[Question] EvalCallback and Monitor wrapped env

### ISSUE THREAD

**Issue by drozzy** [DLR-RM/stable-baselines3#418] opened 2021-05-05 02:51 UTC
### Question

Why does EvalCallback make use (or encourage) the use of the Monitor wrapper?

It seems like EvalCallback already does the *same* thing as the monitor - namely it aggregates the rewards and counts the episode lengths.

What is the use case that this tackles?

The only special case I can see that triggers this is if the *evaluation* environment is wrapped with some reward/episode-length altering wrapper. But why would one wrap the evaluation environment?

### Checklist

- [x] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by araffin** [comment] 2021-05-05 05:42
Duplicate of https://github.com/DLR-RM/stable-baselines3/issues/181

**Closed by araffin** 2021-05-05 05:42 UTC
Labels: duplicate, question
