### ISSUE TITLE
[Bug]: Loaded weights are different from saved weights

### ISSUE THREAD

**Issue by BolunDai0216** [DLR-RM/stable-baselines3#1458] opened 2023-04-16 21:59 UTC
### 🐛 Bug

When I was loading the weights it was different from the weights that were saved. There maybe similar issues, but I don't think the issue is solved.

### To Reproduce

```python
env = gym.make("CartPole-v1")
model = PPO("MlpPolicy", env, verbose=1)
model.learn(total_timesteps=1e3)
model.save("models/ppo/cartpole")
action_net_weights = model.policy.action_net.weight
del model

# Create Environement
env = gym.make("CartPole-v1")

# Load Model
ppo = PPO("MlpPolicy", env, verbose=1)
ppo.load("models/ppo/cartpole")
loaded_action_net_weights = ppo.policy.action_net.weight

print(loaded_action_net_weights - action_net_weights)
```

### System Info

```
- OS: Linux-5.15.0-69-generic-x86_64-with-glibc2.31 # 76~20.04.1-Ubuntu SMP Mon Mar 20 15:54:19 UTC 2023
- Python: 3.9.16
- Stable-Baselines3: 2.0.0a0
- PyTorch: 2.0.0+cu117
- GPU Enabled: True
- Numpy: 1.24.2
- Gym: 0.28.0
```

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have provided a minimal working example to reproduce the bug
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment] 2023-04-16 22:15
> I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo


Duplicate of https://github.com/DLR-RM/stable-baselines3/issues/533 and https://github.com/DLR-RM/stable-baselines3/issues/614#issuecomment-996220319 and https://github.com/DLR-RM/stable-baselines3/issues/683#issuecomment-996213446

> have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)

we have an explicit warning in the doc, and your code does not follow the examples present in the doc.

**Closed by araffin** 2023-04-16 22:15 UTC
Labels: bug, duplicate, RTFM

**Comment by BolunDai0216** [comment] 2023-04-16 22:18
I see, can't believe I missed that.
