### ISSUE TITLE
How to use functions of the original class after vectorization

### ISSUE THREAD

**Issue by longziyu** [DLR-RM/stable-baselines3#1423] opened 2023-04-02 04:09 UTC
### ❓ Question

I run the following code：

```
env = My_Env(...)
env = DummyVecEnv([lambda: env])
```

In My_Env , a function `count()` is defined. When the environment is not vectorized, ` env. count() `can be called to display the value of each moment of reinforcement learning.
However, when I use `env = DummyVecEnv([lambda: env])` , there is an `AttributeError: ' DummyVecEnv' object has no attribute 'count'`
I have read the source code of `DummyVecEnv`. Its definition process does not inherit the class functions of env.
However, my `count()` function involves other variables in `My_Env` class, and it is not possible to simply add `count(`) to the `DummyVecEnv` initialization function.
I was wondering how to use functions in `My_Env` after running `env=DummyVecEnv ([lambda: env])` .

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by qgallouedec** [comment] 2023-04-02 05:10
Check out ˋvec_env. env_method`

**Comment by araffin** [comment] 2023-04-05 18:26
Probably duplicate of https://github.com/DLR-RM/stable-baselines3/issues/1249 too

**Closed by araffin** 2023-04-05 18:26 UTC
Labels: duplicate, question, RTFM
