### ISSUE TITLE
[Bug]: `env_checker` assumes termination/truncation signal is native python-only boolean

### ISSUE THREAD

**Issue by fracapuano** [DLR-RM/stable-baselines3#1795] opened 2023-12-24 17:32 UTC
## Problem
The **env_checker utility assumes termination/truncation signals are exclusively native-python boolean values**, but it is common for people (myself included---to be transparent, I might be biased on this) to implement their environments using numpy.

## Proposed Solution
This can be fixed with relatively limited effort, by just changing [these three lines](https://github.com/DLR-RM/stable-baselines3/blob/master/stable_baselines3/common/env_checker.py#L328:L330)
Into:
```python
# Assertions
assert isinstance(reward, (float, int)), "The reward returned by `step()` must be a float or a one-dimensional NumPy array"
if isinstance(reward, np.ndarray):
    try:
        reward = reward.item()
    except: 
        raise AssertionError(f"rewards must be scalar values only! You provided {reward} with shape {reward.shape}")
assert isinstance(terminated, (bool, np.bool_)), "The `terminated` signal must be a boolean or a NumPy boolean"
assert isinstance(truncated, (bool, np.bool_)), "The `truncated` signal must be a boolean or a NumPy boolean"
```

I have checked if using **`np.bool_` signals** could cause any trouble **in training**, and it seems **everything works just fine**.
Happy to discuss this through, but I feel it is a relatively quick win that would benefit us environment writers :)

### To Reproduce

```python
from stable_baselines3.common.env_checker import check_env
import gymnasium as gym
import numpy as np
from numpy.typing import NDArray


class MyEnv(gym.Env):
    def __init__(self):
        super().__init__()
        # just for reproducibility
        self.observation_space = gym.spaces.Box(low=-1, high=1, shape=(1,)) 
        self.action_space = gym.spaces.Discrete(2)

        # maximum number of steps per episode
        self.max_steps = 100

    def _get_info(self):
        return {
            "timestep_counter": self.timestep,
            "max_steps": self.max_steps
        }

    def reset(self, seed:int=None):
        super().reset(seed=seed)
        self.timestep = 0
        return self.observation_space.sample(), self._get_info()
    
    def is_terminated(self):
        """
        Evaluates process termination condition. 
        In this case, the process is terminated when the agent is close enough to the boundary of the obs space.
        """
        # self.get_distance_from_boundary() returns a NDArray object
        return self.get_distance_from_boundary() < 0.1
    
    def is_truncated(self):
        return self.timestep >= self.max_steps
    
    def get_distance_from_boundary(self)->NDArray:
        return np.abs(1-self.observation_space.sample())

    def step(self, action):
        self.timestep += 1
        reward = 1  # fictional reward for fictional step method

        return self.observation_space.sample(), reward, self.is_terminated(), self.is_truncated(), self._get_info()
    
env = MyEnv()
check_env(env, warn=True)  # raises AssertionError: The `terminated` signal must be a boolean
```

### Relevant log output / Error message

```shell
check_env(env, warn=True)
  File "/Users/68372/miniconda3/envs/oscarenv/lib/python3.10/site-packages/stable_baselines3/common/env_checker.py", line 461, in check_env
    _check_returned_values(env, observation_space, action_space)
  File "/Users/68372/miniconda3/envs/oscarenv/lib/python3.10/site-packages/stable_baselines3/common/env_checker.py", line 329, in _check_returned_values
    assert isinstance(terminated, bool), "The `terminated` signal must be a boolean"
AssertionError: The `terminated` signal must be a boolean
```

### System Info

- OS: macOS-13.6.2-arm64-arm-64bit Darwin Kernel Version 22.6.0: Thu Nov  2 07:43:25 PDT 2023; root:xnu-8796.141.3.701.17~6/RELEASE_ARM64_T6020
- Python: 3.10.13
- Stable-Baselines3: 2.2.1
- PyTorch: 2.1.1
- GPU Enabled: False
- Numpy: 1.26.2
- Cloudpickle: 3.0.0
- Gymnasium: 0.29.1

### Checklist

- [X] My issue does not relate to a custom gym environment. (Use the custom gym env template instead)
- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have provided a [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014) example to reproduce the bug
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment] 2024-01-10 10:27
Hello,

this is somewhat a duplicate of https://github.com/DLR-RM/stable-baselines3/issues/1747

This is to be consistent with the type annotations.
An easy fix is to cast to bool.

But I would agree this might be slightly inconsistent when implementing vectorized `compute_reward()` method for HER replay buffer.

**Closed** 2024-02-14 12:34 UTC
Labels: bug, duplicate
