### ISSUE TITLE
[Question] Multi-agent env multiple reward

### ISSUE THREAD

**Issue by cocozxh** [DLR-RM/stable-baselines3#876] opened 2022-04-19 20:04 UTC
I have noticed that the env checker requires the reward to be float but in some previous cases, like Multi-agent particle environment (https://github.com/openai/multiagent-particle-envs), the reward can be a NumPy array. So I am wondering how to implement a multiagent environment if the reward cannot be an array now.

**Comment by Miffyli** [comment] 2022-04-19 20:07
SB3 is designed for single-agents envs only, and support multi-agent envs like this would be too much out from this scope. I recommend to look at more multi-agent oriented libraries like [SuperSuit](https://github.com/Farama-Foundation/SuperSuit/) and [PettingZoo](https://github.com/Farama-Foundation/PettingZoo/).

**Comment by araffin** [comment] 2022-04-20 09:22
closing as out of scope of the repo (and partial duplicate of #69 )

**Closed by araffin** 2022-04-20 09:22 UTC
Labels: question
