### ISSUE TITLE
[Question] how write mask_fn to mask multi discrete？

### ISSUE THREAD

**Issue by yiptsangkin** [DLR-RM/stable-baselines3#1799] opened 2024-01-04 09:40 UTC
### ❓ Question

i set the action space MultiDiscrete([2, 3, 4])

if i want to mask the action like [1, 0, 3] and [0, 2, 4]，how to write the mask_fn?

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014)
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment] 2024-01-10 15:11
Hello,
this issue is for the SB3 contrib repo.
I guess it is a duplicate of https://github.com/Stable-Baselines-Team/stable-baselines3-contrib/issues/80 ?
The action mask must be flattened.
I would appreciate if you could update the documentation to add a note about it (if it is not already there).

**Closed by araffin** 2024-01-10 15:11 UTC
Labels: question, Maintainers on vacation
