### ISSUE TITLE
How to log custom variables to tensorboard in step

### ISSUE THREAD

**Issue by jiangzhangze** [DLR-RM/stable-baselines3#1518] opened 2023-05-23 06:33 UTC
### ❓ Question

I have a custom gym environment with `reward = 10 - drag - lift`.Now I want to log both `drag` and `lift` in tensorboard.What should I do.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment] 2023-05-23 06:40
> I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)

What have you read/tried so far?

**Comment by jiangzhangze** [comment] 2023-05-23 07:06
I got this random value tutorial from documention:
`import numpy as np

from stable_baselines3 import SAC
from stable_baselines3.common.callbacks import BaseCallback

model = SAC("MlpPolicy", "Pendulum-v1", tensorboard_log="/tmp/sac/", verbose=1)


class TensorboardCallback(BaseCallback):
    def __init__(self, verbose=0):
        super().__init__(verbose)

    def _on_step(self) -> bool:
        # Log scalar value (here a random variable)
        value = np.random.random()
        self.logger.record("random_value", value)
        return True


model.learn(50000, callback=TensorboardCallback())`
But I don't know how to get value from environment.

**Comment by qgallouedec** [comment] 2023-05-23 07:07
Seems to be duplicate of #1437

**Comment by araffin** [comment] 2023-05-23 07:26
Vecmonitor won't log to tensorboard but both "accessing summary writer" section in the doc and #1437 will give you the answer.

**Closed by araffin** 2023-05-23 07:26 UTC
Labels: duplicate, question, custom gym env, RTFM
