### ISSUE TITLE
[Bug] Numpy Attribute Error on A2C learn()

### ISSUE THREAD

**Issue by lagatorc** [DLR-RM/stable-baselines3#929] opened 2022-06-05 17:23 UTC
### 🐛 Bug

When I created an A2C model and ran the learn function I received an AttributeError from numpy.

### To Reproduce
```python
import gym
from stable_baselines3 import A2C
from stable_baselines3.common.vec_env import VecFrameStack
from stable_baselines3.common.env_util import make_atari_env

env = make_atari_env("Breakout-v0", n_envs=4, seed=0)
env = VecFrameStack(env, n_stack=4)

log_path = os.path.join("training", "logs")
model = A2C("CnnPolicy", env, verbose=True, tensorboard_log=log_path)

model.learn(total_timesteps=100000)
```
### Expected behavior

model.learn() should throw this error:

```bash
AttributeError: 'numpy.random._generator.Generator' object has no attribute 'randint'
```

### System Info

OS: Linux-5.13.0-44-generic-x86_64-with-glibc2.10 #49~20.04.1-Ubuntu SMP Wed May 18 18:44:28 UTC 2022
Python: 3.8.5
Stable-Baselines3: 1.5.0
PyTorch: 1.11.0+cu102
GPU Enabled: False
Numpy: 1.22.4
Gym: 0.21.0

- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)
- [x] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [x] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by araffin** [comment] 2022-06-05 17:37
Duplicate of https://github.com/DLR-RM/stable-baselines3/issues/875

**Closed by araffin** 2022-06-05 17:37 UTC
Labels: bug, duplicate

**Comment by lagatorc** [comment] 2022-06-05 17:46
Thank you, sorry I did not find that duplicate issue.
