### ISSUE TITLE
[Bug] 'EntryPoints' object has no attribute 'get' on import of SB3

### ISSUE THREAD

**Issue by joelmichelson** [DLR-RM/stable-baselines3#1101] opened 2022-10-06 18:32 UTC
### 🐛 Bug

AttributeError is thrown on import of SB3. 
![image](https://user-images.githubusercontent.com/8634827/194390057-6ee6d3f5-b8b2-494f-96f1-543a99b08f8a.png)

### To Reproduce

In a google colab notebook, run 

```!pip install stable_baselines3```

```import stable_baselines3```

It appears that this error happens on importing gym.spaces, but this error does *not* happen when importing gym without SB3. 

### Expected behavior

Successful import

### System Info

Google colab notebook

Reproduced with notebooks running on both 
Intel(R) Xeon(R) CPU @ 2.20GHz and AMD EPYC 7B12

### Checklist

- [ x ] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)
- [ x ] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [ x ] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by araffin** [comment] 2022-10-06 18:39
Hello,
what is your gym version and what is your `importlib_metadata` version?

Probably related to https://github.com/DLR-RM/stable-baselines3/pull/1088
`pip install "importlib-metadata~=4.13"` should solve this issue.

**Comment by araffin** [comment] 2022-10-06 18:40
Duplicate of https://github.com/openai/gym/issues/3119

**Closed** 2022-10-06 18:47 UTC
Labels: duplicate, more information needed, openai gym
