### ISSUE TITLE
Attention mechanism / Transformer architecture

### ISSUE THREAD

**Issue by anilkurkcu** [DLR-RM/stable-baselines3#1387] opened 2023-03-15 10:31 UTC
### 🚀 Feature

Hi, since these days attention mechanisms and transformer architectures are everywhere, I thought that it would be good to have this also in SB3. I have found this implementation:

https://peterbloem.nl/blog/transformers

There is also the code available, what is needed is just to be able to create a suitable custom environment that would support it.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo

**Comment by araffin** [comment] 2023-03-15 16:30
> I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo

Duplicate of https://github.com/DLR-RM/stable-baselines3/issues/1077 https://github.com/DLR-RM/stable-baselines3/issues/177 and https://github.com/Stable-Baselines-Team/stable-baselines3-contrib/issues/165

**Closed by araffin** 2023-03-15 16:30 UTC
Labels: duplicate, enhancement
