### ISSUE TITLE
[Question] Tuple action spaces?

### ISSUE THREAD

**Issue by nollied** [DLR-RM/stable-baselines3#920] opened 2022-05-26 07:33 UTC
i'm writing a custom environment and the action space for which is a tuple of a few different spaces. I was trying to use PPO, and i received the following error:

```
AssertionError: The algorithm only supports (<class 'gym.spaces.box.Box'>, <class 'gym.spaces.discrete.Discrete'>, <class 'gym.spaces.multi_discrete.MultiDiscrete'>, <class 'gym.spaces.multi_binary.MultiBinary'>) as action spaces but Tuple(Discrete(4), Box([0.], [1.], (1,), float32), Box([0. 0.], [1. 1.], (2,), float32), Box([-0.05 -0.05], [0.05 0.05], (2,), float32)) was provided
```

are there any algorithms that are ready for tuplized action spaces out the box? if not, do you have an idea for a workaround?

**Comment by araffin** [comment] 2022-05-26 09:22
Duplicate of https://github.com/DLR-RM/stable-baselines3/issues/731 and #527

**Closed by araffin** 2022-05-26 09:22 UTC
Labels: duplicate, question
